hmcts/nfdiv-case-api

charts/nfdiv-case-api/Chart.yaml, charts/nfdiv-case-api/values.aat.template.yaml
https://tools.hmcts.net/jira/browse/NFDIV-479
Fix chart and values
```
[ ] Yes
[ X ] No
```
=> Add tag to chart and set to false in AAT

ccd-definitions/src/main/java/uk/gov/hmcts/reform/divorce/ccd/DevelopmentCcdConfig.java, ccd-definitions/src/main/java/uk/gov/hmcts/reform/divorce/ccd/event/DraftCreate.java, ccd-definitions/src/main/java/uk/gov/hmcts/reform/divorce/ccd/event/PatchCase.java, ccd-definitions/src/main/java/uk/gov/hmcts/reform/divorce/ccd/model/CaseEvent.java, ccd-definitions/src/main/java/uk/gov/hmcts/reform/divorce/ccd/model/Constants.java
=> Add more models

charts/nfdiv-case-api/Chart.yaml, charts/nfdiv-case-api/values.yaml
=> add autoscaling

charts/nfdiv-case-api/Chart.yaml, charts/nfdiv-case-api/values.yaml
=> add CPU params 80%

api/build.gradle
Switch back to tomcat 9 as 10 isn't compatible with spring boot.
=> use latest tomcat 9

.editorconfig, api/build.gradle, api/src/integrationTest/java/uk/gov/hmcts/reform/divorce/caseapi/config/SwaggerPublisherTest.java, api/src/main/java/uk/gov/hmcts/reform/divorce/caseapi/config/EmailTemplatesConfig.java, api/src/main/java/uk/gov/hmcts/reform/divorce/caseapi/config/NotificationsConfiguration.java, api/src/main/java/uk/gov/hmcts/reform/divorce/caseapi/enums/EmailTemplateNames.java, api/src/main/java/uk/gov/hmcts/reform/divorce/caseapi/enums/LanguagePreference.java, api/src/main/java/uk/gov/hmcts/reform/divorce/caseapi/enums/NotificationConstants.java, api/src/main/java/uk/gov/hmcts/reform/divorce/caseapi/exceptions/NotificationException.java, api/src/main/java/uk/gov/hmcts/reform/divorce/caseapi/notification/handler/SaveAndSignOutNotificationHandler.java, api/src/main/java/uk/gov/hmcts/reform/divorce/caseapi/service/NotificationService.java, api/src/main/resources/application.yaml, api/src/test/java/uk/gov/hmcts/reform/divorce/caseapi/CaseApiTest.java, api/src/test/java/uk/gov/hmcts/reform/divorce/caseapi/notification/handler/SaveAndSignOutNotificationHandlerTest.java, api/src/test/java/uk/gov/hmcts/reform/divorce/caseapi/service/NotificationServiceTest.java, ccd-definitions/settings.gradle, ccd-definitions/src/main/java/uk/gov/hmcts/reform/divorce/ccd/model/CaseData.java, ccd-definitions/src/main/java/uk/gov/hmcts/reform/divorce/ccd/model/enums/DivorceOrDissolution.java, charts/nfdiv-case-api/Chart.yaml, charts/nfdiv-case-api/values.yaml, config/owasp/suppressions.xml, config/pmd/ruleset.xml, settings.gradle
https://tools.hmcts.net/jira/browse/NFDIV-410
- Added Notification service which will be used by different notification handlers.
- Added save and sign out notification handler.
- Added unit tests.
- Updated case data to include missing fields.
```
[ ] Yes
[x ] No
```
=> Implement service to use gov notify for sending save and signout notification

ccd-definitions/src/main/java/uk/gov/hmcts/reform/divorce/ccd/event/PatchCase.java, ccd-definitions/src/main/java/uk/gov/hmcts/reform/divorce/ccd/model/CaseData.java, ccd-definitions/src/test/java/uk/gov/hmcts/reform/divorce/ccd/event/PatchCaseTest.java
https://tools.hmcts.net/jira/browse/NFDIV-525
Added the jurisdiction fields to case data and to a the patch event
```
[ ] Yes
[ X ] No
```
=> Nfdiv-525: jurisdiction fields

ccd-definitions/src/main/java/uk/gov/hmcts/reform/divorce/ccd/event/PatchCase.java, ccd-definitions/src/main/java/uk/gov/hmcts/reform/divorce/ccd/model/CaseData.java, ccd-definitions/src/test/java/uk/gov/hmcts/reform/divorce/ccd/event/PatchCaseTest.java
https://tools.hmcts.net/jira/browse/NFDIV-300
adding the LanguagePreferenceWelsh field
```
[ ] Yes
[x] No
```
=> adding the language preference field

Jenkinsfile_CNP, ccd-definitions/src/main/java/uk/gov/hmcts/reform/divorce/ccd/DevelopmentCcdConfig.java
=> configure callback urls

api/build.gradle, ccd-definitions/build.gradle, ccd-definitions/src/main/java/uk/gov/hmcts/reform/divorce/ccd/Permissions.java, ccd-definitions/src/main/java/uk/gov/hmcts/reform/divorce/ccd/event/SaveAndClose.java, ccd-definitions/src/main/java/uk/gov/hmcts/reform/divorce/ccd/model/CaseData.java, ccd-definitions/src/test/java/uk/gov/hmcts/reform/divorce/ccd/event/SaveAndCloseTest.java, ccd-definitions/src/test/java/uk/gov/hmcts/reform/divorce/ccd/mock/EventBuildingMockUtil.java
Update ccd-config-generator to version 0.15.2
=> Update ccd-config-generator to version 0.15.2

ccd-definitions/src/main/java/uk/gov/hmcts/reform/divorce/ccd/event/SolicitorUpdate.java, ccd-definitions/src/test/java/uk/gov/hmcts/reform/divorce/ccd/event/SolicitorUpdateTest.java
=> Fix solicitorCreate save

ccd-definitions/src/main/java/uk/gov/hmcts/reform/divorce/ccd/event/PatchCase.java, ccd-definitions/src/main/java/uk/gov/hmcts/reform/divorce/ccd/model/CaseData.java, ccd-definitions/src/test/java/uk/gov/hmcts/reform/divorce/ccd/event/PatchCaseTest.java
https://tools.hmcts.net/jira/browse/NFDIV-422
```
[ ] Yes
[X] No
```
=> adding the certificate name fields

ccd-definitions/src/main/java/uk/gov/hmcts/reform/divorce/ccd/event/PatchCase.java, ccd-definitions/src/main/java/uk/gov/hmcts/reform/divorce/ccd/model/CaseData.java, ccd-definitions/src/test/java/uk/gov/hmcts/reform/divorce/ccd/event/PatchCaseTest.java
[NFDIV-427](https://tools.hmcts.net/jira/browse/NFDIV-427) English Version - Where did you get married page / form your civil partnership
Adds Where did you get married fields.
```
[ ] Yes
[x] No
```
=> feat(NFDIV-427): Added country/place fields

ccd-definitions/src/main/java/uk/gov/hmcts/reform/divorce/ccd/model/CaseData.java, ccd-definitions/src/test/java/uk/gov/hmcts/reform/divorce/ccd/event/PatchCaseTest.java
[NFDIV-250](https://tools.hmcts.net/jira/browse/NFDIV-250) How the court will contact you
Adds additional `PetitionerAgreedToReceiveEmails` field.
```
[ ] Yes
[x] No
```
=> feat(NFDIV-250): How the court will contact you fields

api/src/integrationTest/java/uk/gov/hmcts/reform/divorce/caseapi/controllers/SaveAndCloseControllerTest.java, api/src/main/resources/application.yaml, api/src/test/java/uk/gov/hmcts/reform/divorce/caseapi/notification/handler/SaveAndSignOutNotificationHandlerTest.java
Updated template to match ID in new account
=> update notify template

api/build.gradle, ccd-definitions/build.gradle, ccd-definitions/src/main/java/uk/gov/hmcts/reform/divorce/ccd/CcdPageConfiguration.java, ccd-definitions/src/main/java/uk/gov/hmcts/reform/divorce/ccd/event/solicitor/SolicitorCreate.java, ccd-definitions/src/main/java/uk/gov/hmcts/reform/divorce/ccd/event/solicitor/SolicitorStatementOfTruthPaySubmit.java, ccd-definitions/src/main/java/uk/gov/hmcts/reform/divorce/ccd/event/solicitor/SolicitorUpdate.java, ccd-definitions/src/main/java/uk/gov/hmcts/reform/divorce/ccd/event/solicitor/page/HelpWithFees.java, ccd-definitions/src/main/java/uk/gov/hmcts/reform/divorce/ccd/event/solicitor/page/SolPayAccount.java, ccd-definitions/src/main/java/uk/gov/hmcts/reform/divorce/ccd/event/solicitor/page/SolPayment.java, ccd-definitions/src/main/java/uk/gov/hmcts/reform/divorce/ccd/event/solicitor/page/SolPaymentSummary.java, ccd-definitions/src/main/java/uk/gov/hmcts/reform/divorce/ccd/event/solicitor/page/SolStatementOfTruth.java, ccd-definitions/src/main/java/uk/gov/hmcts/reform/divorce/ccd/event/solicitor/page/SolSummary.java, ccd-definitions/src/main/java/uk/gov/hmcts/reform/divorce/ccd/model/CaseData.java, ccd-definitions/src/main/java/uk/gov/hmcts/reform/divorce/ccd/model/State.java, ccd-definitions/src/main/java/uk/gov/hmcts/reform/divorce/ccd/model/enums/SolServiceMethod.java, ccd-definitions/src/main/java/uk/gov/hmcts/reform/divorce/ccd/model/enums/SolToPay.java, ccd-definitions/src/test/java/uk/gov/hmcts/reform/divorce/ccd/event/solicitor/SolicitorCreateTest.java, ccd-definitions/src/test/java/uk/gov/hmcts/reform/divorce/ccd/event/solicitor/SolicitorStatementOfTruthPaySubmitTest.java, ccd-definitions/src/test/java/uk/gov/hmcts/reform/divorce/ccd/event/solicitor/SolicitorUpdateTest.java, ccd-definitions/src/test/java/uk/gov/hmcts/reform/divorce/ccd/event/solicitor/page/HelpWithFeesTest.java, ccd-definitions/src/test/java/uk/gov/hmcts/reform/divorce/ccd/event/solicitor/page/SolPayAccountTest.java, ccd-definitions/src/test/java/uk/gov/hmcts/reform/divorce/ccd/event/solicitor/page/SolPaymentSummaryTest.java, ccd-definitions/src/test/java/uk/gov/hmcts/reform/divorce/ccd/event/solicitor/page/SolPaymentTest.java, ccd-definitions/src/test/java/uk/gov/hmcts/reform/divorce/ccd/event/solicitor/page/SolStatementOfTruthTest.java, ccd-definitions/src/test/java/uk/gov/hmcts/reform/divorce/ccd/event/solicitor/page/SolSummaryTest.java, ccd-definitions/src/test/java/uk/gov/hmcts/reform/divorce/ccd/mock/EventBuildingMockUtil.java
Add solicitor-statement-of-truth-pay-submit event
Add event pages and fields
=> Add solicitor case submit event

api/src/functionalTest/java/uk/gov/hmcts/reform/divorce/caseapi/SolicitorSubmitPetitionTest.java, api/src/functionalTest/resources/responses/ccd-callback-submit-petition.json, api/src/integrationTest/java/uk/gov/hmcts/reform/divorce/caseapi/controllers/SolicitorSubmitPetitionControllerTest.java, api/src/main/java/uk/gov/hmcts/reform/divorce/caseapi/model/payments/FeeResponse.java, api/src/main/resources/application.yaml, ccd-definitions/src/main/java/uk/gov/hmcts/reform/divorce/ccd/event/solicitor/SolicitorStatementOfTruthPaySubmit.java, ccd-definitions/src/test/java/uk/gov/hmcts/reform/divorce/ccd/event/solicitor/SolicitorStatementOfTruthPaySubmitTest.java
https://tools.hmcts.net/jira/browse/NFDIV-542
=> Added functional test for about to start callback - solicitor submit

ccd-definitions/src/main/java/uk/gov/hmcts/reform/divorce/ccd/event/PatchCase.java, ccd-definitions/src/main/java/uk/gov/hmcts/reform/divorce/ccd/model/CaseData.java, ccd-definitions/src/test/java/uk/gov/hmcts/reform/divorce/ccd/event/PatchCaseTest.java
https://tools.hmcts.net/jira/browse/NFDIV-424
```
[ ] Yes
[X] No
```
=> adding the last name changed when married property

ccd-definitions/src/main/java/uk/gov/hmcts/reform/divorce/ccd/event/solicitor/SolicitorCreate.java, ccd-definitions/src/main/java/uk/gov/hmcts/reform/divorce/ccd/event/solicitor/SolicitorUpdate.java, ccd-definitions/src/main/java/uk/gov/hmcts/reform/divorce/ccd/event/solicitor/page/SolAboutThePetitioner.java, ccd-definitions/src/main/java/uk/gov/hmcts/reform/divorce/ccd/event/solicitor/page/SolAboutTheRespondent.java, ccd-definitions/src/main/java/uk/gov/hmcts/reform/divorce/ccd/event/solicitor/page/SolAboutTheSolicitor.java, ccd-definitions/src/test/java/uk/gov/hmcts/reform/divorce/ccd/event/solicitor/SolicitorCreateTest.java, ccd-definitions/src/test/java/uk/gov/hmcts/reform/divorce/ccd/event/solicitor/SolicitorStatementOfTruthPaySubmitTest.java, ccd-definitions/src/test/java/uk/gov/hmcts/reform/divorce/ccd/event/solicitor/SolicitorUpdateTest.java, ccd-definitions/src/test/java/uk/gov/hmcts/reform/divorce/ccd/event/solicitor/page/SolAboutThePetitionerTest.java, ccd-definitions/src/test/java/uk/gov/hmcts/reform/divorce/ccd/event/solicitor/page/SolAboutTheRespondentTest.java, ccd-definitions/src/test/java/uk/gov/hmcts/reform/divorce/ccd/event/solicitor/page/SolAboutTheSolicitorTest.java
Update SolicitorCreate and SolicitorUpdate to use paged configuration
=> Update solicitor-create and solicitor-update to split into pages

ccd-definitions/src/main/java/uk/gov/hmcts/reform/divorce/ccd/event/PatchCase.java, ccd-definitions/src/test/java/uk/gov/hmcts/reform/divorce/ccd/event/PatchCaseTest.java
[NFDIV-463](https://tools.hmcts.net/jira/browse/NFDIV-463) Enter your address
Adds address field. Can be data from a postcode lookup, address inputs or single text area.
```
[ ] Yes
[x] No
```
=> feat(NFDIV-463): Added address field

api/build.gradle, ccd-definitions/build.gradle, ccd-definitions/src/main/java/uk/gov/hmcts/reform/divorce/ccd/caserole/CaseRoles.java, ccd-definitions/src/test/java/uk/gov/hmcts/reform/divorce/ccd/caserole/CaseRolesTest.java
Add CaseRoles.json generation to CCD definition.
=> Add CaseRoles to ccd definition

build.gradle
Reverts hmcts/nfdiv-case-api#93
=> Revert "Bump org.owasp.dependencycheck from 6.1.2 to 6.1.3"

ccd-definitions/src/main/java/uk/gov/hmcts/reform/divorce/ccd/event/PatchCase.java, ccd-definitions/src/test/java/uk/gov/hmcts/reform/divorce/ccd/event/PatchCaseTest.java
https://tools.hmcts.net/jira/browse/NFDIV-425
```
[ ] Yes
[X] No
```
=> adding patch case for field

ccd-definitions/src/main/java/uk/gov/hmcts/reform/divorce/ccd/event/PatchCase.java, ccd-definitions/src/test/java/uk/gov/hmcts/reform/divorce/ccd/event/PatchCaseTest.java
=> adding fields to patch case

Jenkinsfile_CNP, api/src/functionalTest/java/uk/gov/hmcts/reform/divorce/caseapi/DefaultLanguagePreferenceSettingTest.java, api/src/functionalTest/java/uk/gov/hmcts/reform/divorce/caseapi/SolicitorSubmitPetitionTest.java, api/src/functionalTest/java/uk/gov/hmcts/reform/divorce/caseapi/TestResourceUtil.java, api/src/functionalTest/resources/responses/ccd-callback-set-language-preference.json, api/src/functionalTest/resources/responses/ccd-callback-submit-petition.json, api/src/integrationTest/java/uk/gov/hmcts/reform/divorce/caseapi/controllers/SolicitorCreateControllerTest.java, api/src/integrationTest/resources/set-language-preference-response.json, api/src/main/java/uk/gov/hmcts/reform/divorce/caseapi/controllers/SolicitorCreateController.java, api/src/test/java/uk/gov/hmcts/reform/divorce/caseapi/TestConstants.java, api/src/test/java/uk/gov/hmcts/reform/divorce/caseapi/controllers/SolicitorCreateControllerTest.java, ccd-definitions/src/main/java/uk/gov/hmcts/reform/divorce/ccd/event/solicitor/SolicitorCreate.java, ccd-definitions/src/main/java/uk/gov/hmcts/reform/divorce/ccd/event/solicitor/SolicitorUpdate.java, ccd-definitions/src/main/java/uk/gov/hmcts/reform/divorce/ccd/event/solicitor/page/LanguagePreference.java, ccd-definitions/src/main/java/uk/gov/hmcts/reform/divorce/ccd/model/CaseData.java, ccd-definitions/src/test/java/uk/gov/hmcts/reform/divorce/ccd/event/solicitor/page/LanguagePreferenceTest.java
- https://tools.hmcts.net/jira/browse/NFDIV-538
- This PR sets language preference as part of about to start for solicitor create event.
=> Add solicitor create about start callback

ccd-definitions/src/main/java/uk/gov/hmcts/reform/divorce/ccd/model/CaseData.java, ccd-definitions/src/main/java/uk/gov/hmcts/reform/divorce/ccd/model/enums/LegalProceedingsRelated.java
https://tools.hmcts.net/jira/browse/NFDIV-302
```
[ ] Yes
[X] No
```
=> adding field names for nfdiv-302

ccd-definitions/src/main/java/uk/gov/hmcts/reform/divorce/ccd/model/CaseData.java
changing method to recieve set of values
```
[ ] Yes
[X] No
```
=> changing legalProceedingsRelated to set

ccd-definitions/src/main/java/uk/gov/hmcts/reform/divorce/ccd/model/CaseData.java
[NFDIV-453](https://tools.hmcts.net/jira/browse/NFDIV-453) You need to get their address
Adds a serve another way field.
```
[ ] Yes
[x] No
```
=> feat(NFDIV-453): Added serve another way field

api/src/functionalTest/resources/responses/ccd-callback-solicitor-create-about-to-submit.json, ccd-definitions/src/main/java/uk/gov/hmcts/reform/divorce/ccd/model/CaseData.java
[NFDIV-438](https://tools.hmcts.net/jira/browse/NFDIV-438) Enter your husband's or wife's postal address
Adds respondent address field.
```
[ ] Yes
[x] No
```
=> feat(NFDIV-438): Added respondent address field

build.gradle, src/main/java/uk/gov/hmcts/divorce/ccd/event/solicitor/SolicitorCreate.java, src/main/java/uk/gov/hmcts/divorce/ccd/event/solicitor/page/RespondentServiceDetails.java, src/main/java/uk/gov/hmcts/divorce/ccd/model/CaseData.java
https://tools.hmcts.net/jira/browse/NFDIV-575
Add Respondent Service Details page to Solicitor Create event
=> Add respondent service details page

src/main/java/uk/gov/hmcts/divorce/ccd/event/solicitor/SolicitorCreate.java, src/main/java/uk/gov/hmcts/divorce/ccd/event/solicitor/page/MarriageCertificateDetails.java, src/main/java/uk/gov/hmcts/divorce/ccd/model/CaseData.java
https://tools.hmcts.net/jira/browse/NFDIV-576
=> Added marriage certificate details page

src/main/java/uk/gov/hmcts/divorce/ccd/event/solicitor/SolicitorCreate.java, src/main/java/uk/gov/hmcts/divorce/ccd/event/solicitor/page/FinancialOrders.java, src/main/java/uk/gov/hmcts/divorce/ccd/model/CaseData.java, src/main/java/uk/gov/hmcts/divorce/ccd/model/enums/FinancialOrderFor.java
https://tools.hmcts.net/jira/browse/NFDIV-579
Add Solicitor Create event Financial Orders page
=> Add Solicitor Financial Orders page

src/main/java/uk/gov/hmcts/divorce/ccd/event/solicitor/SolicitorCreate.java, src/main/java/uk/gov/hmcts/divorce/ccd/event/solicitor/page/ClaimForCosts.java
https://tools.hmcts.net/jira/browse/NFDIV-580
Add Solicitor Create event Claim For Costs page
=> Add solicitor claim for costs page

src/main/java/uk/gov/hmcts/divorce/ccd/model/CaseData.java
[NFDIV-557](https://tools.hmcts.net/jira/browse/NFDIV-557) Check your answers
Added `prayerHasBeenGiven` field.
```
[ ] Yes
[x] No
```
=> feat(NFDIV-557): Added prayerHasBeenGiven field

src/main/java/uk/gov/hmcts/divorce/api/ccd/model/CaseData.java, src/main/java/uk/gov/hmcts/divorce/api/ccd/model/enums/ConnectionSummary.java
adding the connection summary field
Note: i noticed in the config file this field was set to text but the frontend is a radio component meaning its preset values.
```
[ ] Yes
[X] No
```
=> adding connection summary field

Jenkinsfile_CNP, build.gradle, src/functionalTest/resources/responses/ccd-callback-set-language-preference.json, src/main/java/uk/gov/hmcts/divorce/solicitor/event/SolicitorCreate.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/SolicitorStatementOfTruthPaySubmit.java
Fix solicitor create event submission by updating ccd-config-generator to version 0.19.18
=> Update ccd-config-generator to version 0.19.18

src/main/java/uk/gov/hmcts/divorce/common/model/JurisdictionConnections.java
https://tools.hmcts.net/jira/browse/NFDIV-612
```
[ ] Yes
[X] No
```
=> adding more connections

src/main/java/uk/gov/hmcts/divorce/common/model/CaseData.java
* [NFDIV-562](https://tools.hmcts.net/jira/browse/NFDIV-562) Enter your name
* [NFDIV-563](https://tools.hmcts.net/jira/browse/NFDIV-563) Enter your husband's or wife's name
Adds fields for "Middle name(s)".
```
[ ] Yes
[x] No
```
=> feat(NFDIV-562): Added middle name fields

build.gradle, config/checkstyle/checkstyle.xml, src/main/java/uk/gov/hmcts/divorce/ccd/CcdPageConfiguration.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/SolicitorCreate.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/SolicitorStatementOfTruthPaySubmit.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/SolicitorUpdate.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/ClaimForCosts.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/FinancialOrders.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/HelpWithFees.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/LanguagePreference.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/MarriageCertificateDetails.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/OtherLegalProceedings.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/RespondentServiceDetails.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/SolAboutThePetitioner.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/SolAboutTheRespondent.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/SolAboutTheSolicitor.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/SolPayAccount.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/SolPayment.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/SolPaymentSummary.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/SolStatementOfTruth.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/SolSummary.java
Update ccd-config-generator to version 0.19.20
=> Update ccd-config-generator to version 0.19.20

src/main/java/uk/gov/hmcts/divorce/common/model/CaseData.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/SolicitorCreate.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/MarriageIrretrievablyBroken.java
Added the initial version of the Marriage Irretrievably Broken page.
```
[ ] Yes
[X] No
```
=> Add Marriage Irretrievably Broken page to Solicitor Create

build.gradle, src/main/java/uk/gov/hmcts/divorce/ccd/CcdPageConfiguration.java, src/main/java/uk/gov/hmcts/divorce/ccd/PageBuilder.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/SolicitorCreate.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/SolicitorStatementOfTruthPaySubmit.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/SolicitorUpdate.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/ClaimForCosts.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/FinancialOrders.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/HelpWithFees.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/JurisdictionApplyForDivorce.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/LanguagePreference.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/MarriageCertificateDetails.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/MarriageIrretrievablyBroken.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/OtherLegalProceedings.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/RespondentServiceDetails.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/SolAboutThePetitioner.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/SolAboutTheRespondent.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/SolAboutTheSolicitor.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/SolPayAccount.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/SolPayment.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/SolPaymentSummary.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/SolStatementOfTruth.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/SolSummary.java, src/test/java/uk/gov/hmcts/divorce/ccd/PageBuilderTest.java, src/test/java/uk/gov/hmcts/divorce/solicitor/event/SolicitorCreateTest.java, src/test/java/uk/gov/hmcts/divorce/solicitor/event/SolicitorUpdateTest.java
Add PageBuilder to simplify ccd page configuration interface
=> Add PageBuilder to simplify ccd page configuration

src/main/java/uk/gov/hmcts/divorce/common/model/CaseData.java, src/main/java/uk/gov/hmcts/divorce/common/model/SupportingDocumentType.java, src/main/java/uk/gov/hmcts/divorce/common/model/SupportingDocuments.java
[NFDIV-305](https://tools.hmcts.net/jira/browse/NFDIV-305) Upload documents
Added fields for supporting documents and cannot upload documents.
```
[ ] Yes
[x] No
```
=> feat(NFDIV-305): Added documents field

src/main/java/uk/gov/hmcts/divorce/common/model/CaseData.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/SolicitorCreate.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/SolHowDoYouWantToApplyForDivorce.java
https://tools.hmcts.net/jira/browse/NFDIV-645
Initial implementation of the How do you want to apply for divorce page
```
[ ] Yes
[X] No
```
=> Add how do you want to apply for divorce page

src/main/java/uk/gov/hmcts/divorce/ccd/tab/CaseTypeTab.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/SolicitorUpdateLanguage.java, src/test/java/uk/gov/hmcts/divorce/solicitor/event/SolicitorUpdateLanguageTest.java
https://tools.hmcts.net/jira/browse/NFDIV-593
Added the update language option
Added the associated unit test
Added the language details tab
```
[ ] Yes
[X] No
```
=> Add update language option

src/functionalTest/java/uk/gov/hmcts/divorce/citizen/SaveAndCloseTest.java, src/functionalTest/java/uk/gov/hmcts/divorce/common/ServiceAuthValidationTest.java, src/functionalTest/java/uk/gov/hmcts/divorce/solicitor/SolicitorCreateTest.java, src/functionalTest/java/uk/gov/hmcts/divorce/solicitor/SolicitorSubmitPetitionTest.java, src/functionalTest/java/uk/gov/hmcts/divorce/testutil/CaseDataUtil.java, src/functionalTest/java/uk/gov/hmcts/divorce/testutil/FunctionalTestSuite.java, src/functionalTest/resources/request/casedata/ccd-callback-casedata.json, src/functionalTest/resources/request/casedata/ccd-callback-solicitor-submit-petition-about-to-submit.json, src/functionalTest/resources/responses/ccd-callback-solicitor-submit-petition-about-to-submit.json, src/integrationTest/java/uk/gov/hmcts/divorce/solicitor/SolicitorStatementOfTruthPaySubmitTest.java, src/integrationTest/resources/wiremock/responses/about-to-submit-statement-of-truth-error.json, src/integrationTest/resources/wiremock/responses/about-to-submit-statement-of-truth.json, src/main/java/uk/gov/hmcts/divorce/common/model/CaseData.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/SolicitorStatementOfTruthPaySubmit.java, src/test/java/uk/gov/hmcts/divorce/solicitor/event/SolicitorStatementOfTruthPaySubmitTest.java, src/test/java/uk/gov/hmcts/divorce/testutil/TestDataHelper.java
https://tools.hmcts.net/jira/browse/NFDIV-643
Add about to submit callback for solicitor submit petition
Add validation of statementOfTruth and solSignStatementOfTruth, both should be set to YES to continue with submission
=> Add about to submit callback for solicitor submit petition

src/main/java/uk/gov/hmcts/divorce/common/model/CaseData.java, src/main/java/uk/gov/hmcts/divorce/common/model/DocumentType.java, src/main/java/uk/gov/hmcts/divorce/common/model/LegalConnections.java, src/main/java/uk/gov/hmcts/divorce/document/model/DivorceDocument.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/SolicitorCreate.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/JurisdictionApplyForDivorce.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/UploadMarriageCertificate.java, src/main/java/uk/gov/hmcts/divorce/solicitor/service/MiniPetitionDraft.java, src/test/java/uk/gov/hmcts/divorce/solicitor/service/MiniPetitionDraftTest.java
https://tools.hmcts.net/jira/browse/NFDIV-581
=> NFDIV-581: Upload marriage certificate

src/main/java/uk/gov/hmcts/divorce/common/model/CaseData.java, src/main/java/uk/gov/hmcts/divorce/solicitor/service/MiniPetitionDraft.java, src/test/java/uk/gov/hmcts/divorce/solicitor/service/MiniPetitionDraftTest.java
=> NFDIV-581: Use ListValue for documentsUploaded field

src/main/java/uk/gov/hmcts/divorce/solicitor/event/SolicitorUpdateContactDetails.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/SolUpdateContactDetails.java, src/test/java/uk/gov/hmcts/divorce/solicitor/event/SolicitorUpdateContactDetailsTest.java
- Added update solicitor contact details page and event.
- Added update solicitor contact details unit test.
- Made solicitor update language event available after case has been submitted.
```
[ ] Yes
[x] No
```
=> Add update solicitor contact details page and event

src/main/java/uk/gov/hmcts/divorce/common/model/CaseData.java
=> Fix field wording issue

src/main/java/uk/gov/hmcts/divorce/common/model/CaseData.java
https://tools.hmcts.net/jira/browse/NFDIV-593
Updated the wording for the language preference question
```
[ ] Yes
[x] No
```
=> Update language preference question

src/functionalTest/java/uk/gov/hmcts/divorce/solicitor/SolicitorCreateTest.java, src/functionalTest/resources/responses/ccd-callback-solicitor-create-about-to-submit.json, src/integrationTest/java/uk/gov/hmcts/divorce/solicitor/SolicitorCreateTest.java, src/integrationTest/resources/solicitor-create-about-to-submit-response.json, src/main/java/uk/gov/hmcts/divorce/common/model/CaseData.java, src/main/java/uk/gov/hmcts/divorce/common/updater/CaseDataContext.java, src/main/java/uk/gov/hmcts/divorce/document/DocAssemblyService.java, src/main/java/uk/gov/hmcts/divorce/document/content/DraftPetitionTemplateContent.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/SolicitorCreate.java, src/main/java/uk/gov/hmcts/divorce/solicitor/service/SolicitorCreatePetitionService.java, src/main/java/uk/gov/hmcts/divorce/solicitor/service/updater/MiniPetitionDraft.java, src/main/java/uk/gov/hmcts/divorce/solicitor/service/updater/SolicitorCourtDetails.java, src/test/java/uk/gov/hmcts/divorce/document/DocAssemblyServiceTest.java, src/test/java/uk/gov/hmcts/divorce/document/content/DraftPetitionTemplateContentTest.java, src/test/java/uk/gov/hmcts/divorce/solicitor/event/SolicitorCreateTest.java, src/test/java/uk/gov/hmcts/divorce/solicitor/service/SolicitorCreatePetitionServiceTest.java, src/test/java/uk/gov/hmcts/divorce/solicitor/service/updater/MiniPetitionDraftTest.java, src/test/java/uk/gov/hmcts/divorce/solicitor/service/updater/SolicitorCourtDetailsTest.java, src/test/java/uk/gov/hmcts/divorce/testutil/TestDataHelper.java
https://tools.hmcts.net/jira/browse/NFDIV-657
Remove createdDate field from CaseData
Use CCD metadata created_date where date is required
=> Nfdiv 657 remove created date field

build.gradle, src/main/java/uk/gov/hmcts/divorce/document/content/DocmosisTemplateConstants.java
=> output dates as strings, remove linking

src/functionalTest/java/uk/gov/hmcts/divorce/citizen/PaymentMadeTest.java, src/functionalTest/resources/request/casedata/ccd-callback-casedata-payment-made.json, src/functionalTest/resources/responses/ccd-callback-casedata-payment-made.json, src/main/java/uk/gov/hmcts/divorce/common/model/CaseData.java
Add a functional test to trigger the notification
=> Add functional test

src/functionalTest/resources/responses/ccd-callback-solicitor-create-about-to-submit.json, src/integrationTest/java/uk/gov/hmcts/divorce/solicitor/SolicitorStatementOfTruthPaySubmitTest.java, src/integrationTest/resources/solicitor-create-about-to-submit-response.json, src/main/java/uk/gov/hmcts/divorce/document/model/DocumentType.java, src/main/java/uk/gov/hmcts/divorce/solicitor/service/DraftPetitionRemovalService.java, src/main/java/uk/gov/hmcts/divorce/solicitor/service/updater/MiniPetitionDraft.java, src/test/java/uk/gov/hmcts/divorce/solicitor/service/DraftPetitionRemovalServiceTest.java, src/test/java/uk/gov/hmcts/divorce/solicitor/service/SolicitorSubmitPetitionServiceTest.java, src/test/java/uk/gov/hmcts/divorce/solicitor/service/updater/MiniPetitionDraftTest.java, src/test/java/uk/gov/hmcts/divorce/testutil/TestDataHelper.java
https://tools.hmcts.net/jira/browse/NFDIV-662
Update DocumentType list
Store divorce mini petition as divorceApplication DocumentType
=> Update DocumentType list

src/main/java/uk/gov/hmcts/divorce/common/model/ApplicationType.java, src/main/java/uk/gov/hmcts/divorce/common/model/CaseData.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/SolHowDoYouWantToApplyForDivorce.java
https://tools.hmcts.net/jira/browse/NFDIV-636
Added the application type field
```
[ ] Yes
[x] No
```
=> NFDIV-636 Add application type field

src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/SolAboutTheSolicitor.java
=> NFDIV-666: Remove redundant 'the'

src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/UploadMarriageCertificate.java
https://tools.hmcts.net/jira/browse/NFDIV-710
=> NFDIV-710: Change the formatting and label names on Doc Upload

src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/UploadMarriageCertificate.java
=> NFDIV-710: Resolve issues with formatting

src/main/java/uk/gov/hmcts/divorce/common/model/CaseData.java, src/main/java/uk/gov/hmcts/divorce/common/model/Jurisdiction.java
https://tools.hmcts.net/jira/browse/NFDIV-715
=> NFDIV-715: Rename field labels

src/main/java/uk/gov/hmcts/divorce/solicitor/event/SolicitorCreate.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/Applicant2ServiceDetails.java, src/main/java/uk/gov/hmcts/divorce/solicitor/service/SolicitorCreateApplicationService.java, src/test/java/uk/gov/hmcts/divorce/solicitor/event/SolicitorCreateTest.java, src/test/java/uk/gov/hmcts/divorce/solicitor/service/SolicitorCreateApplicationServiceTest.java
Reverts hmcts/nfdiv-case-api#266
=> Revert "Move service logic to handler as it is more appropriate in handler"

build.gradle, src/main/java/uk/gov/hmcts/divorce/ccd/NoFaultDivorce.java, src/main/java/uk/gov/hmcts/divorce/common/model/CaseData.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/MarriageCertificateDetails.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/SolAboutApplicant1.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/SolAboutApplicant2.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/SolAboutTheSolicitor.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/SolHowDoYouWantToApplyForDivorce.java
https://tools.hmcts.net/jira/browse/NFDIV-714
=> NFDIV-714: Add CaseEventFieldLabel and CaseEventHintText as required

build.gradle, src/main/java/uk/gov/hmcts/divorce/solicitor/event/SolicitorUpdateLanguage.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/Applicant2ServiceDetails.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/ClaimForCosts.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/CommonFieldSettings.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/FinancialOrders.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/JurisdictionApplyForDivorce.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/LanguagePreference.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/MarriageCertificateDetails.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/MarriageIrretrievablyBroken.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/OtherLegalProceedings.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/SolAboutApplicant1.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/SolAboutApplicant2.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/SolAboutTheSolicitor.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/SolHowDoYouWantToApplyForDivorce.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/UploadMarriageCertificate.java
https://tools.hmcts.net/jira/browse/NFDIV-712
Add image banner for sole and joint to all solicitor create pages
=> Set banner on solicitor create event pages

build.gradle, src/functionalTest/java/uk/gov/hmcts/divorce/solicitor/SolicitorSubmitApplicationTest.java, src/integrationTest/java/uk/gov/hmcts/divorce/solicitor/SolicitorStatementOfTruthPaySubmitTest.java, src/integrationTest/resources/wiremock/responses/about-to-submit-statement-of-truth-error.json, src/integrationTest/resources/wiremock/responses/about-to-submit-statement-of-truth-payment-error.json, src/main/java/uk/gov/hmcts/divorce/ccd/NoFaultDivorce.java, src/main/java/uk/gov/hmcts/divorce/common/model/State.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/SolicitorCreate.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/SolicitorStatementOfTruthPaySubmit.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/SolicitorUpdate.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/SolicitorUpdateLanguage.java, src/main/java/uk/gov/hmcts/divorce/solicitor/service/SolicitorSubmitApplicationService.java, src/test/java/uk/gov/hmcts/divorce/solicitor/event/SolicitorStatementOfTruthPaySubmitTest.java, src/test/java/uk/gov/hmcts/divorce/solicitor/service/SolicitorSubmitApplicationServiceTest.java
Consolidate solicitor and citizen states
=> Nfdiv 707 update states

src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/CommonFieldSettings.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/SolAboutApplicant1.java
https://tools.hmcts.net/jira/browse/NFDIV-713
Update layout of applicant 1 page solictor create event
=> Add layout changes to applicant 1 solictor create page

src/main/java/uk/gov/hmcts/divorce/ccd/tab/CaseTypeTab.java
=> NFDIV-717: Add showCondition for applicant1SolicitorRepresented

src/main/java/uk/gov/hmcts/divorce/solicitor/event/SolicitorCreateApplication.java
=> move screener question to page 3

src/main/java/uk/gov/hmcts/divorce/solicitor/event/ApplicantUpdateContactDetails.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/Applicant1UpdateContactDetails.java, src/test/java/uk/gov/hmcts/divorce/solicitor/event/ApplicantUpdateContactDetailsTest.java
https://tools.hmcts.net/jira/browse/NFDIV-718
=> Added applicant 1 update contact details event

src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/SolPayAccount.java
https://tools.hmcts.net/jira/browse/NFDIV-746
=> NFDIV-746: Make Account Number Optional

src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerAwaitingDocuments.java, src/main/java/uk/gov/hmcts/divorce/common/model/CaseData.java, src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerAwaitingDocumentsTest.java
https://tools.hmcts.net/jira/browse/NFDIV-731
Add caseworker-awaiting-documents event to transition state from Submitted to AwaitingDocuments
Enables testing for NFDIV-731
=> Add awaitingDocuments caseworker event

src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/SolStatementOfTruth.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/SolSummary.java
https://tools.hmcts.net/jira/browse/NFDIV-609
=> RDM-609: Alter label fields on sol summary and sol statement of truth

src/functionalTest/resources/request/casedata/ccd-callback-casedata-applicant1-statement-of-truth.json, src/functionalTest/resources/request/casedata/ccd-callback-casedata-payment-made-awaiting-documents.json, src/functionalTest/resources/request/casedata/ccd-callback-casedata-payment-made.json, src/functionalTest/resources/responses/response-applicant1-statement-of-truth.json, src/functionalTest/resources/responses/response-payment-made-awaiting-documents.json, src/functionalTest/resources/responses/response-payment-made.json, src/main/java/uk/gov/hmcts/divorce/common/model/Jurisdiction.java, src/main/java/uk/gov/hmcts/divorce/common/model/JurisdictionConnections.java, src/test/java/uk/gov/hmcts/divorce/common/model/JurisdictionTest.java, src/test/java/uk/gov/hmcts/divorce/testutil/TestDataHelper.java
https://tools.hmcts.net/jira/browse/NFDIV-695
Add a new jurisdiction connection for joint applications
```
[ ] Yes
[x] No
```
=> NFDIV-695 Add jurisdiction connection

src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/SolStatementOfTruth.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/SolSummary.java
https://tools.hmcts.net/jira/browse/NFDIV-609
=> NFDIV 609: Resolve formatting issues

src/integrationTest/java/uk/gov/hmcts/divorce/caseworker/event/ValidateHwfReferenceTest.java, src/integrationTest/java/uk/gov/hmcts/divorce/citizen/event/CitizenAddPaymentTest.java, src/integrationTest/java/uk/gov/hmcts/divorce/solicitor/SolicitorSubmitApplicationTest.java, src/integrationTest/resources/caseworker/validate-hwf-code-awaiting-docs.json, src/integrationTest/resources/caseworker/validate-hwf-code-awaiting-pay-response.json, src/integrationTest/resources/caseworker/validate-hwf-code-error.json, src/integrationTest/resources/caseworker/validate-hwf-code-submitted-response.json, src/main/java/uk/gov/hmcts/divorce/caseworker/event/ValidateHwfReference.java, src/main/java/uk/gov/hmcts/divorce/common/model/CaseData.java, src/main/java/uk/gov/hmcts/divorce/common/model/State.java, src/main/java/uk/gov/hmcts/divorce/solicitor/service/SolicitorSubmitApplicationService.java, src/test/java/uk/gov/hmcts/divorce/solicitor/service/SolicitorSubmitApplicationServiceTest.java, src/test/java/uk/gov/hmcts/divorce/testutil/TestConstants.java, src/test/java/uk/gov/hmcts/divorce/testutil/TestDataHelper.java
https://tools.hmcts.net/jira/browse/NFDIV-588
- Added validate HWF code event with page controls.
- Added about to submit to set state as per the condition.
- Includes fix for integration tests which was failing due to Jackson not supporting Java 8 date/time type by default.
- Added integration tests
- Tested on local docker
```
[ ] Yes
[x ] No
```
=> Added validate hwf code event with about to submit callback

src/integrationTest/java/uk/gov/hmcts/divorce/caseworker/CaseworkerUploadDocumentsAndSubmitTest.java, src/integrationTest/java/uk/gov/hmcts/divorce/solicitor/SolicitorSubmitApplicationTest.java, src/integrationTest/resources/caseworker-document-upload-about-to-start-response.json, src/integrationTest/resources/caseworker-document-upload-about-to-submit-response.json, src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerAwaitingDocuments.java, src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerUploadDocumentsAndSubmit.java, src/main/java/uk/gov/hmcts/divorce/common/model/CaseData.java, src/main/java/uk/gov/hmcts/divorce/common/model/access/CaseworkerAccess.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/SolicitorCreateApplication.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/SolicitorUpdateApplication.java, src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerUploadDocumentsAndSubmitTest.java, src/test/java/uk/gov/hmcts/divorce/testutil/TestDataHelper.java
https://tools.hmcts.net/jira/browse/NFDIV-731
https://tools.hmcts.net/jira/browse/NFDIV-591
Add caseworker-upload-documents-and-submit event to allow caseworker to upload documents and submit case
=> Nfdiv 731 caseworker attach documents and submit

src/main/java/uk/gov/hmcts/divorce/ccd/NoFaultDivorce.java, src/main/java/uk/gov/hmcts/divorce/common/model/Jurisdiction.java, src/main/java/uk/gov/hmcts/divorce/common/model/JurisdictionConnections.java, src/test/java/uk/gov/hmcts/divorce/common/model/JurisdictionTest.java
https://tools.hmcts.net/jira/browse/NFDIV-695
Renamed the joint jurisdiction connection for clarity
```
[ ] Yes
[x] No
```
=> NFDIV-695 Rename joint jurisdiction connection

src/main/java/uk/gov/hmcts/divorce/document/content/DraftApplicationTemplateContent.java
https://tools.hmcts.net/jira/browse/NFDIV-742
Fix draft application pdf missing mariage date
=> Fix draft pdf marriage date missing

build.gradle, src/main/java/uk/gov/hmcts/divorce/solicitor/event/SolicitorCreateApplication.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/SolicitorUpdateApplication.java
Fix caseworker field authorisation and remove work around.
=> Fix caseworker field authorisation

src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/HelpWithFees.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/SolPayAccount.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/SolPayment.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/SolPaymentSummary.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/SolStatementOfTruth.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/SolSummary.java
https://tools.hmcts.net/jira/browse/NFDIV-748
Add NFD banner to solicitor submit event pages
=> Add NFD banner to solicitor submit pages

src/functionalTest/resources/responses/response-solicitor-create-mid-event.json, src/integrationTest/resources/solicitor-mid-event-error-response.json, src/integrationTest/resources/solicitor-mid-event-response.json, src/main/java/uk/gov/hmcts/divorce/solicitor/event/SolicitorUpdateApplication.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/MarriageIrretrievablyBroken.java, src/main/java/uk/gov/hmcts/divorce/solicitor/service/SolicitorCreateApplicationService.java, src/test/java/uk/gov/hmcts/divorce/solicitor/service/SolicitorCreateApplicationApplicationServiceTest.java
Fix fields being blanked after mid event callback.  If revisiting pages after setting all case data, the mid event callback was blanking some field data that was part of JsonUnwrapped Classes
=> Fix blanking of fields after mid event callback

src/functionalTest/java/uk/gov/hmcts/divorce/citizen/CitizenSubmitApplicationTest.java, src/functionalTest/resources/request/casedata/ccd-callback-casedata-applicant1-statement-of-truth.json, src/functionalTest/resources/responses/response-applicant1-help-with-fees.json, src/functionalTest/resources/responses/response-applicant1-statement-of-truth.json, src/integrationTest/java/uk/gov/hmcts/divorce/citizen/event/CitizenSubmitApplicationTest.java, src/integrationTest/resources/wiremock/responses/applicant-1-about-to-start-help-with-fees.json, src/integrationTest/resources/wiremock/responses/applicant-1-about-to-start-statement-of-truth.json, src/main/java/uk/gov/hmcts/divorce/citizen/event/CitizenSubmitApplication.java, src/test/java/uk/gov/hmcts/divorce/citizen/event/CitizenSubmitApplicationTest.java, src/test/java/uk/gov/hmcts/divorce/testutil/TestDataHelper.java
[NFDIV-680](https://tools.hmcts.net/jira/browse/NFDIV-680) Payment - State Changes
Fixes a null pointer exception when HWF is not set.
```
[ ] Yes
[x] No
```
=> fix: null pointer when HWF not entered

src/functionalTest/resources/responses/response-applicant1-help-with-fees.json, src/functionalTest/resources/responses/response-applicant1-statement-of-truth.json, src/functionalTest/resources/responses/response-payment-made-awaiting-documents.json, src/functionalTest/resources/responses/response-payment-made.json, src/functionalTest/resources/responses/response-solicitor-create-about-to-submit.json, src/functionalTest/resources/responses/response-solicitor-submit-application-about-to-submit.json, src/functionalTest/resources/responses/response-solicitor-submit-application.json, src/functionalTest/resources/responses/response-solicitor-update-about-to-submit.json, src/integrationTest/resources/solicitor-create-about-to-submit-response.json, src/integrationTest/resources/solicitor-mid-event-response.json, src/integrationTest/resources/solicitor-update-about-to-submit-response.json, src/integrationTest/resources/wiremock/responses/about-to-submit-invite-applicant-2.json, src/integrationTest/resources/wiremock/responses/applicant-1-about-to-start-help-with-fees.json, src/integrationTest/resources/wiremock/responses/applicant-1-about-to-start-statement-of-truth.json, src/main/java/uk/gov/hmcts/divorce/ccd/tab/CaseTypeTab.java, src/main/java/uk/gov/hmcts/divorce/common/model/CaseData.java, src/main/java/uk/gov/hmcts/divorce/common/model/MarriageDetails.java, src/main/java/uk/gov/hmcts/divorce/common/model/State.java, src/main/java/uk/gov/hmcts/divorce/common/validation/ValidationUtil.java, src/main/java/uk/gov/hmcts/divorce/document/content/DraftApplicationTemplateContent.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/IssueApplication.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/VerifyMarriageCertificate.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/MarriageCertificateDetails.java, src/main/java/uk/gov/hmcts/divorce/solicitor/service/CcdAccessService.java, src/test/java/uk/gov/hmcts/divorce/citizen/event/CitizenSubmitApplicationTest.java, src/test/java/uk/gov/hmcts/divorce/testutil/TestDataHelper.java
https://tools.hmcts.net/jira/browse/NFDIV-611
- Move marriageApplicant1 and marriageApplicant2 to Marriage details model class.
- Introduce event to issue petition as described in the ticket.
- Doesn't include generation of documents for issue event.
```
[ ] Yes
[x ] No
```
=> Added Issue Application event to move case to Issued

src/main/java/uk/gov/hmcts/divorce/document/content/DraftApplicationTemplateContent.java, src/test/java/uk/gov/hmcts/divorce/document/content/DraftApplicationTemplateContentTest.java
https://tools.hmcts.net/jira/browse/NFDIV-767
Update draft application pdf date formatting to 'd MMMM yyyy'
=> Update draft application pdf with correct date format

src/main/java/uk/gov/hmcts/divorce/ccd/NoFaultDivorce.java, src/main/java/uk/gov/hmcts/divorce/common/model/State.java
For the frontend submission page, there is a progression bar which informs the state of the case however, some of the state hasnt been implemented yet, just adding the state for FE check.
```
[ ] Yes
[X] No
```
=> updating state

src/main/java/uk/gov/hmcts/divorce/solicitor/event/SolicitorCreateApplication.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/ClaimForCosts.java
https://tools.hmcts.net/jira/browse/NFDIV-603
https://tools.hmcts.net/jira/browse/NFDIV-629
=> Added divorceClaimFrom field and moved jurisdiction to appear on page 8

src/functionalTest/java/uk/gov/hmcts/divorce/citizen/CitizenAddPaymentTest.java, src/functionalTest/resources/request/casedata/ccd-callback-casedata-payment-cancelled.json, src/functionalTest/resources/request/casedata/ccd-callback-casedata-payment-in-progress.json, src/functionalTest/resources/responses/response-payment-cancelled.json, src/functionalTest/resources/responses/response-payment-in-progress.json, src/integrationTest/java/uk/gov/hmcts/divorce/citizen/event/CitizenAddPaymentTest.java
[NFDIV-680](https://tools.hmcts.net/jira/browse/NFDIV-680) Payment - State Changes
Added functional & integration tests for add payment in progress & cancelled.
```
[ ] Yes
[x] No
```
=> feat(NFDIV-680): Added functional & integration tests for add payment

src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/JurisdictionApplyForDivorce.java
Minor fix to wording on Jurisdiction page - replace apple with apply
=> Fix wording fault on jurisdiction page

src/main/java/uk/gov/hmcts/divorce/ccd/workbasket/WorkBasketInputFields.java, src/main/java/uk/gov/hmcts/divorce/ccd/workbasket/WorkBasketResultFields.java, src/test/java/uk/gov/hmcts/divorce/ccd/workbasket/WorkBasketInputFieldsTest.java, src/test/java/uk/gov/hmcts/divorce/ccd/workbasket/WorkBasketResultFieldsTest.java
https://tools.hmcts.net/jira/browse/NFDIV-709
Tidy the workbasket heading so that they line up over two lines
=> Tidy workbasket headings

src/main/java/uk/gov/hmcts/divorce/common/model/LegalConnections.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/JurisdictionApplyForDivorce.java
https://tools.hmcts.net/jira/browse/NFDIV-681
```
[ ] Yes
[x ] No
```
=> Rearranged legal connections and removed residual jurisdiction text

src/main/java/uk/gov/hmcts/divorce/common/model/CaseData.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/MarriageIrretrievablyBroken.java, src/test/java/uk/gov/hmcts/divorce/solicitor/event/page/MarriageIrretrievablyBrokenTest.java
[NFDIV-752](https://tools.hmcts.net/jira/browse/NFDIV-752) Has your marriage irretrievably broken down - Joint App 2
Adds additional optional field for has applicant 2 relationship broken.
```
[ ] Yes
[x] No
```
=> feat(NFDIV-752): Applicant 2 has relationship broken

charts/nfdiv-case-api/Chart.yaml, charts/nfdiv-case-api/values.preview.template.yaml, charts/nfdiv-case-api/values.yaml
=> Add XUI to chart

src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerIssueApplication.java, src/main/java/uk/gov/hmcts/divorce/caseworker/service/IssueApplicationService.java, src/main/java/uk/gov/hmcts/divorce/common/model/CaseData.java, src/main/java/uk/gov/hmcts/divorce/common/model/access/CaseworkerAccess.java, src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerIssueApplicationTest.java, src/test/java/uk/gov/hmcts/divorce/caseworker/service/CaseworkerIssueApplicationServiceTest.java
https://tools.hmcts.net/jira/browse/NFDIV-813
- Validates case data when issuing application.
- Sets Issue date 
```
[ ] Yes
[ x] No
```
=> Added validation for issue application and issue date

src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerIssueAos.java, src/main/java/uk/gov/hmcts/divorce/common/model/State.java, src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerIssueAosTest.java
https://tools.hmcts.net/jira/browse/NFDIV-808
Add caseworker issue AOS event
Add IssuedAos state
=> Add issue AOS event and IssuedAos state

src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerIssueAos.java, src/main/java/uk/gov/hmcts/divorce/common/model/State.java
Issue AOS is the event name not the state name
=> Rename IssueAOS -> AwaitingAos

src/main/java/uk/gov/hmcts/divorce/common/model/State.java
Add states up to the bulk scheduling
=> add states

src/main/java/uk/gov/hmcts/divorce/common/model/Applicant.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/Applicant2SolConfirmContactDetails.java
NFDIV-953
Changes to title and cost pages
=> NFDIV-953:Changes to title and cost pages

src/main/java/uk/gov/hmcts/divorce/solicitor/event/SolicitorSubmitDraftAos.java
NFDIV-953
Added summary and updated submit button label
```
[ ] Yes
[x ] No
```
=> NFDIV-953:Added summary and updated submit button label

src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerAddNote.java, src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerAddNoteTest.java
=> Add new notes to the top of the  list and update list value ids

src/main/java/uk/gov/hmcts/divorce/common/model/FinancialOrderFor.java
https://tools.hmcts.net/jira/browse/NFDIV-788
```
[ ] Yes
[X] No
```
=> add second applicant to FinancialOrderFor enum

build.gradle, src/functionalTest/resources/application.yaml, src/integrationTest/resources/application.yaml, src/main/java/uk/gov/hmcts/divorce/CaseApiApplication.java, src/main/java/uk/gov/hmcts/divorce/caseworker/schedule/CaseworkerIssueAosTask.java, src/main/java/uk/gov/hmcts/divorce/caseworker/service/CcdCaseDataContentProvider.java, src/main/java/uk/gov/hmcts/divorce/caseworker/service/CcdConflictException.java, src/main/java/uk/gov/hmcts/divorce/caseworker/service/CcdManagementException.java, src/main/java/uk/gov/hmcts/divorce/caseworker/service/CcdSearchCaseException.java, src/main/java/uk/gov/hmcts/divorce/caseworker/service/CcdSearchService.java, src/main/java/uk/gov/hmcts/divorce/caseworker/service/CcdUpdateService.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/divorce/caseworker/schedule/CaseworkerIssueAosTaskTest.java, src/test/java/uk/gov/hmcts/divorce/caseworker/service/CcdCaseDataContentProviderTest.java, src/test/java/uk/gov/hmcts/divorce/caseworker/service/CcdSearchServiceTest.java, src/test/java/uk/gov/hmcts/divorce/caseworker/service/CcdUpdateServiceTest.java
https://tools.hmcts.net/jira/browse/NFDIV-808
Add scheduled task that submits issued cases for the issue AOS event
=> Add scheduled task to submit issued cases for issue aos event

src/functionalTest/resources/request/casedata/ccd-callback-casedata-applicant1-invite-applicant2.json, src/functionalTest/resources/responses/response-applicant1-invite-applicant2.json, src/integrationTest/java/uk/gov/hmcts/divorce/citizen/event/CitizenLinkApplicant2Test.java, src/integrationTest/resources/wiremock/responses/about-to-submit-invite-applicant-2.json, src/integrationTest/resources/wiremock/responses/applicant-1-about-to-start-help-with-fees.json, src/integrationTest/resources/wiremock/responses/applicant-1-about-to-start-statement-of-truth.json, src/main/java/uk/gov/hmcts/divorce/citizen/event/CitizenLinkApplicant2.java, src/main/java/uk/gov/hmcts/divorce/citizen/notification/ApplicationSentForReviewApplicant2Notification.java, src/main/java/uk/gov/hmcts/divorce/common/model/CaseData.java, src/main/java/uk/gov/hmcts/divorce/solicitor/service/CcdAccessService.java, src/test/java/uk/gov/hmcts/divorce/citizen/event/CitizenLinkApplicant2Test.java, src/test/java/uk/gov/hmcts/divorce/testutil/TestDataHelper.java
https://tools.hmcts.net/jira/browse/NFDIV-966
=> NFDIV-966: Rename invite email address and respondent user id fields

src/main/java/uk/gov/hmcts/divorce/citizen/event/CitizenApplicant2UpdateApplication.java, src/test/java/uk/gov/hmcts/divorce/citizen/event/CitizenApplicant2UpdateApplicationTest.java
https://tools.hmcts.net/jira/browse/NFDIV-976
=> NFDIV-976: Create event for Applicant 2 update case

Jenkinsfile_CNP
- Perftest doesn't has test stage hence definitions needs to be generated after checkout which will be now for all the environments.
=> Fix perftest and sync with master

src/main/java/uk/gov/hmcts/divorce/solicitor/event/SolicitorUpdateApplicant1ContactDetails.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/UpdateApplicant1ContactDetails.java, src/test/java/uk/gov/hmcts/divorce/solicitor/event/SolicitorUpdateApplicant1ContactDetailsTest.java
Somesh is working on a CaseworkerUpdateContactDetails so I thought I should give this one a clearer name
=> Rename solicitor update contact details

src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerUpdateApplicationType.java, src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerUpdateApplicationTypeTest.java
https://tools.hmcts.net/jira/browse/NFDIV-969
=> Added event to update application type for caseworkers

src/main/java/uk/gov/hmcts/divorce/citizen/notification/ApplicationSubmittedNotification.java
https://tools.hmcts.net/jira/browse/NFDIV-964
=> NFDIV-964: Set dueDate with dateSubmitted+14 days

Jenkinsfile_CNP, src/functionalTest/resources/application.yaml, src/integrationTest/java/uk/gov/hmcts/divorce/solicitor/SolicitorSubmitApplicationTest.java, src/integrationTest/java/uk/gov/hmcts/divorce/testutil/CaseDataWireMock.java, src/integrationTest/java/uk/gov/hmcts/divorce/testutil/IdamWireMock.java, src/integrationTest/resources/application.yaml, src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerAwaitingConditionalOrder.java, src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerIssueAos.java, src/main/java/uk/gov/hmcts/divorce/caseworker/service/CcdSearchService.java, src/main/java/uk/gov/hmcts/divorce/caseworker/service/CcdUpdateService.java, src/main/java/uk/gov/hmcts/divorce/idam/IdamService.java, src/main/java/uk/gov/hmcts/divorce/solicitor/service/CcdAccessService.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/divorce/caseworker/service/CcdSearchServiceTest.java, src/test/java/uk/gov/hmcts/divorce/caseworker/service/CcdUpdateServiceTest.java, src/test/java/uk/gov/hmcts/divorce/idam/IdamServiceTest.java, src/test/java/uk/gov/hmcts/divorce/solicitor/service/CcdAccessServiceTest.java, src/test/java/uk/gov/hmcts/divorce/testutil/TestConstants.java
- Replace caseworker user with system update user for triggering background events and adding solicitor roles.
```
[ ] Yes
[x ] No
```
=> Use system update user

src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerAmendCase.java, src/main/java/uk/gov/hmcts/divorce/caseworker/event/page/AmendCase.java, src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerAmendCaseTest.java
NFDIV-843
Event to enable Amed case
```
[ ] Yes
[ x] No
```
=> NFDIV-843: Event to enable Amed case

src/functionalTest/java/uk/gov/hmcts/divorce/caseworker/CaseworkerIssueAosTest.java, src/integrationTest/java/uk/gov/hmcts/divorce/caseworker/IssueAosTest.java, src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerIssueAos.java, src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerIssueAosTest.java
https://tools.hmcts.net/jira/browse/NFDIV-808
Remove submitted callback and add email notification logic into about to submit for issue aos event
=> Combine issue aos event callbacks into about to submit

src/main/java/uk/gov/hmcts/divorce/caseworker/schedule/CaseworkerAwaitingConditionalOrderTask.java, src/test/java/uk/gov/hmcts/divorce/caseworker/schedule/CaseworkerAwaitingConditionalOrderTaskTest.java
NFDIV-983
Ignoring case with null issue date
```
[ ] Yes
[x] No
```
=> NFDIV-983: Ignoring case with null issue date

src/main/java/uk/gov/hmcts/divorce/systemupdate/schedule/SystemProgressHeldCasesTask.java
NFDIV-983
Added logs to debug the issue
```
[ ] Yes
[x ] No
```
=> NFDIV-983: Added logs to debug the issue

src/main/java/uk/gov/hmcts/divorce/systemupdate/schedule/SystemProgressHeldCasesTask.java
NFDIV-983
Retrieving issue date from the case details map
```
[ ] Yes
[ x] No
```
=> NFDIV-983: Retrieving issue date from the case details map

src/main/java/uk/gov/hmcts/divorce/systemupdate/schedule/SystemProgressHeldCasesTask.java
NFDIV-983
Logging issue date from CaseDetails map
```
[ ] Yes
[x ] No
```
=> NFDIV-983: Logging issue date from CaseDetails map

src/main/java/uk/gov/hmcts/divorce/divorcecase/model/access/CaseworkerAccess.java, src/main/java/uk/gov/hmcts/divorce/systemupdate/schedule/SystemProgressHeldCasesTask.java
NFDIV-983
Adding caseworker system update role to CaseworkerAccess.
```
[ ] Yes
[x ] No
```
=> NFDIV-983: Adding caseworker system update role to CaseworkerAccess.

src/main/java/uk/gov/hmcts/divorce/caseworker/service/IssueApplicationService.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/Application.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/CaseData.java, src/test/java/uk/gov/hmcts/divorce/caseworker/service/CaseworkerIssueApplicationServiceTest.java
NFDIV-983
Moving issueDate from CaseData to Application
```
[ ] Yes
[X ] No
```
=> NFDIV-983: Moving issueDate from CaseData to Application

src/main/java/uk/gov/hmcts/divorce/divorcecase/tab/CaseTypeTab.java
NFDIV-595
Added respondent section
```
[ ] Yes
[x ] No
```
=> NFDIV-595: Added respondent section

src/main/java/uk/gov/hmcts/divorce/divorcecase/model/State.java, src/test/java/uk/gov/hmcts/divorce/divorcecase/model/StateTest.java
https://tools.hmcts.net/jira/browse/NFDIV-939
Add alphabetical sort order to State enumeration, so that they are displayed in order on the Case List filter
=> Set state display order by reordering State enumeration

src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerAmendCase.java, src/main/java/uk/gov/hmcts/divorce/caseworker/event/page/AmendCase.java
NFDIV-843
Added joint application fields
```
[ ] Yes
[ x] No
```
=> NFDIV-843: Added joint application fields

build.gradle, src/main/java/uk/gov/hmcts/divorce/caseworker/event/page/AmendCase.java
NFDIV-843
Used new optionalWithoutDefaultValue method
```
[ ] Yes
[x ] No
```
=> NFDIV-843: Used new optionalWithoutDefaultValue method

src/main/java/uk/gov/hmcts/divorce/divorcecase/model/Applicant.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/tab/CaseTypeTab.java
NFDIV-595
Fixing respondent solicitor represent label.
```
[ ] Yes
[x ] No
```
=> NFDIV-595: Fixing respondent solicitor represent label.

charts/nfdiv-case-api/Chart.yaml, charts/nfdiv-case-api/values.preview.template.yaml
Fix for https://github.com/hmcts/ccd-data-store-api/commit/7aaea598ec77a756df825631d157ab41080b32b1
=> Fix for change in idam env vars

src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerUploadConfidentialDocument.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/CaseData.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/access/CaseworkerCourtAdminAccess.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/tab/CaseTypeTab.java, src/main/java/uk/gov/hmcts/divorce/document/model/ConfidentialDivorceDocument.java, src/main/java/uk/gov/hmcts/divorce/document/model/ConfidentialDocumentsReceived.java, src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerUploadConfidentialDocumentTest.java
https://tools.hmcts.net/jira/browse/NFDIV-923
- Added event and model classes for upload confidential documents.
- Added case tab config for confidential documents
```
[ ] Yes
[ x] No
```
=> Added upload confidential documents event

src/main/java/uk/gov/hmcts/divorce/divorcecase/NoFaultDivorce.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/Applicant.java
https://tools.hmcts.net/jira/browse/NFDIV-753
Update the changeNameHow field so that it can be used as checkboxes on the FE
```
[ ] Yes
[x] No
```
=> Update to changeNameHow field

src/integrationTest/java/uk/gov/hmcts/divorce/caseworker/CaseworkerIssueApplicationTest.java, src/integrationTest/resources/application.yaml, src/integrationTest/resources/caseworker-issue-application-about-to-submit-app2-not-sol-rep-response.json, src/integrationTest/resources/caseworker-issue-application-about-to-submit-app2-sol-rep-response.json, src/main/java/uk/gov/hmcts/divorce/caseworker/service/IssueApplicationService.java, src/main/java/uk/gov/hmcts/divorce/caseworker/service/task/GenerateCitizenRespondentAosInvitation.java, src/main/java/uk/gov/hmcts/divorce/document/CaseDataDocumentService.java, src/main/java/uk/gov/hmcts/divorce/document/DocumentConstants.java, src/main/java/uk/gov/hmcts/divorce/document/content/CitizenRespondentAosInvitationTemplateContent.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/divorce/caseworker/service/CaseworkerIssueApplicationServiceTest.java, src/test/java/uk/gov/hmcts/divorce/caseworker/service/task/GenerateCitizenRespondentAosInvitationTest.java, src/test/java/uk/gov/hmcts/divorce/caseworker/service/task/GenerateMiniApplicationTest.java, src/test/java/uk/gov/hmcts/divorce/document/CaseDataDocumentServiceTest.java, src/test/java/uk/gov/hmcts/divorce/document/content/CitizenRespondentAosInvitationTemplateContentTest.java, src/test/java/uk/gov/hmcts/divorce/solicitor/service/task/MiniApplicationDraftTest.java
https://tools.hmcts.net/jira/browse/NFDIV-815
Generate citizen respondent AoS invitation PDF and add to generated documents, if respondent is not represented
=> Generate citizen respondent aos invitation

src/main/java/uk/gov/hmcts/divorce/caseworker/service/print/AosPackPrinter.java, src/main/java/uk/gov/hmcts/divorce/caseworker/service/task/SendAosPack.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/AcknowledgementOfService.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/State.java, src/main/java/uk/gov/hmcts/divorce/document/model/DocumentType.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/SolicitorUpdateAos.java, src/main/java/uk/gov/hmcts/divorce/systemupdate/event/SystemProgressCaseToAosOverdue.java
NFDIV-867
AOS should be AoS
```
[ ] Yes
[ x] No
```
=> NFDIV-867: AOS should be AoS

src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerUploadDocument.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/CaseData.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/access/CaseworkerCourtAdminWithSolicitorAccess.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/tab/CaseTypeTab.java, src/main/java/uk/gov/hmcts/divorce/document/model/CaseworkerUploadedDocument.java, src/main/java/uk/gov/hmcts/divorce/document/model/CaseworkerUploadedDocumentType.java, src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerUploadDocumentTest.java
https://tools.hmcts.net/jira/browse/NFDIV-945
=> Added caseworker upload document event

src/functionalTest/resources/request/casedata/ccd-callback-general-order-about-to-submit.json, src/functionalTest/resources/request/casedata/ccd-callback-general-order.json, src/functionalTest/resources/responses/response-caseworker-general-order-mid-event.json, src/integrationTest/java/uk/gov/hmcts/divorce/caseworker/CaseworkerCreateGeneralOrderTest.java, src/integrationTest/resources/caseworker-general-order-response.json, src/main/java/uk/gov/hmcts/divorce/caseworker/event/page/CreateGeneralOrder.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/GeneralOrder.java, src/test/java/uk/gov/hmcts/divorce/testutil/TestDataHelper.java
NFDIV-867
To general order add field - Name of Legal Advisor
```
[ ] Yes
[ x] No
```
=> NFDIV-867: To general order add field - Name of Legal Advisor

src/main/java/uk/gov/hmcts/divorce/divorcecase/model/FinancialOrderFor.java
https://tools.hmcts.net/jira/browse/NFDIV-854
=> Updated financial order for to be aligned with divorce 1]

src/main/java/uk/gov/hmcts/divorce/citizen/notification/Applicant2ApprovedNotification.java, src/test/java/uk/gov/hmcts/divorce/citizen/notification/Applicant2ApprovedNotificationTest.java
fix applicant2 email notification date format
```
[ ] Yes
[x] No
```
=> fix applicant2 email notification date format

src/functionalTest/java/uk/gov/hmcts/divorce/solicitor/SolicitorSubmitAosTest.java, src/functionalTest/resources/request/casedata/ccd-callback-casedata-solicitor-submit-aos.json, src/integrationTest/java/uk/gov/hmcts/divorce/solicitor/SolicitorSubmitAosTest.java, src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerAmendCase.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/AcknowledgementOfService.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/State.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/SolicitorSubmitAos.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/Applicant2SolStatementOfTruth.java, src/test/java/uk/gov/hmcts/divorce/solicitor/event/SolicitorSubmitAosTest.java
https://tools.hmcts.net/jira/browse/NFDIV-906
Add about to submit callback for solicitor submit AoS - validate AoS, check if disputed
=> Add about to submit callback for solicitor submit AoS

src/integrationTest/java/uk/gov/hmcts/divorce/citizen/event/CitizenSubmitApplicationTest.java, src/main/java/uk/gov/hmcts/divorce/citizen/event/CitizenSubmitApplication.java, src/test/java/uk/gov/hmcts/divorce/citizen/event/CitizenSubmitApplicationTest.java
https://tools.hmcts.net/jira/browse/NFDIV-986
=> NFDIV-986 Add notification for HWF

charts/nfdiv-case-api/Chart.yaml, charts/nfdiv-case-api/values.yaml
=> Add application overdue scheduled cron to values.yaml

src/functionalTest/java/uk/gov/hmcts/divorce/solicitor/SolicitorSubmitUpdateDraftAosTest.java, src/functionalTest/resources/request/casedata/ccd-callback-casedata-solicitor-submit-aos.json, src/integrationTest/java/uk/gov/hmcts/divorce/solicitor/SolicitorSubmitAosTest.java, src/integrationTest/java/uk/gov/hmcts/divorce/solicitor/SolicitorSubmitUpdateDraftAosTest.java, src/main/java/uk/gov/hmcts/divorce/common/service/HoldingPeriodService.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/SolicitorDraftAos.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/SolicitorSubmitAos.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/SolicitorUpdateAos.java, src/main/java/uk/gov/hmcts/divorce/solicitor/service/SolicitorSubmitAosService.java, src/main/java/uk/gov/hmcts/divorce/solicitor/service/task/AddMiniApplicationLink.java, src/main/java/uk/gov/hmcts/divorce/solicitor/service/task/SetSubmissionAndDueDate.java, src/main/java/uk/gov/hmcts/divorce/solicitor/service/task/SetSubmitAosState.java, src/main/java/uk/gov/hmcts/divorce/systemupdate/schedule/SystemProgressHeldCasesTask.java, src/test/java/uk/gov/hmcts/divorce/common/service/HoldingPeriodServiceTest.java, src/test/java/uk/gov/hmcts/divorce/solicitor/event/SolicitorDraftAosTest.java, src/test/java/uk/gov/hmcts/divorce/solicitor/event/SolicitorSubmitAosTest.java, src/test/java/uk/gov/hmcts/divorce/solicitor/event/SolicitorUpdateAosTest.java, src/test/java/uk/gov/hmcts/divorce/solicitor/service/SolicitorSubmitAosServiceTest.java, src/test/java/uk/gov/hmcts/divorce/solicitor/service/task/AddMiniApplicationLinkTest.java, src/test/java/uk/gov/hmcts/divorce/solicitor/service/task/SetSubmissionAndDueDateTest.java, src/test/java/uk/gov/hmcts/divorce/solicitor/service/task/SetSubmitAosStateTest.java, src/test/java/uk/gov/hmcts/divorce/systemupdate/schedule/SystemProgressHeldCasesTaskTest.java, src/test/java/uk/gov/hmcts/divorce/testutil/ClockTestUtil.java
Set dateAosSubmitted case field on solicitor-submit-aos event about to submit
Add unit tests
=> Move set aos submit date to submit aos event

src/integrationTest/java/uk/gov/hmcts/divorce/citizen/event/CitizenSaveAndCloseTest.java, src/main/java/uk/gov/hmcts/divorce/citizen/event/CitizenSaveAndClose.java, src/main/java/uk/gov/hmcts/divorce/citizen/notification/SaveAndSignOutNotificationHandler.java, src/test/java/uk/gov/hmcts/divorce/citizen/event/CitizenSaveAndCloseTest.java, src/test/java/uk/gov/hmcts/divorce/citizen/notification/SaveAndSignOutNotificationHandlerTest.java
https://tools.hmcts.net/jira/browse/NFDIV-772
=> NFDIV-772 Send correct applicant save and close notification

src/integrationTest/resources/application.yaml, src/main/java/uk/gov/hmcts/divorce/citizen/notification/Applicant1ResubmitNotification.java, src/test/java/uk/gov/hmcts/divorce/citizen/notification/Applicant1ResubmitNotificationTest.java
https://tools.hmcts.net/jira/browse/NFDIV-990
adding correct url to the partners answers.
```
[ ] Yes
[X] No
```
=> pointing to the correct endpoint

src/main/java/uk/gov/hmcts/divorce/citizen/event/CitizenSwitchedToSole.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/State.java, src/test/java/uk/gov/hmcts/divorce/citizen/event/CitizenSwitchedToSoleTest.java
Remove SwitchedToSole state 
```
[ ] Yes
[x] No
```
=> Remove SwitchedToSole state

src/main/java/uk/gov/hmcts/divorce/divorcecase/model/Applicant.java
https://tools.hmcts.net/jira/browse/NFDIV-1066
=> NFDIV-1066: Add PCQ ID for both applicants

src/main/java/uk/gov/hmcts/divorce/divorcecase/search/SearchCasesResultFields.java
https://tools.hmcts.net/jira/browse/NFDIV-1060
Change case reference label to "Case Number"
=> Chnage case reference label to case number

src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/Applicant2SolConfirmContactDetails.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/Applicant2SolUpdateAosApplicant1Application.java
https://tools.hmcts.net/jira/browse/NFDIV-1108
Fix blank dynamic labels in draft aos pages
=> Fix blank dynamic labels in draft oas

build.gradle, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/Applicant.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/Application.java, src/main/java/uk/gov/hmcts/divorce/systemupdate/schedule/SystemAlertApplicationNotReviewedTask.java, src/main/java/uk/gov/hmcts/divorce/systemupdate/schedule/SystemRemindApplicant1ApplicationApprovedTask.java, src/main/java/uk/gov/hmcts/divorce/systemupdate/schedule/SystemRemindApplicant2Task.java, src/test/java/uk/gov/hmcts/divorce/divorcecase/model/AcknowledgementOfServiceTest.java, src/test/java/uk/gov/hmcts/divorce/divorcecase/model/ApplicantTest.java, src/test/java/uk/gov/hmcts/divorce/divorcecase/model/ApplicationTest.java, src/test/java/uk/gov/hmcts/divorce/divorcecase/model/ApplicationTypeTest.java, src/test/java/uk/gov/hmcts/divorce/divorcecase/model/SolicitorTest.java, src/test/java/uk/gov/hmcts/divorce/systemupdate/schedule/SystemAlertApplicationNotReviewedTaskTest.java, src/test/java/uk/gov/hmcts/divorce/systemupdate/schedule/SystemRemindApplicant1ApplicationApprovedTaskTest.java, src/test/java/uk/gov/hmcts/divorce/systemupdate/schedule/SystemRemindApplicant2TaskTest.java
https://tools.hmcts.net/jira/browse/NFDIV-1115
Remove Sonar exclusions of CCD model classes
Add unit tests
=> Remove sonar model exclusions and add tests

src/functionalTest/java/uk/gov/hmcts/divorce/solicitor/SolicitorPaymentMidEventCallbackTest.java, src/main/java/uk/gov/hmcts/divorce/payment/PaymentService.java, src/main/java/uk/gov/hmcts/divorce/payment/model/PbaErrorMessage.java, src/test/java/uk/gov/hmcts/divorce/payment/PaymentServiceTest.java
https://tools.hmcts.net/jira/browse/NFDIV-546
=> Refactored payments error handling as per latest error codes

src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/SolAboutApplicant1.java
https://tools.hmcts.net/jira/browse/NFDIV-1103
Before:
After:
```
[ ] Yes
[ ] No
```
=> Updated solicitor applicant details page(see screenshot in description)

src/main/java/uk/gov/hmcts/divorce/divorcecase/model/Application.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/SolStatementOfTruth.java
https://tools.hmcts.net/jira/browse/NFDIV-1063
Update Solicitor submit SOT page
=> Update solicitor submit SOT page

build.gradle, src/test/java/uk/gov/hmcts/divorce/divorcecase/model/access/AosAccessTest.java, src/test/java/uk/gov/hmcts/divorce/divorcecase/model/access/Applicant2AccessTest.java, src/test/java/uk/gov/hmcts/divorce/divorcecase/model/access/CaseAccessAdministratorTest.java, src/test/java/uk/gov/hmcts/divorce/divorcecase/model/access/CaseworkerAccessBetaOnlyAccessTest.java, src/test/java/uk/gov/hmcts/divorce/divorcecase/model/access/CaseworkerAccessTest.java, src/test/java/uk/gov/hmcts/divorce/divorcecase/model/access/CaseworkerAndSuperUserAccessTest.java, src/test/java/uk/gov/hmcts/divorce/divorcecase/model/access/CaseworkerBetaAndSuperUserAccessTest.java, src/test/java/uk/gov/hmcts/divorce/divorcecase/model/access/CaseworkerCourtAdminAccessTest.java, src/test/java/uk/gov/hmcts/divorce/divorcecase/model/access/CaseworkerCourtAdminWithSolicitorAccessTest.java, src/test/java/uk/gov/hmcts/divorce/divorcecase/model/access/DefaultAccessTest.java, src/test/java/uk/gov/hmcts/divorce/divorcecase/model/access/OrganisationPolicyAccessTest.java
Add unit tests for access classes to increase coverage
=> Add unit tests to access classes

src/main/java/uk/gov/hmcts/divorce/solicitor/event/SolicitorCreateApplication.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/SolicitorUpdateApplication.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/UploadDocument.java
https://tools.hmcts.net/jira/browse/NFDIV-1126
=> Reworded upload marriage certificate page to upload documents

src/main/java/uk/gov/hmcts/divorce/divorcecase/tab/CaseTypeTab.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/tab/TabShowCondition.java, src/test/java/uk/gov/hmcts/divorce/divorcecase/tab/TabShowConditionTest.java
https://tools.hmcts.net/jira/browse/NFDIV-1100
Add show condtion to AoS tab, only show when application type = soleApplication and not in any of the following states:
Draft, AwaitingHWFDecision, AwaitingPayment, Submitted, AwaitingDocuments
=> Add show condition to AoS tab

src/main/java/uk/gov/hmcts/divorce/citizen/event/CitizenUpdateApplication.java
https://tools.hmcts.net/jira/browse/NFDIV-1123
```
[ ] Yes
[X] No
```
=> add AwaitingApplicant1Response to update event for NFDIV-1123

src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerIssueApplication.java, src/main/java/uk/gov/hmcts/divorce/caseworker/service/IssueApplicationService.java, src/main/java/uk/gov/hmcts/divorce/caseworker/service/task/SetPostIssueState.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/State.java, src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerIssueApplicationTest.java, src/test/java/uk/gov/hmcts/divorce/caseworker/service/CaseworkerIssueApplicationServiceTest.java, src/test/java/uk/gov/hmcts/divorce/caseworker/service/task/SetPostIssueStateTest.java
https://tools.hmcts.net/jira/browse/NFDIV-1147
Add AwaitingService state
Set post state for Issue Application event
=> Add awaiting service state

src/main/java/uk/gov/hmcts/divorce/divorcecase/model/Application.java
https://tools.hmcts.net/jira/browse/NFDIV-1063
Change \"prayer\" to 'prayer' for consistency
=> Change from double quotes to single quotes

src/functionalTest/java/uk/gov/hmcts/divorce/solicitor/SolicitorSubmitAosFT.java, src/functionalTest/resources/request/casedata/ccd-callback-casedata-solicitor-submit-aos.json, src/functionalTest/resources/responses/response-solicitor-submit-aos.json, src/integrationTest/java/uk/gov/hmcts/divorce/solicitor/SolicitorSubmitAosIT.java, src/integrationTest/resources/application.yaml, src/integrationTest/resources/solicitor-submit-aos-response.json, src/main/java/uk/gov/hmcts/divorce/citizen/notification/Applicant1ResubmitNotification.java, src/main/java/uk/gov/hmcts/divorce/citizen/notification/Applicant2ApprovedNotification.java, src/main/java/uk/gov/hmcts/divorce/citizen/notification/ApplicationIssuedNotification.java, src/main/java/uk/gov/hmcts/divorce/citizen/notification/ApplicationSentForReviewApplicant1Notification.java, src/main/java/uk/gov/hmcts/divorce/citizen/notification/ApplicationSentForReviewApplicant2Notification.java, src/main/java/uk/gov/hmcts/divorce/citizen/notification/ApplicationSubmittedNotification.java, src/main/java/uk/gov/hmcts/divorce/citizen/notification/JointApplicationOverdueNotification.java, src/main/java/uk/gov/hmcts/divorce/document/DocumentConstants.java, src/main/java/uk/gov/hmcts/divorce/document/content/RespondentAnswersTemplateContent.java, src/main/java/uk/gov/hmcts/divorce/document/model/DocumentType.java, src/main/java/uk/gov/hmcts/divorce/notification/FormatUtil.java, src/main/java/uk/gov/hmcts/divorce/solicitor/service/SolicitorSubmitAosService.java, src/main/java/uk/gov/hmcts/divorce/solicitor/service/task/GenerateRespondentAnswersDoc.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/divorce/citizen/notification/Applicant1ResubmitNotificationTest.java, src/test/java/uk/gov/hmcts/divorce/citizen/notification/Applicant2ApprovedNotificationTest.java, src/test/java/uk/gov/hmcts/divorce/citizen/notification/ApplicationIssuedNotificationTest.java, src/test/java/uk/gov/hmcts/divorce/citizen/notification/ApplicationSentForReviewApplicant1NotificationTest.java, src/test/java/uk/gov/hmcts/divorce/citizen/notification/ApplicationSentForReviewApplicant2NotificationTest.java, src/test/java/uk/gov/hmcts/divorce/citizen/notification/JointApplicationOverdueNotificationTest.java, src/test/java/uk/gov/hmcts/divorce/document/content/RespondentAnswersTemplateContentTest.java, src/test/java/uk/gov/hmcts/divorce/solicitor/service/SolicitorSubmitAosServiceTest.java, src/test/java/uk/gov/hmcts/divorce/solicitor/service/task/GenerateRespondentAnswersDocTest.java
https://tools.hmcts.net/jira/browse/NFDIV-1143
-  Added task to generate respondent answers pdf as part of submit AOS.
=> Generate respondent answers pdf

src/integrationTest/java/uk/gov/hmcts/divorce/solicitor/SolicitorSubmitAosIT.java, src/integrationTest/resources/solicitor-submit-aos-response.json
=> Fix SolicitorSubmitAosIT

src/main/java/uk/gov/hmcts/divorce/systemupdate/schedule/SystemProgressHeldCasesTask.java
https://tools.hmcts.net/jira/browse/NFDIV-876
- Issue date was set to null instead of due date which is now rectified.
=> Set due date to null instead of issue date for awaiting conditional system task

src/main/java/uk/gov/hmcts/divorce/divorcecase/model/Applicant.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/tab/ApplicationTab.java
https://tools.hmcts.net/jira/browse/NFDIV-1094
Remove 'applicant' from applicant model labels, for display in application tab
Add Statement of Truth fields and change headings to mirror divorce 1
Add broken marriage fields
Update application tab field display order
=> Nfdiv 1094 application tab review changes

src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/JurisdictionApplyForDivorce.java
https://tools.hmcts.net/jira/browse/NFDIV-1093
Remove unwanted text about the court power following discussion between Kevin and Lalita
```
[ ] Yes
[x] No
```
=> Remove unwanted label from Jurisdiction Summary page

src/main/java/uk/gov/hmcts/divorce/citizen/event/CitizenApplicant1ConfirmReceipt.java, src/main/java/uk/gov/hmcts/divorce/citizen/event/CitizenApplicant2ConfirmReceipt.java, src/test/java/uk/gov/hmcts/divorce/citizen/event/CitizenApplicant1ConfirmReceiptTest.java, src/test/java/uk/gov/hmcts/divorce/citizen/event/CitizenApplicant2ConfirmReceiptTest.java
https://tools.hmcts.net/jira/browse/NFDIV-1001
Add applicant1-confirm-receipt and applicant2-confirm-receipt events, for the joint hub page
```
[ ] Yes
[x] No
```
=> NFDIV-1001 citizen confirm receipt events

build.gradle
Update deprecated gradle settings
=> Update deprecated gradle settings

src/main/java/uk/gov/hmcts/divorce/divorcecase/model/ConfidentialAddress.java
https://tools.hmcts.net/jira/browse/NFDIV-1192
=> Updated confidential address dropdown label

src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerServiceApplicationReceived.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/CaseData.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/ServiceApplication.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/ServiceApplicationType.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/tab/CaseTypeTab.java, src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerServiceApplicationReceivedTest.java, src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerSystemUserUpdateIssueDateTest.java
https://tools.hmcts.net/jira/browse/NFDIV-893
=> Added service application received for caseworkers

src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerIssueBailiffPack.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/Bailiff.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/CaseData.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/State.java, src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerIssueBailiffPackTest.java
https://tools.hmcts.net/jira/browse/NFDIV-1150
=> Added issue bailiff pack event for caseworkers

src/functionalTest/resources/application.yaml, src/integrationTest/java/uk/gov/hmcts/divorce/caseworker/CaseworkerReIssueApplicationIT.java, src/integrationTest/resources/application.yaml, src/integrationTest/resources/caseworker-reissue-application-about-to-submit-app2-not-sol-rep-offline-aos-response.json, src/integrationTest/resources/caseworker-reissue-application-about-to-submit-app2-not-sol-rep-reissue-case-response.json, src/integrationTest/resources/caseworker-reissue-application-about-to-submit-app2-sol-rep-offline-aos-response.json, src/main/java/uk/gov/hmcts/divorce/caseworker/service/ReIssueApplicationService.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/divorce/caseworker/service/ReIssueApplicationServiceTest.java
https://tools.hmcts.net/jira/browse/NFDIV-865
- Overdue days are different based on Reissue type
- For Digital - 14 days
- For Offline- 16 days
- For Complete Reissue- 16 days
This PR addresses above and makes it configurable.
=> Make overdue days configurable for different reissue types

src/functionalTest/java/uk/gov/hmcts/divorce/caseworker/CaseworkerIssueBailiffPackFT.java, src/functionalTest/resources/responses/response-caseworker-issue-bailiff-pack.json, src/integrationTest/java/uk/gov/hmcts/divorce/caseworker/CaseworkerIssueBailiffIT.java, src/integrationTest/resources/application.yaml, src/integrationTest/resources/caseworker-issue-bailiff-pack-response.json, src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerIssueBailiffPack.java, src/main/java/uk/gov/hmcts/divorce/caseworker/event/page/CreateGeneralOrder.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/Bailiff.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/tab/CaseTypeTab.java, src/main/java/uk/gov/hmcts/divorce/document/CaseDataDocumentService.java, src/main/java/uk/gov/hmcts/divorce/document/DocumentConstants.java, src/main/java/uk/gov/hmcts/divorce/document/content/CertificateOfServiceContent.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerIssueBailiffPackTest.java, src/test/java/uk/gov/hmcts/divorce/caseworker/event/page/CreateGeneralOrderTest.java, src/test/java/uk/gov/hmcts/divorce/document/CaseDataDocumentServiceTest.java, src/test/java/uk/gov/hmcts/divorce/document/content/CertificateOfServiceContentTest.java
https://tools.hmcts.net/jira/browse/NFDIV-1197
- Implements about to submit callback to generate certificate of service document.
=> Generate certificate of service document when issue bailiff is triggered

src/main/java/uk/gov/hmcts/divorce/systemupdate/schedule/SystemAlertApplicationNotReviewedTask.java, src/main/java/uk/gov/hmcts/divorce/systemupdate/schedule/SystemRemindApplicant1ApplicationApprovedTask.java, src/main/java/uk/gov/hmcts/divorce/systemupdate/schedule/SystemRemindApplicant2Task.java
Add logging to investigate due date issue. Will be able to identify whether the form to update the due date in ExUI is using the correct format.
=> NFDIV-1114

src/main/java/uk/gov/hmcts/divorce/divorcecase/model/Bailiff.java
=> Fixed type for certificate of service

src/integrationTest/java/uk/gov/hmcts/divorce/caseworker/CaseworkerIssueApplicationIT.java, src/integrationTest/java/uk/gov/hmcts/divorce/caseworker/CaseworkerReIssueApplicationIT.java, src/integrationTest/resources/application.yaml, src/main/java/uk/gov/hmcts/divorce/common/exception/InvalidCcdCaseDataException.java, src/main/java/uk/gov/hmcts/divorce/document/content/DivorceApplicationJointTemplateContent.java, src/main/java/uk/gov/hmcts/divorce/document/content/DivorceApplicationSoleTemplateContent.java, src/main/java/uk/gov/hmcts/divorce/document/content/DraftApplicationTemplateContent.java, src/main/java/uk/gov/hmcts/divorce/document/content/GeneralOrderTemplateContent.java, src/main/java/uk/gov/hmcts/divorce/document/content/RespondentSolicitorAosInvitationTemplateContent.java, src/main/java/uk/gov/hmcts/divorce/document/content/provider/ApplicantTemplateDataProvider.java, src/main/java/uk/gov/hmcts/divorce/document/content/provider/ApplicationTemplateDataProvider.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/divorce/document/content/DivorceApplicationJointTemplateContentTest.java, src/test/java/uk/gov/hmcts/divorce/document/content/DivorceApplicationSoleTemplateContentTest.java, src/test/java/uk/gov/hmcts/divorce/document/content/provider/ApplicantTemplateDataProviderTest.java, src/test/java/uk/gov/hmcts/divorce/document/content/provider/ApplicationTemplateDataProviderTest.java, src/test/java/uk/gov/hmcts/divorce/testutil/TestConstants.java
https://tools.hmcts.net/jira/browse/NFDIV-1178
Add sole divorce application generation
=> Nfdiv 1177 generate sole divorce application 2

build.gradle, src/main/java/uk/gov/hmcts/divorce/solicitor/event/SolicitorUpdateConditionalOrder.java
https://tools.hmcts.net/jira/browse/NFDIV-1121
Allow update of ConditionalOrder from Solicitor 1 login when state is ConditionalOrderDrafted
```
[ ] Yes
[x] No
```
=> Nfdiv 1121 update conditional order

src/main/java/uk/gov/hmcts/divorce/divorcecase/model/RetiredFields.java
=> Remove bad migration

src/functionalTest/resources/request/casedata/ccd-callback-casedata-applicant1-resubmit-application.json, src/functionalTest/resources/responses/response-applicant1-resubmit-application.json, src/main/java/uk/gov/hmcts/divorce/citizen/event/CitizenApplicant1Resubmit.java, src/test/java/uk/gov/hmcts/divorce/citizen/event/CitizenApplicant1ResubmitTest.java
Set app2 joint confirmation fields to null when app1 resubmits
```
[ ] Yes
[x] No
```
=> Set app2 joint confirmation fields to null when app1 resubmits

src/main/java/uk/gov/hmcts/divorce/divorcecase/model/ConditionalOrder.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/SolicitorSubmitConditionalOrder.java
https://tools.hmcts.net/jira/browse/NFDIV-1120
Add Statement of Truth page to submit conditional order event
=> Add Statement of Truth page to submit conditional order event

src/main/java/uk/gov/hmcts/divorce/divorcecase/model/ConditionalOrder.java
https://tools.hmcts.net/jira/browse/NFDIV-1120
Change solicitorAdditionalComments field type to TextArea
=> Change solicitor additional comments field to textarea type

src/main/java/uk/gov/hmcts/divorce/divorcecase/model/ConditionalOrder.java, src/main/java/uk/gov/hmcts/divorce/legaladvisor/event/LegalAdvisorGrantConditionalOrder.java, src/main/java/uk/gov/hmcts/divorce/legaladvisor/event/LegalAdvisorRefuseConditionalOrder.java, src/main/java/uk/gov/hmcts/divorce/legaladvisor/event/LegalAdvisorRequestClarification.java, src/test/java/uk/gov/hmcts/divorce/legaladvisor/event/LegalAdvisorGrantConditionalOrderTest.java, src/test/java/uk/gov/hmcts/divorce/legaladvisor/event/LegalAdvisorRefuseConditionalOrderTest.java, src/test/java/uk/gov/hmcts/divorce/legaladvisor/event/LegalAdvisorRequestClarificationTest.java
https://tools.hmcts.net/jira/browse/NFDIV-1221
Add legal advisor grant conditional order pages
=> Add legal advisor grant conditional order pages

src/main/java/uk/gov/hmcts/divorce/legaladvisor/event/LegalAdvisorGrantConditionalOrder.java
https://tools.hmcts.net/jira/browse/NFDIV-1221
Change grant conditional order event name to 'Make a decision'
=> Correct grant conditional order event name case

src/integrationTest/java/uk/gov/hmcts/divorce/caseworker/CaseworkerAddBailiffReturnIT.java, src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerAddBailiffReturn.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/Bailiff.java, src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerAddBailiffReturnTest.java
https://tools.hmcts.net/jira/browse/NFDIV-940
Add caseworker-add-bailiff-return event
=> Add bailiff return event

src/functionalTest/resources/application.yaml, src/integrationTest/resources/application.yaml, src/integrationTest/resources/caseworker-reissue-application-about-to-submit-app2-not-sol-rep-response.json, src/integrationTest/resources/caseworker-reissue-application-about-to-submit-app2-sol-rep-response.json, src/main/java/uk/gov/hmcts/divorce/caseworker/service/ReIssueApplicationService.java, src/main/java/uk/gov/hmcts/divorce/caseworker/service/task/SetReIssueAndDueDate.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/divorce/caseworker/service/ReIssueApplicationServiceTest.java, src/test/java/uk/gov/hmcts/divorce/caseworker/service/task/SetReIssueAndDueDateTest.java
https://tools.hmcts.net/jira/browse/NFDIV-1057
=> NFDIV-1057 tidy up re-issue date handling

src/main/java/uk/gov/hmcts/divorce/bulkaction/ccd/BulkActionCaseTypeTab.java, src/main/java/uk/gov/hmcts/divorce/bulkaction/data/BulkActionCaseData.java, src/main/java/uk/gov/hmcts/divorce/bulkaction/data/BulkListCaseDetails.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/ConditionalOrder.java, src/main/java/uk/gov/hmcts/divorce/systemupdate/schedule/bulkaction/SystemCreateBulkCaseListTask.java
https://tools.hmcts.net/jira/browse/NFDIV-1263
=> NFDIV-1263: Add fields to Bulk case tab

src/integrationTest/java/uk/gov/hmcts/divorce/testutil/FeesWireMock.java, src/main/java/uk/gov/hmcts/divorce/payment/PaymentService.java, src/test/java/uk/gov/hmcts/divorce/payment/PaymentServiceTest.java
Reverts hmcts/nfdiv-case-api#825
=> Revert "Revert changes to the Bailiff and Divorce service keywords"

src/main/java/uk/gov/hmcts/divorce/divorcecase/model/Bailiff.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/tab/CaseTypeTab.java
https://tools.hmcts.net/jira/browse/NFDIV-1203
Add the bailiff and deemed and dispensed fields to the Alternative Service Application tab
```
[ ] Yes
[x] No
```
=> Nfdiv 1203 service application tab update

src/main/java/uk/gov/hmcts/divorce/bulkaction/ccd/BulkActionPageBuilder.java, src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerPronounceList.java, src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerPronounceListTest.java
https://tools.hmcts.net/jira/browse/NFDIV-1270
https://tools.hmcts.net/jira/browse/NFDIV-1271
Add caseworker pronounce list event
=> Add caseworker pronounce list event

src/main/java/uk/gov/hmcts/divorce/citizen/event/CitizenUpdateContactDetails.java
https://tools.hmcts.net/jira/browse/NFDIV-1292
```
[ ] Yes
[X] No
```
=> update permissions for contact details event

src/main/java/uk/gov/hmcts/divorce/divorcecase/tab/CaseTypeTab.java
Add show condition so heading label only shows when field has been completed
=> NFDIV-1118

src/main/java/uk/gov/hmcts/divorce/bulkaction/ccd/event/CaseworkerScheduleCase.java, src/test/java/uk/gov/hmcts/divorce/bulkaction/ccd/event/CaseworkerScheduleCaseTest.java
https://tools.hmcts.net/jira/browse/NFDIV-1223
- Implements validation for hearing date to check if caseworker has not entered hearing date which is in past.
=> Add validation for hearing date

src/main/java/uk/gov/hmcts/divorce/citizen/event/CitizenUpdateContactDetails.java, src/test/java/uk/gov/hmcts/divorce/citizen/event/CitizenUpdateContactDetailsTest.java
https://tools.hmcts.net/jira/browse/NFDIV-1292
```
[ ] Yes
[X] No
```
=> fix check to see if user is app2 and update contact details.

src/main/java/uk/gov/hmcts/divorce/bulkaction/ccd/event/CaseworkerScheduleCase.java, src/test/java/uk/gov/hmcts/divorce/bulkaction/ccd/event/CaseworkerScheduleCaseTest.java
https://tools.hmcts.net/jira/browse/NFDIV-1223
=> Update error message when hearing date is entered in the future

src/integrationTest/java/uk/gov/hmcts/divorce/bulkaction/task/BulkCaseCaseTaskFactoryIT.java, src/main/java/uk/gov/hmcts/divorce/bulkaction/task/BulkActionCaseTaskProvider.java, src/main/java/uk/gov/hmcts/divorce/bulkaction/task/BulkCaseCaseTaskFactory.java, src/main/java/uk/gov/hmcts/divorce/bulkaction/task/PronounceCaseProvider.java, src/main/java/uk/gov/hmcts/divorce/bulkaction/task/UpdateCaseCourtHearingProvider.java, src/main/java/uk/gov/hmcts/divorce/bulkaction/task/UpdateCasePronouncementJudgeProvider.java, src/main/java/uk/gov/hmcts/divorce/common/config/BulkCaseConfiguration.java, src/test/java/uk/gov/hmcts/divorce/bulkaction/task/BulkCaseCaseTaskFactoryTest.java, src/test/java/uk/gov/hmcts/divorce/bulkaction/task/PronounceCaseProviderTest.java, src/test/java/uk/gov/hmcts/divorce/bulkaction/task/UpdateCaseCourtHearingProviderTest.java, src/test/java/uk/gov/hmcts/divorce/bulkaction/task/UpdateCasePronouncementJudgeProviderTest.java
Add extensible BulkCaseCaseTaskFactory, uses resource map configured by Spring
=> Add extensible BulkCaseCaseTaskFactory

src/functionalTest/java/uk/gov/hmcts/divorce/caseworker/CaseworkerIssueApplicationFT.java, src/functionalTest/resources/request/casedata/ccd-callback-caseworker-issue-sole-citizen-application-about-to-submit.json, src/functionalTest/resources/responses/response-caseworker-issue-sole-citizen-application-about-to-submit.json, src/integrationTest/java/uk/gov/hmcts/divorce/caseworker/CaseworkerIssueApplicationIT.java, src/integrationTest/java/uk/gov/hmcts/divorce/caseworker/CaseworkerReIssueApplicationIT.java, src/integrationTest/resources/application.yaml, src/integrationTest/resources/caseworker-issue-sole-citizen-application-about-to-submit-response.json, src/integrationTest/resources/caseworker-reissue-sole-citizen-application-about-to-submit-response.json, src/main/java/uk/gov/hmcts/divorce/caseworker/service/IssueApplicationService.java, src/main/java/uk/gov/hmcts/divorce/caseworker/service/task/GenerateNoticeOfProceeding.java, src/main/java/uk/gov/hmcts/divorce/document/DocumentConstants.java, src/main/java/uk/gov/hmcts/divorce/document/content/NoticeOfProceedingContent.java, src/main/java/uk/gov/hmcts/divorce/document/model/DocumentType.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/divorce/caseworker/service/CaseworkerIssueApplicationServiceTest.java, src/test/java/uk/gov/hmcts/divorce/caseworker/service/task/GenerateDivorceApplicationTest.java, src/test/java/uk/gov/hmcts/divorce/caseworker/service/task/GenerateNoticeOfProceedingTest.java, src/test/java/uk/gov/hmcts/divorce/document/content/CertificateOfServiceContentTest.java, src/test/java/uk/gov/hmcts/divorce/document/content/GeneralOrderTemplateContentTest.java, src/test/java/uk/gov/hmcts/divorce/document/content/NoticeOfProceedingContentTest.java, src/test/java/uk/gov/hmcts/divorce/document/content/ServiceOrderTemplateContentTest.java
https://tools.hmcts.net/jira/browse/NFDIV-1260
- Notice of proceeding document is generated during issue application for citizen sole applications.
=> Generate notice of proceedings for citizen sole application

src/main/java/uk/gov/hmcts/divorce/divorcecase/model/CaseData.java, src/test/java/uk/gov/hmcts/divorce/solicitor/event/SolicitorUpdateApplicationTest.java
https://tools.hmcts.net/jira/browse/NFDIV-1377
=> Sort applicant1 documents uploaded only when new docs are added

src/main/java/uk/gov/hmcts/divorce/divorcecase/tab/ApplicationTab.java
https://tools.hmcts.net/jira/browse/NFDIV-1239
Remove 2 fields from the ApplicationTab
```
[ ] Yes
[x] No
```
=> Nfdiv 1239 application tab cleanup

src/main/java/uk/gov/hmcts/divorce/caseworker/service/IssueApplicationService.java
generateNoticeOfProceeding after setting the issue date
```
[ ] Yes
[x] No
```
=> generateNoticeOfProceeding after setting the issue date

src/main/java/uk/gov/hmcts/divorce/citizen/event/CitizenSwitchedToSole.java, src/test/java/uk/gov/hmcts/divorce/citizen/event/CitizenSwitchedToSoleTest.java
https://tools.hmcts.net/jira/browse/NFDIV-1214
remove notification for app2 if marriage not broken selected
```
[ ] Yes
[x] No
```
=> nfdiv-1214 remove notification for app2 if marriage not broken selected

src/main/java/uk/gov/hmcts/divorce/divorcecase/model/ConditionalOrder.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/tab/CaseTypeTab.java, src/main/java/uk/gov/hmcts/divorce/systemupdate/service/task/GenerateCertificateOfEntitlement.java, src/test/java/uk/gov/hmcts/divorce/systemupdate/service/task/GenerateCertificateOfEntitlementTest.java
https://tools.hmcts.net/jira/browse/NFDIV-1224
Add certificate of entitlement to Outcome of conditional order tab and documents tab
=> Add certificate of entitlement to tabs

src/main/java/uk/gov/hmcts/divorce/citizen/event/CitizenUpdateContactDetails.java
=> check if applicant2 link exist.

src/main/java/uk/gov/hmcts/divorce/divorcecase/model/Applicant.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/RetiredFields.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/tab/ApplicationTab.java, src/main/java/uk/gov/hmcts/divorce/document/content/DivorceApplicationJointTemplateContent.java, src/main/java/uk/gov/hmcts/divorce/document/content/DivorceApplicationSoleTemplateContent.java, src/main/java/uk/gov/hmcts/divorce/document/content/DocmosisTemplateConstants.java, src/main/java/uk/gov/hmcts/divorce/document/content/DraftApplicationTemplateContent.java, src/main/java/uk/gov/hmcts/divorce/document/content/provider/ApplicantTemplateDataProvider.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/FinancialOrders.java, src/test/java/uk/gov/hmcts/divorce/document/content/DivorceApplicationJointTemplateContentTest.java, src/test/java/uk/gov/hmcts/divorce/document/content/DivorceApplicationSoleTemplateContentTest.java, src/test/java/uk/gov/hmcts/divorce/document/content/DraftDivorceApplicationSoleTemplateContentTest.java, src/test/java/uk/gov/hmcts/divorce/document/content/provider/ApplicantTemplateDataProviderTest.java
https://tools.hmcts.net/jira/browse/NFDIV-1290
=> NFDIV-1290: Remove Financial Order For field

src/main/java/uk/gov/hmcts/divorce/systemupdate/service/CcdSearchService.java, src/test/java/uk/gov/hmcts/divorce/systemupdate/service/CcdSearchServiceTest.java
https://tools.hmcts.net/jira/browse/NFDIV-1386
Update bulk case cron elastic search query for error or unprocessed cases.  This fixes an issue where the processed list was being ignored and fully processed bulk cases were returned from search.
=> Update bulkcase cron search for error or unprocessed cases

src/main/java/uk/gov/hmcts/divorce/divorcecase/tab/CaseTypeTab.java
https://tools.hmcts.net/jira/browse/NFDIV-1414
=> Fix court field name so that it is displayed in outcome of CO tab

src/main/java/uk/gov/hmcts/divorce/common/event/DraftAos.java, src/main/java/uk/gov/hmcts/divorce/common/event/UpdateAos.java, src/main/java/uk/gov/hmcts/divorce/common/event/page/Applicant2HowToRespondToApplication.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/AcknowledgementOfService.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/HowToRespondApplication.java
https://tools.hmcts.net/jira/browse/NFDIV-1389
=> Added how to respond to application for draft and update aos

src/main/java/uk/gov/hmcts/divorce/systemupdate/schedule/SystemMigrateCasesTask.java, src/main/java/uk/gov/hmcts/divorce/systemupdate/schedule/bulkaction/SystemMigrateBulkCasesTask.java, src/main/java/uk/gov/hmcts/divorce/systemupdate/service/CcdSearchService.java, src/test/java/uk/gov/hmcts/divorce/systemupdate/schedule/SystemMigrateCasesTaskTest.java, src/test/java/uk/gov/hmcts/divorce/systemupdate/schedule/bulkaction/SystemMigrateBulkCasesTaskTest.java, src/test/java/uk/gov/hmcts/divorce/systemupdate/service/CcdSearchServiceTest.java
https://tools.hmcts.net/jira/browse/NFDIV-1407
=> NFDIV-1407: Add exception handling for jackson deserialization

src/functionalTest/resources/request/casedata/ccd-callback-caseworker-issue-joint-citizen-application-about-to-submit.json, src/integrationTest/java/uk/gov/hmcts/divorce/caseworker/CaseworkerIssueApplicationIT.java, src/integrationTest/java/uk/gov/hmcts/divorce/caseworker/CaseworkerReIssueApplicationIT.java, src/main/java/uk/gov/hmcts/divorce/caseworker/service/task/SendApplicationIssueNotifications.java, src/test/java/uk/gov/hmcts/divorce/caseworker/service/task/SendApplicationIssueNotificationsTest.java
https://tools.hmcts.net/jira/browse/NFDIV-1348
=> NFDIV-1348: Add checks for whether app2 email is known

src/main/java/uk/gov/hmcts/divorce/common/event/page/SolicitorDetailsWithStatementOfTruth.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/AcknowledgementOfService.java
https://tools.hmcts.net/jira/browse/NFDIV-1345
=> Updated Solicitor SOT page for submit AOS

src/integrationTest/java/uk/gov/hmcts/divorce/caseworker/CaseworkerIssueApplicationIT.java, src/integrationTest/resources/application.yaml, src/integrationTest/resources/caseworker-issue-sole-citizen-application-about-to-submit-response.json, src/main/java/uk/gov/hmcts/divorce/caseworker/service/task/GenerateNoticeOfProceeding.java, src/main/java/uk/gov/hmcts/divorce/caseworker/service/task/SendApplicationIssueNotifications.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/Applicant.java, src/main/java/uk/gov/hmcts/divorce/document/DocumentConstants.java, src/main/java/uk/gov/hmcts/divorce/document/content/NoticeOfProceedingContent.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/divorce/caseworker/service/task/GenerateDivorceApplicationTest.java, src/test/java/uk/gov/hmcts/divorce/caseworker/service/task/GenerateNoticeOfProceedingTest.java, src/test/java/uk/gov/hmcts/divorce/document/content/NoticeOfProceedingContentTest.java
https://tools.hmcts.net/jira/browse/NFDIV-1283
Dependent on docmosis PR https://github.com/hmcts/rdo-docmosis/pull/991
=> Generate notice of proceedings for overseas respondent

build.gradle, src/main/java/uk/gov/hmcts/divorce/bulkaction/data/BulkActionCaseData.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/access/BulkCaseRemovalAccess.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/access/Permissions.java, src/test/java/uk/gov/hmcts/divorce/divorcecase/model/access/BulkCaseRemovalAccessTest.java
- Import new config library
- update permissions on bulk cases to be removed list to disable add button
- unit tests for new permission class
=> NFDIV-1383

src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerPronounceList.java, src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerPronounceListTest.java
https://tools.hmcts.net/jira/browse/NFDIV-1434
Add check on about to submit caseworker-pronounce-list event to return an error if pronounced before the hearing date
=> Add check to stop future pronouncements

src/integrationTest/java/uk/gov/hmcts/divorce/citizen/event/CitizenSubmitApplicationIT.java, src/integrationTest/java/uk/gov/hmcts/divorce/citizen/event/CitizenSwitchToSoleApplicationIT.java, src/main/java/uk/gov/hmcts/divorce/citizen/event/CitizenSwitchedToSole.java, src/test/java/uk/gov/hmcts/divorce/citizen/event/CitizenSwitchedToSoleTest.java, src/test/java/uk/gov/hmcts/divorce/citizen/notification/Applicant1ApplyForConditionalOrderNotificationTest.java, src/test/java/uk/gov/hmcts/divorce/testutil/TestDataHelper.java
https://tools.hmcts.net/jira/browse/NFDIV-1374
Remove the access code for app 2 when app 1 switch to sole and app2 is not yet linked to the case
Small clean up of the test data
```
[ ] Yes
[x] No
```
=> App1 switch to sole when App2 is not linked

src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerGeneralReferral.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/GeneralReferral.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/RetiredFields.java, src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerGeneralReferralTest.java, src/test/java/uk/gov/hmcts/divorce/divorcecase/model/RetiredFieldsTest.java
https://tools.hmcts.net/jira/browse/NFDIV-1236
=> Update general referral to merge judge and legal advisor details

src/main/java/uk/gov/hmcts/divorce/divorcecase/model/Applicant.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/ConditionalOrder.java, src/main/java/uk/gov/hmcts/divorce/document/content/CertificateOfEntitlementContent.java, src/test/java/uk/gov/hmcts/divorce/divorcecase/model/ApplicantTest.java, src/test/java/uk/gov/hmcts/divorce/divorcecase/model/ConditionalOrderTest.java, src/test/java/uk/gov/hmcts/divorce/document/content/CertificateOfEntitlementContentTest.java
Fix null pointer exception thrown when generating certificate of entitlement
=> Fix exception when generating certificate of entitlement

src/main/java/uk/gov/hmcts/divorce/common/event/page/Applicant2SolReviewApplicant1Application.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/AcknowledgementOfService.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/LabelContent.java
https://tools.hmcts.net/jira/browse/NFDIV-1201
=> Content review for draft solicitor aos

src/main/java/uk/gov/hmcts/divorce/citizen/event/CitizenSwitchedToSole.java
Fix app2 switch to sole notifications
Remove the state transition after the notifications are sent
```
[ ] Yes
[x] No
```
=> Fix app2 switch to sole notifications

src/main/java/uk/gov/hmcts/divorce/document/content/NoticeOfProceedingContent.java, src/test/java/uk/gov/hmcts/divorce/document/content/NoticeOfProceedingContentTest.java
https://tools.hmcts.net/jira/browse/NFDIV-1283
=> Update dynamic content for notice of proceedings overseas resp

src/integrationTest/java/uk/gov/hmcts/divorce/legaladvisor/LegalAdvisorGrantConditionalOrderIT.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/ConditionalOrder.java, src/main/java/uk/gov/hmcts/divorce/legaladvisor/event/LegalAdvisorGrantConditionalOrder.java, src/test/java/uk/gov/hmcts/divorce/legaladvisor/event/LegalAdvisorGrantConditionalOrderTest.java
https://tools.hmcts.net/jira/browse/NFDIV-1258
=> Add refusal order page when conditional order is refused

src/main/java/uk/gov/hmcts/divorce/divorcecase/model/State.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/SolicitorSubmitClarification.java
https://tools.hmcts.net/jira/browse/NFDIV-1452
=> Implemented submit clarification for conditional order

src/main/java/uk/gov/hmcts/divorce/divorcecase/tab/CaseTypeTab.java
https://tools.hmcts.net/jira/browse/NFDIV-1313
Add respondent confidential tab
```
[ ] Yes
[x] No
```
=> Nfdiv 1303 confidential tabs

src/main/java/uk/gov/hmcts/divorce/legaladvisor/event/LegalAdvisorGrantConditionalOrder.java
Allow Legal advisor to see make a decision option when case is in ClarificationSubmitted state
https://tools.hmcts.net/jira/browse/NFDIV-1465
=> NFDIV-1465

src/integrationTest/java/uk/gov/hmcts/divorce/caseworker/CaseworkerAddNoteIT.java, src/main/java/uk/gov/hmcts/divorce/common/event/page/Applicant2SolReviewApplicant1Application.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/RefusalOption.java, src/test/java/uk/gov/hmcts/divorce/common/event/page/Applicant2SolReviewApplicant1ApplicationTest.java
https://tools.hmcts.net/jira/browse/NFDIV-1201
=> Implemented midevent callback to validate respondent has read the application

src/integrationTest/java/uk/gov/hmcts/divorce/legaladvisor/LegalAdvisorMakeDecisionIT.java, src/main/java/uk/gov/hmcts/divorce/legaladvisor/event/LegalAdvisorMakeDecision.java, src/test/java/uk/gov/hmcts/divorce/legaladvisor/event/LegalAdvisorMakeDecisionTest.java, src/test/java/uk/gov/hmcts/divorce/legaladvisor/event/LegalAdvisorRefuseConditionalOrderTest.java
https://tools.hmcts.net/jira/browse/NFDIV-1460
=> Refactor legal advisor event and add additional info for admin error

src/main/java/uk/gov/hmcts/divorce/systemupdate/convert/CaseDetailsListConverter.java, src/main/java/uk/gov/hmcts/divorce/systemupdate/service/CcdSearchService.java, src/test/java/uk/gov/hmcts/divorce/systemupdate/convert/CaseDetailsListConverterTest.java, src/test/java/uk/gov/hmcts/divorce/systemupdate/service/CcdSearchServiceTest.java
https://tools.hmcts.net/jira/browse/NFDIV-1425
Handle deserialization failure when converting to CaseDetails when searching for AwaitingPronouncement cases
=> Handle deserialization failure when converting to CaseDetails

src/functionalTest/java/uk/gov/hmcts/divorce/systemupdate/event/SystemNotifyApplicantDisputeFormOverdueFT.java, src/main/java/uk/gov/hmcts/divorce/systemupdate/schedule/SystemNotifyApplicantDisputeFormOverdueTask.java
- https://tools.hmcts.net/jira/browse/NFDIV-1088
- correct notification flag and functional test names
```
[ ] Yes
[X] No
```
=> nfdiv-1088: correct notification flag and test names

src/main/java/uk/gov/hmcts/divorce/document/content/RespondentAnswersTemplateContent.java, src/test/java/uk/gov/hmcts/divorce/document/content/RespondentAnswersTemplateContentTest.java
https://tools.hmcts.net/jira/browse/NFDIV-1472
Update respondent answers template fields to add reasonCourtsOfEnglandAndWalesHaveNoJurisdiction and inWhichCountryIsYourLifeMainlyBased
=> Update respondent answers template reason fields

src/functionalTest/resources/request/casedata/ccd-callback-caseworker-issue-application-about-to-submit.json, src/functionalTest/resources/request/casedata/ccd-callback-caseworker-reject-application-about-to-submit.json, src/main/java/uk/gov/hmcts/divorce/common/event/page/Applicant2SolConfirmContactDetails.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/LabelContent.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/RetiredFields.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/Solicitor.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/tab/ApplicationTab.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/SolicitorCreateApplication.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/SolAboutTheSolicitor.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/SolUpdateContactDetails.java, src/test/java/uk/gov/hmcts/divorce/divorcecase/model/RetiredFieldsTest.java
https://tools.hmcts.net/jira/browse/NFDIV-1406
Implement changes as per https://docs.google.com/document/d/1zwt27OEP25_uB_1IV4DNU9X_X-PACHaOYdl4f-YaakE/edit#
=> Implement about the solicitor content changes

src/main/java/uk/gov/hmcts/divorce/divorcecase/model/RejectionReason.java, src/main/java/uk/gov/hmcts/divorce/legaladvisor/event/LegalAdvisorMakeDecision.java
https://tools.hmcts.net/jira/browse/NFDIV-1453
=> Added page for amend application for CO refusal and updated enum

src/main/java/uk/gov/hmcts/divorce/common/event/DraftConditionalOrder.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/Applicant.java
https://tools.hmcts.net/jira/browse/NFDIV-995
Add applyForConditionalOrderStarted fields 
```
[ ] Yes
[x] No
```
=> NFDIV-995 Add applyForConditionalOrderStarted fields

src/integrationTest/java/uk/gov/hmcts/divorce/solicitor/SolicitorApplyForFinalOrderIT.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/FinalOrder.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/LabelContent.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/State.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/SolicitorApplyForFinalOrder.java, src/test/java/uk/gov/hmcts/divorce/solicitor/event/SolicitorApplyForFinalOrderTest.java
https://tools.hmcts.net/jira/browse/NFDIV-1469
=> Solicitor apply for final order

src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerGrantFinalOrder.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/FinalOrder.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/State.java, src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerGrantFinalOrderTest.java
https://tools.hmcts.net/jira/browse/NFDIV-1482
=> NFDIV-1482: Grant final order

src/integrationTest/java/uk/gov/hmcts/divorce/legaladvisor/LegalAdvisorMakeDecisionIT.java, src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerAddAdminClarification.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/State.java, src/main/java/uk/gov/hmcts/divorce/legaladvisor/event/LegalAdvisorMakeDecision.java, src/test/java/uk/gov/hmcts/divorce/legaladvisor/event/LegalAdvisorMakeDecisionTest.java
- Display additional information textarea when LA selects free text option.
- Transition state to AwaitingAmendedApplication when LA rejects conditional order application.
- Transition state to ClarificationSubmitted when caseworker submits admin clarification.
=> Make decision state transition and fixes

src/main/java/uk/gov/hmcts/divorce/divorcecase/model/ConditionalOrder.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/SolicitorSubmitClarification.java
https://tools.hmcts.net/jira/browse/NFDIV-1497
=> Updated field description and made field optional for submit clarification response

src/main/java/uk/gov/hmcts/divorce/common/event/SubmitConditionalOrder.java, src/main/java/uk/gov/hmcts/divorce/common/event/UpdateConditionalOrder.java
https://tools.hmcts.net/jira/browse/NFDIV-995
Update grants for conditional order events to allow for Citizen and Applicant 2
(Old pr was broken)
```
[ ] Yes
[x] No
```
=> Update grants for conditional order events

src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerFinalOrderPending.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/State.java, src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerFinalOrderPendingTest.java
https://tools.hmcts.net/jira/browse/NFDIV-1483
=> Added Final order pending event for caseworkers

src/test/java/uk/gov/hmcts/divorce/citizen/event/CitizenUpdateCaseStateAatTest.java
Fix Citizen update case state test
Test is failing on master as environment is AAT
```
[ ] Yes
[x] No
```
=> Fix Citizen update case state test

src/test/java/uk/gov/hmcts/divorce/citizen/event/CitizenUpdateCaseStateAatTest.java
Remove update case state test which is failing on master as environment variable is set as AAT
```
[ ] Yes
[x] No
```
=> Remove update case state test

src/main/java/uk/gov/hmcts/divorce/divorcecase/model/ConditionalOrder.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/RetiredFields.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/tab/CaseTypeTab.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/SolicitorSubmitClarification.java, src/test/java/uk/gov/hmcts/divorce/divorcecase/model/RetiredFieldsTest.java
https://tools.hmcts.net/jira/browse/NFDIV-1471
=> Updated clarification responses to collection as we need to store previous responses

src/main/java/uk/gov/hmcts/divorce/legaladvisor/event/LegalAdvisorMakeServiceDecision.java
https://tools.hmcts.net/jira/browse/NFDIV-1215
Fix for refusal reason showing when application accepted
```
[ ] Yes
[x] No
```
=> Fix for refusal reason showing when Application is accepted

src/main/java/uk/gov/hmcts/divorce/bulkaction/task/PronounceCaseProvider.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/FinalOrder.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/tab/CaseTypeTab.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/tab/TabShowCondition.java, src/test/java/uk/gov/hmcts/divorce/bulkaction/task/PronounceCaseProviderTest.java, src/test/java/uk/gov/hmcts/divorce/divorcecase/model/FinalOrderTest.java, src/test/java/uk/gov/hmcts/divorce/divorcecase/tab/TabShowConditionTest.java
https://tools.hmcts.net/jira/browse/NFDIV-1300
Add Final Order fields dateFinalOrderNoLongerEligible and dateFinalOrderEligibleToRespondent
Add Final Order methods for calculating dates for fields
Add Final Order tab
=> Add final order tab and fields

src/main/java/uk/gov/hmcts/divorce/divorcecase/model/ConditionalOrder.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/tab/CaseTypeTab.java, src/main/java/uk/gov/hmcts/divorce/legaladvisor/event/LegalAdvisorMakeDecision.java, src/test/java/uk/gov/hmcts/divorce/legaladvisor/event/LegalAdvisorMakeDecisionTest.java
- Implements about to start callback to reset refusal fields 
- Updated show condition for MultiSelectList
- Added missing fields to case tab
=> Add about to start callback to reset refusal fields and update admin refusal page

Jenkinsfile_CNP, charts/nfdiv-case-api/Chart.yaml, charts/nfdiv-case-api/values.yaml, src/main/java/uk/gov/hmcts/divorce/citizen/event/CitizenUpdateCaseStateAat.java, src/test/java/uk/gov/hmcts/divorce/citizen/event/CitizenUpdateCaseStateAatTest.java
Add CLUSTER_NAME environment variable check for citizen update case state
```
[ ] Yes
[x] No
```
=> Add CLUSTER_NAME environment variable check for citizen update case state

src/main/java/uk/gov/hmcts/divorce/divorcecase/model/Application.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/LabelContent.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/MarriageIrretrievablyBroken.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/SolHowDoYouWantToApplyForDivorce.java
https://tools.hmcts.net/jira/browse/NFDIV-1488
=> Content changes for statement of irretrievable breakdown page

src/main/java/uk/gov/hmcts/divorce/divorcecase/tab/CaseTypeTab.java
https://tools.hmcts.net/jira/browse/NFDIV-1313
Rename tab from Confidential Address to Confidential Applicant
```
[ ] Yes
[x] No
```
=> Rename Confidential Address to Confidential Applicant

src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerAnswerReceived.java
Remove event show condition as it needs to be shown irregardless of whether disputed or not
https://tools.hmcts.net/jira/browse/NFDIV-1181
=> NFDIV-1181

src/main/java/uk/gov/hmcts/divorce/divorcecase/model/LabelContent.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/MarriageDetails.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/SolicitorCreateApplication.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/MarriageCertificateDetails.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/SolHowDoYouWantToApplyForDivorce.java
https://tools.hmcts.net/jira/browse/NFDIV-1492
=> Marriage details content changes

src/main/java/uk/gov/hmcts/divorce/divorcecase/model/Applicant.java
https://tools.hmcts.net/jira/browse/NFDIV-1493
=> Legal Proceedings content update

src/main/java/uk/gov/hmcts/divorce/bulkaction/service/CaseTriggerService.java
Add exception logging to CaseTriggerService
=> Add exception logging to CaseTriggerService

src/main/java/uk/gov/hmcts/divorce/divorcecase/model/Applicant.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/FinancialOrders.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/SolHowDoYouWantToApplyForDivorce.java
https://tools.hmcts.net/jira/browse/NFDIV-1494
=> Content changes for financial order page

src/main/java/uk/gov/hmcts/divorce/common/event/page/Applicant2SolConfirmContactDetails.java
=> Added hidden field so that label content is displayed for legal proceedings page

src/main/java/uk/gov/hmcts/divorce/divorcecase/tab/CaseTypeTab.java
https://tools.hmcts.net/jira/browse/NFDIV-1313
Allow Applicant solicitor to see Confidential Applicant Tab
```
[ ] Yes
[x] No
```
=> Add solicitor role for Confidential Applicant Tab

src/main/java/uk/gov/hmcts/divorce/divorcecase/model/CaseData.java, src/main/java/uk/gov/hmcts/divorce/document/model/DivorceDocument.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/UploadDocument.java
https://tools.hmcts.net/jira/browse/NFDIV-1498
=> Content changes for upload documents

src/main/java/uk/gov/hmcts/divorce/bulkaction/ccd/BulkActionCaseTypeConfig.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/NoFaultDivorce.java
https://tools.hmcts.net/jira/browse/NFDIV-1531
=> Updated case type description for NFD and Bulk case

src/main/java/uk/gov/hmcts/divorce/solicitor/event/SolicitorApplyForFinalOrder.java
=> Added hidden fields to display dynamic content and label values

src/functionalTest/java/uk/gov/hmcts/divorce/systemupdate/event/SystemRemindApplicantsApplyForCOrderFT.java
- https://tools.hmcts.net/jira/browse/NFDIV-1128
- https://tools.hmcts.net/jira/browse/NFDIV-1129
- https://tools.hmcts.net/jira/browse/NFDIV-1130
- fix functional test
```
[ ] Yes
[X] No
```
=> nfdiv-1128: fix functional test

src/main/java/uk/gov/hmcts/divorce/systemupdate/event/SystemProgressHeldCase.java
- https://tools.hmcts.net/jira/browse/NFDIV-1128
- https://tools.hmcts.net/jira/browse/NFDIV-1129
- https://tools.hmcts.net/jira/browse/NFDIV-1130
- fix holding state progression
```
[ ] Yes
[X] No
```
=> nfdiv-1128: fix state progression

src/main/java/uk/gov/hmcts/divorce/notification/AwaitingConditionalOrderNotification.java, src/main/java/uk/gov/hmcts/divorce/systemupdate/event/SystemProgressHeldCase.java
- https://tools.hmcts.net/jira/browse/NFDIV-1128
- https://tools.hmcts.net/jira/browse/NFDIV-1129
- https://tools.hmcts.net/jira/browse/NFDIV-1130
- check applicant 2 email address before trying to send notification
```
[ ] Yes
[X] No
```
=> nfdiv-1128: check app2 email exists before sending

src/main/java/uk/gov/hmcts/divorce/caseworker/event/page/CreateGeneralOrder.java
https://tools.hmcts.net/jira/browse/NFDIV-1235
=> Make judge and legal advisor fields optional

src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerIssueApplication.java
=> Added hidden field to display dynamic label for place of marriage

src/main/java/uk/gov/hmcts/divorce/caseworker/event/page/AnswerReceivedPaymentSummary.java, src/main/java/uk/gov/hmcts/divorce/common/event/DraftAos.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/RetiredFields.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/tab/ApplicationTab.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/tab/CaseTypeTab.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/SolicitorApplyForFinalOrder.java, src/main/java/uk/gov/hmcts/divorce/systemupdate/schedule/SystemFinalOrderOverdueTask.java, src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerAddAdminClarificationTest.java, src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerAnswerReceivedTest.java, src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerFinalOrderPendingTest.java, src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerGrantFinalOrderTest.java, src/test/java/uk/gov/hmcts/divorce/caseworker/event/page/AnswerReceivedUploadDocumentTest.java, src/test/java/uk/gov/hmcts/divorce/citizen/event/CitizenUpdateCaseStateAatTest.java, src/test/java/uk/gov/hmcts/divorce/divorcecase/model/RetiredFieldsTest.java, src/test/java/uk/gov/hmcts/divorce/divorcecase/model/access/BulkCaseRemovalAccessTest.java, src/test/java/uk/gov/hmcts/divorce/solicitor/event/SolicitorApplyForFinalOrderTest.java, src/test/java/uk/gov/hmcts/divorce/solicitor/event/SolicitorCreateApplicationTest.java, src/test/java/uk/gov/hmcts/divorce/systemupdate/event/SystemNotifyApplicantDisputeFormOverdueTest.java, src/test/java/uk/gov/hmcts/divorce/systemupdate/event/SystemNotifyFinalOrderOverdueTest.java, src/test/java/uk/gov/hmcts/divorce/systemupdate/event/SystemProgressCaseToAwaitingFinalOrderTest.java, src/test/java/uk/gov/hmcts/divorce/systemupdate/event/SystemRemindApplicantsApplyForCOrderTest.java, src/test/java/uk/gov/hmcts/divorce/systemupdate/schedule/SystemProgressCasesToAwaitingFinalOrderTaskTest.java, src/test/java/uk/gov/hmcts/divorce/systemupdate/schedule/conditionalorder/SystemRemindApplicantsApplyForCOrderTaskTest.java
Sonar has reported 57 code smells https://sonarcloud.io/project/issues?id=uk.gov.hmcts.reform%3Anfdiv-case-api&resolved=false&sinceLeakPeriod=true&types=CODE_SMELL
=> Fix code smell reported by sonar 

src/main/java/uk/gov/hmcts/divorce/caseworker/event/page/AmendCase.java
https://tools.hmcts.net/jira/browse/NFDIV-1438
=> Update case content changes

src/main/java/uk/gov/hmcts/divorce/solicitor/event/SolicitorSubmitApplication.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/SolicitorUpdateApplication.java
https://tools.hmcts.net/jira/browse/NFDIV-1344
=> Update event conditions for submit and update case

src/functionalTest/resources/request/casedata/ccd-callback-casedata.json, src/functionalTest/resources/responses/response-caseworker-add-notes-about-to-submit.json, src/functionalTest/resources/responses/response-caseworker-issue-bailiff-pack.json, src/functionalTest/resources/responses/response-solicitor-create-about-to-submit.json, src/functionalTest/resources/responses/response-solicitor-payment-mid-event.json, src/integrationTest/java/uk/gov/hmcts/divorce/solicitor/SolicitorCreateApplicationIT.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/Applicant.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/MarriageDetails.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/MarriageFormation.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/RetiredFields.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/SolicitorCreateApplication.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/SolAboutApplicant1.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/SolAboutApplicant2.java, src/main/java/uk/gov/hmcts/divorce/solicitor/service/SolicitorCreateApplicationService.java, src/main/java/uk/gov/hmcts/divorce/solicitor/service/task/SetApplicantGender.java, src/test/java/uk/gov/hmcts/divorce/solicitor/event/SolicitorCreateApplicationTest.java, src/test/java/uk/gov/hmcts/divorce/solicitor/service/SolicitorCreateApplicationApplicationServiceTest.java, src/test/java/uk/gov/hmcts/divorce/solicitor/service/task/SetApplicantGenderTest.java
See https://github.com/hmcts/nfdiv-case-api/pull/1158
=> Fix gender2

src/main/java/uk/gov/hmcts/divorce/divorcecase/model/Application.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/SolicitorSubmitJointApplication.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/FinancialOrdersForApplicant2.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/HelpWithFeesPageForApplicant2.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/MarriageIrretrievablyBroken.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/MarriageIrretrievablyBrokenForApplicant2.java, src/test/java/uk/gov/hmcts/divorce/solicitor/event/SolicitorSubmitJointApplicationTest.java, src/test/java/uk/gov/hmcts/divorce/solicitor/event/page/MarriageIrretrievablyBrokenForApplicant2Test.java
https://tools.hmcts.net/jira/browse/NFDIV-1525
=> Added solicitor submit joint application event

src/integrationTest/java/uk/gov/hmcts/divorce/document/content/CertificateOfEntitlementContentIT.java, src/main/java/uk/gov/hmcts/divorce/document/content/CertificateOfEntitlementContent.java, src/test/java/uk/gov/hmcts/divorce/document/content/CertificateOfEntitlementContentTest.java
Fix certificate of entitlement null pointer
```
[ ] Yes
[x] No
```
=> Fix certificate of entitlement null pointer

src/main/java/uk/gov/hmcts/divorce/citizen/notification/AosReminderNotifications.java, src/main/java/uk/gov/hmcts/divorce/citizen/notification/Applicant1ResubmitNotification.java, src/main/java/uk/gov/hmcts/divorce/citizen/notification/ApplicationOutstandingActionNotification.java, src/main/java/uk/gov/hmcts/divorce/citizen/notification/ApplicationRemindApplicant2Notification.java, src/main/java/uk/gov/hmcts/divorce/citizen/notification/ApplicationSentForReviewNotification.java, src/main/java/uk/gov/hmcts/divorce/common/notification/ApplicationIssuedNotification.java, src/main/java/uk/gov/hmcts/divorce/common/notification/AwaitingConditionalOrderNotification.java, src/main/java/uk/gov/hmcts/divorce/common/notification/AwaitingConditionalOrderReminderNotification.java, src/main/java/uk/gov/hmcts/divorce/common/notification/ConditionalOrderPendingReminderNotification.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/CaseData.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/ConditionalOrder.java, src/main/java/uk/gov/hmcts/divorce/notification/AwaitingConditionalOrderReminderNotification.java, src/main/java/uk/gov/hmcts/divorce/notification/CommonContent.java, src/main/java/uk/gov/hmcts/divorce/notification/ConditionalOrderPendingReminderNotification.java, src/main/java/uk/gov/hmcts/divorce/systemupdate/event/SystemProgressHeldCase.java, src/main/java/uk/gov/hmcts/divorce/systemupdate/event/SystemRemindApplicantsApplyForCOrder.java, src/test/java/uk/gov/hmcts/divorce/common/notification/AwaitingConditionalOrderNotificationTest.java, src/test/java/uk/gov/hmcts/divorce/common/notification/AwaitingConditionalOrderReminderNotificationTest.java, src/test/java/uk/gov/hmcts/divorce/common/notification/ConditionalOrderPendingReminderNotificationTest.java, src/test/java/uk/gov/hmcts/divorce/divorcecase/model/CaseDataTest.java, src/test/java/uk/gov/hmcts/divorce/divorcecase/model/ConditionalOrderTest.java, src/test/java/uk/gov/hmcts/divorce/notification/AwaitingConditionalOrderReminderNotificationTest.java, src/test/java/uk/gov/hmcts/divorce/notification/CommonContentTest.java, src/test/java/uk/gov/hmcts/divorce/notification/ConditionalOrderPendingReminderNotificationTest.java, src/test/java/uk/gov/hmcts/divorce/systemupdate/event/SystemProgressHeldCaseTest.java, src/test/java/uk/gov/hmcts/divorce/systemupdate/event/SystemRemindApplicantsApplyForCOrderTest.java
https://tools.hmcts.net/jira/browse/NFDIV-1568
Move isDivorce method inside CaseData
Refactor conditional order notifications to use NotificiationDispatcher
=> Nfdiv 1568 refactor awaiting conditional order notification

src/integrationTest/java/uk/gov/hmcts/divorce/systemupdate/service/CcdUpdateServiceIT.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/ConditionalOrder.java, src/main/java/uk/gov/hmcts/divorce/document/model/DivorceDocument.java, src/main/java/uk/gov/hmcts/divorce/systemupdate/service/CcdUpdateService.java
https://tools.hmcts.net/jira/browse/NFDIV-1616
Add temp logging to trace certificate of entitlement document
=> Add temp logging to trace certificate of entitlement document

src/main/java/uk/gov/hmcts/divorce/bulkaction/task/UpdateCasePronouncementJudgeProvider.java, src/main/java/uk/gov/hmcts/divorce/common/config/jackson/JacksonConfiguration.java, src/main/java/uk/gov/hmcts/divorce/systemupdate/service/CaseDetailsUpdater.java, src/main/java/uk/gov/hmcts/divorce/systemupdate/service/CcdUpdateService.java
https://tools.hmcts.net/jira/browse/NFDIV-1616
Add more trace logging
=> Add more logging to trace document field issue

src/functionalTest/java/uk/gov/hmcts/divorce/systemupdate/event/SystemRemindApplicantsApplyForCOrderFT.java, src/main/java/uk/gov/hmcts/divorce/systemupdate/schedule/conditionalorder/SystemRemindApplicantsApplyForCOrderTask.java
- https://tools.hmcts.net/jira/browse/NFDIV-1050
- fix flag denoting whether reminder to apply for CO has been sent
```
[ ] Yes
[X] No
```
=> nfdiv-1050: fix notification flag

src/main/java/uk/gov/hmcts/divorce/solicitor/event/SolicitorSubmitApplication.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/HelpWithFeesPage.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/SolConfirmJointApplication.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/SolPaymentSummary.java
https://tools.hmcts.net/jira/browse/NFDIV-1535
=> NFDIV-1535: Update Sign and Submit for Joint applications

src/main/java/uk/gov/hmcts/divorce/divorcecase/tab/CaseTypeTab.java
https://tools.hmcts.net/jira/browse/NFDIV-1463
=> NFDIV-1463: Configure confidential tab roles

src/functionalTest/java/uk/gov/hmcts/divorce/systemupdate/event/SystemPronounceCaseFT.java, src/functionalTest/resources/request/casedata/ccd-callback-casedata-system-pronounce-case-joint-application.json, src/main/java/uk/gov/hmcts/divorce/citizen/notification/conditionalorder/ConditionalOrderPronouncedNotification.java, src/test/java/uk/gov/hmcts/divorce/citizen/notification/conditionalorder/ConditionalOrderPronouncedNotificationTest.java
https://tools.hmcts.net/jira/browse/NFDIV-1137
```
[ ] Yes
[X] No
```
=> NFDIV-1137

package.json, src/integrationTest/java/uk/gov/hmcts/divorce/bulkaction/service/PronouncementListDocServiceIT.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/constant/ConditionalOrderCourtConstants.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/ConditionalOrderCourt.java, src/test/java/uk/gov/hmcts/divorce/bulkaction/service/CasePronouncementServiceTest.java, src/test/java/uk/gov/hmcts/divorce/bulkaction/service/CaseRemovalServiceTest.java, src/test/java/uk/gov/hmcts/divorce/bulkaction/task/UpdateCaseCourtHearingProviderTest.java, src/test/java/uk/gov/hmcts/divorce/citizen/notification/conditionalorder/ConditionalOrderPronouncedNotificationTest.java
Add conditional order court labels to definition.ts generation
=> Add conditional order court labels to definition.ts generation

src/integrationTest/java/uk/gov/hmcts/divorce/legaladvisor/LegalAdvisorGeneralConsiderationIT.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/GeneralReferral.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/GeneralReferralDecision.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/State.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/tab/CaseTypeTab.java, src/main/java/uk/gov/hmcts/divorce/legaladvisor/event/LegalAdvisorGeneralConsideration.java, src/test/java/uk/gov/hmcts/divorce/legaladvisor/event/LegalAdvisorGeneralConsiderationTest.java
https://tools.hmcts.net/jira/browse/NFDIV-1595
=> Added legal advisor general consideration event

src/main/java/uk/gov/hmcts/divorce/citizen/event/CitizenApplicant2UpdateApplication.java, src/main/java/uk/gov/hmcts/divorce/citizen/event/CitizenUpdateApplication.java
Add conditionalOrderPending state to citizen update events
```
[ ] Yes
[x] No
```
=> Update states for citizen update events

src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerRequestDwpDisclosure.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/State.java, src/main/java/uk/gov/hmcts/divorce/legaladvisor/event/LegalAdvisorGeneralConsideration.java, src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerRequestDwpDisclosureTest.java
https://tools.hmcts.net/jira/browse/NFDIV-1597
=> Added caseworker request dwp disclosure event

src/integrationTest/java/uk/gov/hmcts/divorce/caseworker/CaseworkerIssueApplicationIT.java, src/main/java/uk/gov/hmcts/divorce/citizen/notification/AosReminderNotifications.java, src/main/java/uk/gov/hmcts/divorce/common/notification/ApplicationIssuedNotification.java, src/main/java/uk/gov/hmcts/divorce/legaladvisor/notification/LegalAdvisorClarificationSubmittedNotification.java, src/test/java/uk/gov/hmcts/divorce/citizen/notification/AosReminderNotificationsTest.java, src/test/java/uk/gov/hmcts/divorce/common/notification/ApplicationIssuedNotificationTest.java, src/test/java/uk/gov/hmcts/divorce/legaladvisor/notification/LegalAdvisorClarificationSubmittedNotificationTest.java
https://tools.hmcts.net/jira/browse/NFDIV-1585
Add solicitor service checks to applicant 2 solicitor notifications
Tidy up solicitor notifications
=> Nfdiv 1585 tidy solicitor notifications

src/main/java/uk/gov/hmcts/divorce/common/event/SubmitConditionalOrder.java
https://tools.hmcts.net/jira/browse/NFDIV-1157
Update states for submit-conditional-order for joint applications
```
[ ] Yes
[x] No
```
=> NFDIV-1157 Update states for submit-conditional-order

src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerServeByAlternativeMethod.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/State.java, src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerServeByAlternativeMethodTest.java
https://tools.hmcts.net/jira/browse/NFDIV-1598
Add caseworker-serve-by-alternative-method event
=> Add caseworker serve by alternative method event

src/integrationTest/java/uk/gov/hmcts/divorce/caseworker/CaseworkerConfirmAlternativeServiceIT.java, src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerConfirmAlternativeService.java, src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerConfirmAlternativeServiceTest.java
https://tools.hmcts.net/jira/browse/NFDIV-1599
Add caseworker-confirm-alternative-service event
=> Add confirm alternative service event

build.gradle
=> Switch dm client to jitpack

src/main/java/uk/gov/hmcts/divorce/divorcecase/tab/CaseTypeTab.java
https://tools.hmcts.net/jira/browse/NFDIV-1604
Add fee payment method to general referral tab
=> Add fee payment method to general referral tab

src/main/java/uk/gov/hmcts/divorce/systemupdate/event/SystemAttachScannedDocuments.java, src/test/java/uk/gov/hmcts/divorce/systemupdate/event/SystemAttachScannedDocumentsTest.java
Progress case to OfflineDocumentReceived after documents attached to case
https://tools.hmcts.net/jira/browse/NFDIV-1635
=> NFDIV-1635

src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerGeneralReferralPayment.java
Remove legal advisor access from general referral payment event
https://tools.hmcts.net/jira/browse/NFDIV-1653
=> NFDIV-1653

src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerServeByAlternativeMethod.java
https://tools.hmcts.net/jira/browse/NFDIV-1598
caseworker-serve-by-alternative-method event available from any state
=> Serve by alternative method event available from any state

src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerConfirmAlternativeService.java
https://tools.hmcts.net/jira/browse/NFDIV-1599
caseworker-confirm-alternative-service event end state changed to holding state
=> Confirm alternative serive has holding end state

src/main/java/uk/gov/hmcts/divorce/bulkscan/validation/OcrValidator.java, src/main/java/uk/gov/hmcts/divorce/endpoint/ValidationController.java, src/main/java/uk/gov/hmcts/divorce/endpoint/data/D8Data.java, src/main/java/uk/gov/hmcts/divorce/endpoint/data/ValidationStatus.java, src/test/java/uk/gov/hmcts/divorce/bulkscan/validation/OcrValidatorTest.java, src/test/java/uk/gov/hmcts/divorce/endpoint/ValidationControllerTest.java
=> Nfdiv 1332 d8s validation

src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerGeneralReferral.java, src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerGeneralReferralPayment.java, src/main/java/uk/gov/hmcts/divorce/legaladvisor/event/LegalAdvisorGeneralConsideration.java
https://tools.hmcts.net/jira/browse/NFDIV-1634
Remove temporary logging of general referrals list
=> Remove temporary logging for general referrals

src/integrationTest/java/uk/gov/hmcts/divorce/document/content/ConditionalOrderRefusalContentIT.java, src/main/java/uk/gov/hmcts/divorce/document/content/ConditionalOrderRefusalContent.java
https://tools.hmcts.net/jira/browse/NFDIV-1464
Update template var and format id for NFD conditional order refusal document
```
[ ] Yes
[X] No
```
=> Update and format case reference for conditional order refusal doc

src/main/java/uk/gov/hmcts/divorce/divorcecase/model/Solicitor.java
add solicitor firm name field
```
[ ] Yes
[X] No
```
=> add solicitor firm name field for FE

src/main/java/uk/gov/hmcts/divorce/divorcecase/model/State.java
Some states are missing CAA access. This was fine before but now there is NoC it needs to be on a wider range of states
=> Add missing CAA access

src/main/java/uk/gov/hmcts/divorce/citizen/event/CitizenSwitchedToSole.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/Application.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/CaseData.java
- https://tools.hmcts.net/jira/browse/NFDIV-1707
-  enable applicant2 to submit switch-to-sole event by granting them access to relevant case fields
```
[ ] Yes
[X] No
```
=> nfdiv-1707: enable applicant2 to submit switch-to-sole event

src/main/java/uk/gov/hmcts/divorce/common/event/DraftConditionalOrder.java, src/main/java/uk/gov/hmcts/divorce/common/event/page/ConditionalOrderReviewAoS.java, src/main/java/uk/gov/hmcts/divorce/common/event/page/ConditionalOrderReviewApplicant1.java, src/test/java/uk/gov/hmcts/divorce/common/event/page/ConditionalOrderReviewAoSTest.java
https://tools.hmcts.net/jira/browse/NFDIV-1647
Update sole application draft conditional order for solicitor journey to fire validation and prevent a user continuing if they select no to the first page, and change the review page to match the citizen journey.
Update unit tests and clean up spacing.
```
[ ] Yes
[X] No
```
=> NFDIV-1647 Fix draft conditional order sole application

src/main/java/uk/gov/hmcts/divorce/common/event/SubmitConditionalOrder.java, src/main/java/uk/gov/hmcts/divorce/common/event/SubmitJointConditionalOrder.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/ConditionalOrder.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/ConditionalOrderQuestions.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/RetiredFields.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/SolHowDoYouWantToApplyForDivorce.java, src/main/resources/data/joint.json, src/main/resources/data/sole.json, src/test/java/uk/gov/hmcts/divorce/common/event/SubmitConditionalOrderTest.java, src/test/java/uk/gov/hmcts/divorce/common/event/SubmitJointConditionalOrderTest.java, src/test/java/uk/gov/hmcts/divorce/divorcecase/model/RetiredFieldsTest.java, src/test/java/uk/gov/hmcts/divorce/solicitor/event/page/SolHowDoYouWantToApplyForDivorceTest.java
https://tools.hmcts.net/jira/browse/NFDIV-1649
=> NFDIV-1649

src/main/java/uk/gov/hmcts/divorce/common/event/DraftConditionalOrder.java, src/main/java/uk/gov/hmcts/divorce/common/event/UpdateConditionalOrder.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/ConditionalOrderQuestions.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/SolHowDoYouWantToApplyForDivorce.java, src/main/resources/data/joint.json, src/main/resources/data/sole.json, src/test/java/uk/gov/hmcts/divorce/common/event/DraftConditionalOrderTest.java, src/test/java/uk/gov/hmcts/divorce/solicitor/event/page/SolHowDoYouWantToApplyForDivorceTest.java
https://tools.hmcts.net/jira/browse/NFDIV-1647
Re-work sole draft conditional order to allow joint conditional order to be filed by applicant1 only (applicant2 is another story).
```
[ ] Yes
[X] No
```
=> Nfd 1647 add joint draft cond order app1

src/main/java/uk/gov/hmcts/divorce/common/event/UpdateJointConditionalOrder.java, src/test/java/uk/gov/hmcts/divorce/common/event/UpdateJointConditionalOrderTest.java
https://tools.hmcts.net/jira/browse/NFDIV-1663
=> NFDIV-1663

src/main/java/uk/gov/hmcts/divorce/common/event/DraftJointConditionalOrder.java, src/main/java/uk/gov/hmcts/divorce/common/event/UpdateJointConditionalOrder.java, src/main/java/uk/gov/hmcts/divorce/common/event/page/ConditionalOrderReviewAoSApplicant2.java, src/main/java/uk/gov/hmcts/divorce/common/event/page/ConditionalOrderReviewApplicant2.java, src/test/java/uk/gov/hmcts/divorce/common/event/DraftJointConditionalOrderTest.java, src/test/java/uk/gov/hmcts/divorce/common/event/UpdateJointConditionalOrderTest.java, src/test/java/uk/gov/hmcts/divorce/common/event/page/ConditionalOrderReviewAoSApplicant2Test.java
Add new draft-joint-conditional-order event to allow applicant 2 to draft a conditional order on a joint application.
```
[ ] Yes
[X] No
```
=> Add ability for applicant 2 to draft a conditional order for joint application

src/main/java/uk/gov/hmcts/divorce/bulkaction/task/BulkActionCaseTaskException.java, src/main/java/uk/gov/hmcts/divorce/bulkaction/task/PronounceCaseProvider.java, src/main/java/uk/gov/hmcts/divorce/systemupdate/service/CcdUpdateService.java, src/test/java/uk/gov/hmcts/divorce/bulkaction/task/PronounceCaseProviderTest.java
Add null check to pronounce case data update, if dateAndTimeOfHearing is null then log error and throw exception
=> Add null check to pronounce case data update

build.gradle
Bump tomcat-embed-core to 9.0.58 for CVE-2022-23181
Bump tomcat-embed-websocket to 9.0.58 for CVE-2022-23181
=> Bump tomcat-embed-core to 9.0.58

src/main/java/uk/gov/hmcts/divorce/divorcecase/model/Applicant.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/RetiredFields.java, src/main/java/uk/gov/hmcts/divorce/document/content/DraftApplicationTemplateContent.java, src/main/java/uk/gov/hmcts/divorce/document/content/provider/ApplicantTemplateDataProvider.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/FinancialOrders.java, src/test/java/uk/gov/hmcts/divorce/document/content/DraftDivorceApplicationSoleTemplateContentTest.java, src/test/java/uk/gov/hmcts/divorce/document/content/provider/ApplicantTemplateDataProviderTest.java
https://tools.hmcts.net/jira/browse/NFDIV-1641
Revert the revert of financialOrderFor field
Use financialOrdersFor field in templates and pages
=> Revert the revert of financialOrderFor field

src/main/java/uk/gov/hmcts/divorce/divorcecase/model/FinalOrder.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/tab/CaseTypeTab.java
https://tools.hmcts.net/jira/browse/NFDIV-1355
add final order late fields
```
[ ] Yes
[x] No
```
=> nfdiv-1355 add final order late fields

src/main/java/uk/gov/hmcts/divorce/solicitor/event/SolicitorUpdateApplicant1ContactDetails.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/SolicitorUpdateApplicant2ContactDetails.java
Update applicant 1 contact details should only be visible to app 1 solicitor
=> NFDIV-1725

src/main/java/uk/gov/hmcts/divorce/divorcecase/tab/CaseTypeTab.java
https://tools.hmcts.net/jira/browse/NFDIV-330
add Applicant label to FO tab
```
[ ] Yes
[x] No
```
=> Nfdiv-330 add Applicant label to FO tab

src/main/java/uk/gov/hmcts/divorce/common/event/DraftConditionalOrder.java, src/main/java/uk/gov/hmcts/divorce/common/event/DraftJointConditionalOrder.java, src/test/java/uk/gov/hmcts/divorce/common/event/DraftConditionalOrderTest.java, src/test/java/uk/gov/hmcts/divorce/common/event/DraftJointConditionalOrderTest.java
https://tools.hmcts.net/jira/browse/NFDIV-1647
https://tools.hmcts.net/jira/browse/NFDIV-1659
Fix broken "Link to application" on review page for draft conditional order.
```
[ ] Yes
[X] No
```
=> Fix draft cond order app link

src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/Applicant2ServiceDetails.java
https://tools.hmcts.net/jira/browse/NFDIV-1666
Remove leftover / unwanted annotation as not used.
```
[ ] Yes
[X] No
```
=> Remove logging annotation from Applicant2ServiceDetails

src/main/java/uk/gov/hmcts/divorce/divorcecase/model/Solicitor.java
System update user has `R` access on below fields which results in ccd throwing 404 error. Hence updating it to have write `CRU` access so that case can be created via bulk scan
```
applicant2SolicitorAgreeToReceiveEmailsCheckbox
applicant2SolicitorPhone
applicant1SolicitorPhone
applicant1SolicitorReference
applicant2SolicitorReference
```
=> Updated access for system update for bulk scan case creation

src/main/java/uk/gov/hmcts/divorce/divorcecase/model/Application.java
https://tools.hmcts.net/jira/browse/NFDIV-1656
```
[ ] Yes
[X] No
```
=> clean up to use correct app2 term

src/integrationTest/java/uk/gov/hmcts/divorce/caseworker/CaseworkerIssueBailiffIT.java, src/integrationTest/java/uk/gov/hmcts/divorce/document/content/CertificateOfServiceContentIT.java, src/main/java/uk/gov/hmcts/divorce/document/content/CertificateOfServiceContent.java
https://tools.hmcts.net/jira/browse/NFDIV-1702
Updated the content of Certificate of service document
```
[ ] Yes
[x] No
```
=> NFDIV-1702 : Update the content of Certificate of service document

src/main/java/uk/gov/hmcts/divorce/common/event/DraftJointConditionalOrder.java
https://tools.hmcts.net/jira/browse/NFDIV-1659
Add missing aboutToStart to draft joint conditional order event.
```
[ ] Yes
[X] No
```
=> add aboutToStart to draftJointConditionalOrder event

src/main/java/uk/gov/hmcts/divorce/citizen/event/CitizenSubmitApplication.java
https://tools.hmcts.net/jira/browse/NFDIV-1670
=> NFDIV-1670 update name of citizen submit event

src/functionalTest/resources/application.yaml, src/integrationTest/java/uk/gov/hmcts/divorce/caseworker/CaseworkerIssueApplicationIT.java, src/integrationTest/resources/application.yaml, src/integrationTest/resources/wiremock/responses/about-to-submit-citizen-submit-aos-without-dispute.json, src/main/java/uk/gov/hmcts/divorce/caseworker/service/IssueApplicationService.java, src/main/java/uk/gov/hmcts/divorce/caseworker/service/task/SetDueDateAfterIssue.java, src/main/java/uk/gov/hmcts/divorce/common/service/HoldingPeriodService.java, src/main/java/uk/gov/hmcts/divorce/document/content/NoticeOfProceedingContent.java, src/main/java/uk/gov/hmcts/divorce/systemupdate/schedule/SystemProgressHeldCasesTask.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/divorce/caseworker/service/task/SetDueDateAfterIssueTest.java, src/test/java/uk/gov/hmcts/divorce/common/service/HoldingPeriodServiceTest.java, src/test/java/uk/gov/hmcts/divorce/systemupdate/schedule/SystemProgressHeldCasesTaskTest.java
https://tools.hmcts.net/jira/browse/NFDIV-1776
- Remove redundant configuration option
- Switch to using 141 days rather than 20 weeks
- Use HoldingPeriodService everywhere
=> NFDIV-1776 Clean up handling of 20 week holding period

src/main/java/uk/gov/hmcts/divorce/systemupdate/event/SystemLinkApplicant2.java
https://tools.hmcts.net/jira/browse/NFDIV-1723
=> NFDIV-1723 Allow linking of applicant2 when case is in AosOverdue

src/main/java/uk/gov/hmcts/divorce/divorcecase/model/Applicant.java, src/test/java/uk/gov/hmcts/divorce/divorcecase/model/ApplicantTest.java
Update Applicant isBasedOverseas method to return false if the applicant is represented
=> Change Applicant isBasedOverseas to check isRepresented

src/main/java/uk/gov/hmcts/divorce/citizen/notification/JointApplicationApprovedReminder.java, src/main/java/uk/gov/hmcts/divorce/common/service/task/SetStateAfterSubmission.java, src/test/java/uk/gov/hmcts/divorce/citizen/notification/JointApplicationApprovedReminderTest.java, src/test/java/uk/gov/hmcts/divorce/common/service/task/SetStateAfterSubmissionTest.java
[NFDIV-1795](https://tools.hmcts.net/jira/browse/NFDIV-1795)
```
[ ] Yes
[X] No
```
=> consider app2 for HWF conditions

src/functionalTest/resources/request/casedata/ccd-callback-make-service-decision.json, src/functionalTest/resources/responses/response-la-make-service-decision-deemed.json, src/functionalTest/resources/responses/response-la-make-service-decision-dispensed.json, src/integrationTest/java/uk/gov/hmcts/divorce/legaladvisor/LegalAdvisorMakeServiceDecisionIT.java, src/integrationTest/resources/legal-advisor-service-decision-deemed-response.json, src/integrationTest/resources/legal-advisor-service-decision-dispensed-response.json, src/main/java/uk/gov/hmcts/divorce/legaladvisor/event/LegalAdvisorMakeServiceDecision.java, src/test/java/uk/gov/hmcts/divorce/legaladvisor/event/LegalAdvisorMakeServiceDecisionTest.java
https://tools.hmcts.net/jira/browse/NFDIV-1801
If the case hasn't been issued the set the case state to Submitted on successful service application
=> NFDIV-1801 check case has been issued when returning from alternative service

src/functionalTest/resources/application.yaml, src/integrationTest/java/uk/gov/hmcts/divorce/document/content/GeneralOrderTemplateContentIT.java, src/integrationTest/java/uk/gov/hmcts/divorce/document/content/NoticeOfProceedingContentIT.java, src/integrationTest/java/uk/gov/hmcts/divorce/document/content/ServiceOrderTemplateContentIT.java, src/integrationTest/resources/application.yaml, src/main/java/uk/gov/hmcts/divorce/document/content/DocmosisTemplateConstants.java, src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/NFDIV-1677
Update email address and postal address to new values.
```
[ ] Yes
[X] No
```
=> Nfdiv 1677 update email and address

src/main/java/uk/gov/hmcts/divorce/common/event/CreateTestCase.java, src/test/java/uk/gov/hmcts/divorce/common/event/CreateTestCaseTest.java
=> Restrict user id passed during test case creation to being only a valid uuid

src/main/java/uk/gov/hmcts/divorce/solicitor/event/SolicitorSubmitApplication.java
https://tools.hmcts.net/jira/browse/NFDIV-1824
=> NFDIV-1824 Reset SoR on solicitor submit application

src/main/java/uk/gov/hmcts/divorce/common/event/Applicant2Approve.java
https://tools.hmcts.net/jira/browse/NFDIV-1808
The event gets triggered by the system user after SolicitorSubmitJointApplication
=> NFDIV-1808 remove app2 solicitor2 access from applicant2 approve event

src/main/java/uk/gov/hmcts/divorce/divorcecase/tab/CaseTypeTab.java
https://tools.hmcts.net/jira/browse/NFDIV-1796
Update to add titles to each applicants HWF number
=> NFDIV-1796 add titles to HWF fields on payments tab

src/main/java/uk/gov/hmcts/divorce/divorcecase/tab/CaseTypeTab.java
https://tools.hmcts.net/jira/browse/NFDIV-1807
```
[ ] Yes
[X] No
```
=> add app2 documents to case tab documents

src/integrationTest/java/uk/gov/hmcts/divorce/common/SubmitAosIT.java, src/integrationTest/resources/application.yaml, src/integrationTest/resources/solicitor-submit-aos-disputed-offline-response.json, src/main/java/uk/gov/hmcts/divorce/caseworker/service/print/AosPackPrinter.java, src/main/java/uk/gov/hmcts/divorce/caseworker/service/task/SendAosResponseLetterPackToApplicant.java, src/main/java/uk/gov/hmcts/divorce/common/service/SubmitAosService.java, src/main/java/uk/gov/hmcts/divorce/common/service/task/GenerateAosResponseLetterDocument.java, src/main/java/uk/gov/hmcts/divorce/document/DocumentConstants.java, src/main/java/uk/gov/hmcts/divorce/document/DocumentUtil.java, src/main/java/uk/gov/hmcts/divorce/document/content/AosResponseLetterTemplateContent.java, src/main/java/uk/gov/hmcts/divorce/document/model/DocumentType.java, src/main/java/uk/gov/hmcts/divorce/document/print/BulkPrintService.java, src/main/java/uk/gov/hmcts/divorce/document/print/model/Letter.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/divorce/caseworker/service/print/AosPackPrinterTest.java, src/test/java/uk/gov/hmcts/divorce/caseworker/service/task/SendAosResponseLetterPackToApplicantTest.java, src/test/java/uk/gov/hmcts/divorce/common/service/SubmitAosServiceTest.java, src/test/java/uk/gov/hmcts/divorce/common/service/task/GenerateAosResponseLetterDocumentTest.java, src/test/java/uk/gov/hmcts/divorce/document/content/AosResponseLetterTemplateContentTest.java, src/test/java/uk/gov/hmcts/divorce/document/print/BulkPrintServiceTest.java
https://tools.hmcts.net/jira/browse/NFDIV-1718
=> Add AOS Response pack for applicant - offline case and Disputed AOS

src/main/java/uk/gov/hmcts/divorce/divorcecase/model/LabelContent.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/MarriageDetails.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/tab/ApplicationTab.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/tab/CaseTypeTab.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/SolHowDoYouWantToApplyForDivorce.java, src/main/resources/data/joint.json, src/main/resources/data/sole.json, src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerCreatePaperCaseTest.java
https://tools.hmcts.net/jira/browse/NFDIV-1539
=> NFDIV-1539: Update tab content for marriage vs civil partnership

src/main/java/uk/gov/hmcts/divorce/common/event/ApplyForFinalOrder.java, src/test/java/uk/gov/hmcts/divorce/common/event/ApplyForFinalOrderTest.java
Fix final order requested state transition
```
[ ] Yes
[x] No
```
=> Fix final order requested state transition

src/main/java/uk/gov/hmcts/divorce/divorcecase/tab/CaseTypeTab.java
https://tools.hmcts.net/jira/browse/NFDIV-1632
=> NFDIV-1632: Make changes to AoS tab

src/main/java/uk/gov/hmcts/divorce/caseworker/service/print/AosOverduePrinter.java, src/test/java/uk/gov/hmcts/divorce/document/DocumentUtilTest.java
https://tools.hmcts.net/jira/browse/NFDIV-1719
Reverted sort by doc added date as the latest document will always be at the top of the list
```
[ ] Yes
[x] No
```
=> NFDIV-1719 : reverted sort by doc added date

src/main/java/uk/gov/hmcts/divorce/divorcecase/tab/ApplicationTab.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/SolHowDoYouWantToApplyForDivorce.java
https://tools.hmcts.net/jira/browse/NFDIV-1433
Fix missing dynamic fields for applicant headings
=> Nfdiv 1433 add application tab dynamic labels

src/main/java/uk/gov/hmcts/divorce/caseworker/event/page/CorrectPaperCase.java
https://tools.hmcts.net/jira/browse/NFDIV-1855
- Also made scanned documents optional otherwise it forces caseworker to enter exception record reference
=> Update respondent telephone email and scanned documents optional

src/main/java/uk/gov/hmcts/divorce/caseworker/event/page/CorrectPaperCase.java
https://tools.hmcts.net/jira/browse/NFDIV-1873
https://tools.hmcts.net/jira/browse/NFDIV-1877
Correct paper case screen content changes
```
[ ] Yes
[x] No
```
=> NFDIV-1873,1877 : screen content changes

src/main/java/uk/gov/hmcts/divorce/solicitor/event/SolicitorSubmitApplication.java
https://tools.hmcts.net/jira/browse/NFDIV-1850
=> NFDIV-1850: Sign and submit to only be seen by app1 solicitor

src/main/resources/data/joint.json, src/main/resources/data/sole.json
Fix create test case missing dynamic field
=> Fix create test case missing dynamic field

build.gradle, src/main/java/uk/gov/hmcts/divorce/divorcecase/tab/CaseTypeTab.java
https://tools.hmcts.net/jira/browse/NFDIV-1788
=> NFDIV-1788 Add payment history tab

src/main/java/uk/gov/hmcts/divorce/divorcecase/tab/CaseAccessAdministratorSearchTab.java
=> Restore CAA tab

src/integrationTest/java/uk/gov/hmcts/divorce/caseworker/CaseworkerIssueApplicationIT.java, src/integrationTest/java/uk/gov/hmcts/divorce/caseworker/CaseworkerReIssueApplicationIT.java, src/integrationTest/java/uk/gov/hmcts/divorce/citizen/event/Applicant1ResubmitIT.java, src/integrationTest/java/uk/gov/hmcts/divorce/citizen/event/CitizenSubmitApplicationIT.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/validation/ValidationUtil.java, src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerIssueApplicationTest.java, src/test/java/uk/gov/hmcts/divorce/citizen/event/CitizenSubmitApplicationTest.java, src/test/java/uk/gov/hmcts/divorce/common/event/InviteApplicant2Test.java, src/test/java/uk/gov/hmcts/divorce/divorcecase/validation/CaseValidationTest.java
Only validate app2 gender if app2 email populated (thus online)
=> NFDIV-1847

src/cftlib/java/uk/gov/hmcts/divorce/cftlib/CftLibConfig.java, src/integrationTest/resources/d8-transformation-success-response.json, src/integrationTest/resources/d8s-transformation-success-response.json, src/integrationTest/resources/transformation-success-warning-response.json, src/main/java/uk/gov/hmcts/divorce/bulkscan/transformation/PaperFormDetailsTransformer.java, src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerCreatePaperCase.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/Application.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/CaseData.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/PaperCasePaymentMethod.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/tab/CaseTypeTab.java, src/test/java/uk/gov/hmcts/divorce/bulkscan/transformation/PaperFormDetailsTransformerTest.java, src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerCreatePaperCaseTest.java, src/test/resources/transformation/input/valid-paper-form-ocr.json, src/test/resources/transformation/output/paper-form-transformed-warnings.json, src/test/resources/transformation/output/paper-form-transformed.json
https://tools.hmcts.net/jira/browse/NFDIV-1400
=> NFDIV-1400: Add paper case payment method and new paper case flag field

src/integrationTest/java/uk/gov/hmcts/divorce/caseworker/CaseworkerGeneralEmailIT.java, src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerGeneralEmail.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/CaseData.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/GeneralEmailDetails.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/tab/CaseTypeTab.java, src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerGeneralEmailTest.java
https://tools.hmcts.net/jira/browse/NFDIV-1750
=> Add general email collection to correspondence tab 

src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerCorrectPaperCase.java, src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerCorrectPaperCaseTest.java, src/test/java/uk/gov/hmcts/divorce/common/event/SubmitClarificationTest.java
https://tools.hmcts.net/jira/browse/NFDIV-1910
=> NFDIV-1910: Remove warnings once the paper case is corrected

src/main/java/uk/gov/hmcts/divorce/caseworker/event/page/CorrectPaperCase.java, src/test/java/uk/gov/hmcts/divorce/caseworker/event/page/CorrectPaperCaseTest.java
https://tools.hmcts.net/jira/browse/NFDIV-1891
=> NFDIV-1891: Remove prayer from correct paper case

src/integrationTest/java/uk/gov/hmcts/divorce/caseworker/CaseworkerConfirmServiceIT.java, src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerConfirmService.java, src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerConfirmServiceTest.java
https://tools.hmcts.net/jira/browse/NFDIV-1592
=> Added caseworker confirm service event

src/main/java/uk/gov/hmcts/divorce/document/content/NoticeOfProceedingContent.java, src/main/java/uk/gov/hmcts/divorce/document/content/NoticeOfProceedingJointContent.java
https://tools.hmcts.net/jira/browse/NFDIV-1829
Correct respondent NOP wording
=> Update Divorce Service wording

src/main/java/uk/gov/hmcts/divorce/divorcecase/model/CaseData.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/RetiredFields.java
=> Remove unused field

src/functionalTest/resources/responses/response-caseworker-issue-sole-citizen-application-about-to-submit.json, src/integrationTest/java/uk/gov/hmcts/divorce/caseworker/CaseworkerIssueApplicationIT.java, src/integrationTest/java/uk/gov/hmcts/divorce/caseworker/CaseworkerReIssueApplicationIT.java, src/integrationTest/resources/caseworker-issue-application-about-to-submit-app2-not-sol-rep-response.json, src/integrationTest/resources/caseworker-issue-application-draft-application-removal-response.json, src/integrationTest/resources/caseworker-issue-sole-citizen-uk-based-application-about-to-submit-response.json, src/integrationTest/resources/caseworker-reissue-application-about-to-submit-app2-not-sol-rep-reissue-case-response.json, src/integrationTest/resources/caseworker-reissue-application-about-to-submit-app2-not-sol-rep-response.json, src/main/java/uk/gov/hmcts/divorce/caseworker/service/task/GenerateRespondentAosInvitation.java, src/test/java/uk/gov/hmcts/divorce/caseworker/service/task/GenerateRespondentAosInvitationTest.java
https://tools.hmcts.net/jira/browse/NFDIV-1912
=> Removed coversheet for citizen digital respondent

src/main/java/uk/gov/hmcts/divorce/caseworker/event/page/CorrectPaperCase.java
https://tools.hmcts.net/jira/browse/NFDIV-1919
=> Fix validation errors on correct paper case D8 form

src/integrationTest/resources/d8-transformation-success-response.json, src/integrationTest/resources/d8s-transformation-success-response.json, src/integrationTest/resources/transformation-success-warning-response.json, src/main/java/uk/gov/hmcts/divorce/bulkscan/transformation/Applicant1Transformer.java, src/main/java/uk/gov/hmcts/divorce/bulkscan/transformation/Applicant2Transformer.java, src/main/java/uk/gov/hmcts/divorce/bulkscan/transformation/MarriageDetailsTransformer.java, src/test/java/uk/gov/hmcts/divorce/bulkscan/transformation/MarriageDetailsTransformerTest.java, src/test/resources/transformation/output/applicant1-transformed-invalid-sol-warnings.json, src/test/resources/transformation/output/applicant1-transformed.json, src/test/resources/transformation/output/applicant2-transformed.json, src/test/resources/transformation/output/marriage-details-transformed.json
https://tools.hmcts.net/jira/browse/NFDIV-1851
=> Fix marriage broken down and certificate/translation details

src/main/java/uk/gov/hmcts/divorce/caseworker/event/page/CorrectPaperCase.java, src/test/java/uk/gov/hmcts/divorce/caseworker/event/page/CorrectPaperCaseTest.java
https://tools.hmcts.net/jira/browse/NFDIV-1920
=> Fix marriage broken down validation for sole application

src/main/java/uk/gov/hmcts/divorce/common/event/Applicant2Approve.java, src/test/java/uk/gov/hmcts/divorce/common/event/Applicant2ApproveTest.java
https://tools.hmcts.net/jira/browse/NFDIV-1818
Generate applicant 2 answers document only if a joint application and applicant 1 is represented
=> Change when applicant2 answers are generated

src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/SolAboutApplicant2.java
https://tools.hmcts.net/jira/browse/NFDIV-1889
For Sole:
For Joint:
=> Hide applicant 2/respondent name changed question for joint applications

src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerMakeBailiffDecision.java
https://tools.hmcts.net/jira/browse/NFDIV-1905
=> Updated permissions so that LA can trigger make bailiff decision event

src/main/java/uk/gov/hmcts/divorce/caseworker/event/page/CorrectPaperCase.java
https://tools.hmcts.net/jira/browse/NFDIV-1898
=> Removed place of marriage from correct paper case as it is not on D8 form

src/main/java/uk/gov/hmcts/divorce/notification/NotificationDispatcher.java, src/test/java/uk/gov/hmcts/divorce/notification/NotificationDispatcherTest.java
Corrections for application review notification for applicant 2
```
[ ] Yes
[x] No
```
=> Corrections for application review notification for applicant 2

src/main/java/uk/gov/hmcts/divorce/divorcecase/tab/CaseTypeTab.java
Manage when the scanned documents should be shown on documents tabs
https://tools.hmcts.net/jira/browse/NFDIV-1937
=> NFDIV-1937

charts/nfdiv-case-api/Chart.yaml, charts/nfdiv-case-api/values.yaml, src/integrationTest/resources/application.yaml, src/main/java/uk/gov/hmcts/divorce/common/notification/ApplicationIssuedNotification.java, src/main/java/uk/gov/hmcts/divorce/notification/CommonContent.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/divorce/common/notification/ApplicationIssuedNotificationTest.java
https://tools.hmcts.net/jira/browse/NFDIV-1827
=> Update template content for solicitor service solicitor notification

src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerMakeBailiffDecision.java, src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerMakeBailiffDecisionTest.java
https://tools.hmcts.net/jira/browse/NFDIV-1278
- To fix the missing scenario for AC3.
```
[ ] Yes
[X] No
```
=> NFDIV-1278 - Notification when the service application is successful (part 2)

src/integrationTest/resources/valid-d8-ocr.json, src/integrationTest/resources/valid-d8s-ocr.json, src/integrationTest/resources/valid-ocr-with-warnings.json, src/main/java/uk/gov/hmcts/divorce/bulkscan/transformation/Applicant2Transformer.java, src/test/resources/transformation/input/invalid-applicant2-ocr.json, src/test/resources/transformation/input/valid-applicant2-ocr.json
https://tools.hmcts.net/jira/browse/NFDIV-1962
=> NFDIV-1962: Ensure app2 solicitor address is pulled through correctly

src/main/java/uk/gov/hmcts/divorce/caseworker/event/page/CorrectPaperCase.java
https://tools.hmcts.net/jira/browse/NFDIV-1963
Solicitor field validations updated as per ticket
```
[ ] Yes
[x] No
```
=> NFDIV-1963 : Correct paper case - Solicitor details validations

src/main/java/uk/gov/hmcts/divorce/divorcecase/tab/CaseTypeTab.java
https://tools.hmcts.net/jira/browse/NFDIV-1938
=> NFDIV-1938: Add paper form other payment details to payment tab

src/main/java/uk/gov/hmcts/divorce/divorcecase/tab/ApplicationTab.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/tab/CaseTypeTab.java
https://tools.hmcts.net/jira/browse/NFDIV-1981
=> NFDIV-1981: Show marriage formation type only for online cases

src/functionalTest/resources/responses/response-solicitor-payment-mid-event.json
N/A
Changed PBA number to fix FT.
```
[ ] Yes
[X] No
```
=> Fix failing functional test as pba number was updated

src/main/java/uk/gov/hmcts/divorce/caseworker/event/page/CorrectPaperCase.java
https://tools.hmcts.net/jira/browse/NFDIV-2000
=> Move service details above marriage details as per PO review

src/functionalTest/resources/application.yaml, src/integrationTest/resources/application.yaml, src/main/java/uk/gov/hmcts/divorce/common/notification/ApplicationIssuedNotification.java, src/main/java/uk/gov/hmcts/divorce/common/service/HoldingPeriodService.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/divorce/common/notification/ApplicationIssuedNotificationTest.java
https://tools.hmcts.net/jira/browse/NFDIV-2004
=> Update response due date to 16 days instead of 14 days

src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/SolAboutApplicant2.java
Reverts hmcts/nfdiv-case-api#1611
=> Revert "Hide applicant 2/respondent name changed question for joint applications"

src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerProgressPaperCase.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/ProgressPaperCase.java, src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerProgressPaperCaseTest.java
https://tools.hmcts.net/jira/browse/NFDIV-2018
=> Added awaiting HWF option to progress paper case

src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerAlternativeServiceApplication.java, src/main/java/uk/gov/hmcts/divorce/document/model/ConfidentialDocumentsReceived.java, src/main/java/uk/gov/hmcts/divorce/document/model/DocumentType.java
https://tools.hmcts.net/jira/browse/NFDIV-2029
As mentioned in title, add GeneralApplicationReceived state to the service application received event forStates.
```
[ ] Yes
[X] No
```
=> Add GeneralApplicationReceived state to list on service-application-received event

src/main/java/uk/gov/hmcts/divorce/caseworker/event/page/AmendCase.java
https://tools.hmcts.net/jira/browse/NFDIV-1802
=> Display marriage certificate names instead of first middle and last names

src/main/java/uk/gov/hmcts/divorce/common/notification/ApplicationIssuedNotification.java, src/test/java/uk/gov/hmcts/divorce/common/notification/ApplicationIssuedNotificationTest.java
- https://tools.hmcts.net/jira/browse/NFDIV-2037
- update the NoP notification to use issueDate +141 as response date, rather than +16
```
[ ] Yes
[X] No
```
=> nfdiv-2037: use correct response date

src/main/java/uk/gov/hmcts/divorce/systemupdate/event/SystemIssueAosDisputed.java, src/main/java/uk/gov/hmcts/divorce/systemupdate/event/SystemIssueAosUnDisputed.java
update states for aos disputed/undisputed events for NFDIV-1668
https://tools.hmcts.net/jira/browse/NFDIV-1668
=> update states for aos disputed/undisputed events

src/main/java/uk/gov/hmcts/divorce/caseworker/event/page/CorrectPaperCase.java
Add label for app2 prayer on correct paper case to clearly delineate between the two prayers on joint applications
https://tools.hmcts.net/jira/browse/NFDIV-1999
=> NFDIV-1999

src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/SolStatementOfTruth.java, src/test/java/uk/gov/hmcts/divorce/solicitor/event/page/SolStatementOfTruthTest.java
Add a check to ensure solicitor is not selecting personal service
https://tools.hmcts.net/jira/browse/NFDIV-2074
=> NFDIV-2074

src/main/java/uk/gov/hmcts/divorce/divorcecase/model/JurisdictionConnections.java
Update solicitor jurisdiction text
https://tools.hmcts.net/jira/browse/NFDIV-2052
=> Nfdiv-2052 Update solicitor jurisdiction text

src/main/java/uk/gov/hmcts/divorce/citizen/event/CitizenApplicant2UpdateApplication.java
remove history for joint patch case
https://tools.hmcts.net/jira/browse/NFDIV-2096
=> NFDIV-2096 remove history for joint patch

src/integrationTest/java/uk/gov/hmcts/divorce/document/content/NoticeOfProceedingContentIT.java, src/main/java/uk/gov/hmcts/divorce/document/content/NoticeOfProceedingContent.java
https://tools.hmcts.net/jira/browse/NFDIV-2089
=> NFDIV-2089: Add new content values for offline respondent NOP

Jenkinsfile_CNP, build.gradle
=> lets see if integration tests are faster with more threads

src/integrationTest/java/uk/gov/hmcts/divorce/caseworker/CaseworkerIssueApplicationIT.java, src/integrationTest/java/uk/gov/hmcts/divorce/caseworker/CaseworkerReIssueApplicationIT.java, src/integrationTest/resources/application.yaml, src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/NFDIV-2089
=> NFDIV-2089: Point at new version of offline doc

src/functionalTest/java/uk/gov/hmcts/divorce/solicitor/SubmitAosFT.java, src/integrationTest/java/uk/gov/hmcts/divorce/common/SubmitAosIT.java, src/main/java/uk/gov/hmcts/divorce/citizen/event/CitizenApplicant2UpdateApplication.java, src/main/java/uk/gov/hmcts/divorce/common/event/DraftAos.java, src/main/java/uk/gov/hmcts/divorce/common/event/SubmitAos.java, src/main/java/uk/gov/hmcts/divorce/common/service/task/SetSubmissionAndDueDate.java, src/main/java/uk/gov/hmcts/divorce/common/service/task/SetSubmitAosState.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/State.java, src/main/java/uk/gov/hmcts/divorce/systemupdate/event/SystemIssueAosDisputed.java, src/main/java/uk/gov/hmcts/divorce/systemupdate/event/SystemIssueAosUnDisputed.java, src/main/java/uk/gov/hmcts/divorce/systemupdate/event/SystemLinkApplicant2.java, src/test/java/uk/gov/hmcts/divorce/common/event/DraftAosTest.java, src/test/java/uk/gov/hmcts/divorce/common/service/task/SetSubmissionAndDueDateTest.java, src/test/java/uk/gov/hmcts/divorce/common/service/task/SetSubmitAosStateTest.java
reverting merged changes for NFDIV-1668 as there are bugs and issues related with it.
https://tools.hmcts.net/jira/browse/NFDIV-1668
=> revert NFDIV-1668 changes

src/integrationTest/java/uk/gov/hmcts/divorce/caseworker/CaseworkerIssueApplicationIT.java, src/integrationTest/java/uk/gov/hmcts/divorce/caseworker/CaseworkerReIssueApplicationIT.java, src/integrationTest/resources/caseworker-issue-joint-application-app1-represented-about-to-submit-response.json, src/integrationTest/resources/caseworker-issue-joint-application-app2-contact-private-about-to-submit-response.json, src/integrationTest/resources/caseworker-issue-joint-application-app2-represented-about-to-submit-response.json, src/integrationTest/resources/caseworker-reissue-joint-application-applicant1-solicitor-about-to-submit-response.json, src/integrationTest/resources/caseworker-reissue-joint-application-applicant2-solicitor-about-to-submit-response.json, src/main/java/uk/gov/hmcts/divorce/caseworker/service/print/AosPackPrinter.java, src/main/java/uk/gov/hmcts/divorce/caseworker/service/task/SendAosPackToRespondent.java, src/test/java/uk/gov/hmcts/divorce/caseworker/service/print/AosPackPrinterTest.java
Set up app2/respondent printing to be for all sole and joint cases with court service selected
https://tools.hmcts.net/jira/browse/NFDIV-2053
=> NFDIV-2053

src/integrationTest/java/uk/gov/hmcts/divorce/caseworker/CaseworkerIssueApplicationIT.java, src/integrationTest/java/uk/gov/hmcts/divorce/caseworker/CaseworkerReIssueApplicationIT.java, src/main/java/uk/gov/hmcts/divorce/caseworker/service/task/SendApplicationIssueNotifications.java, src/main/java/uk/gov/hmcts/divorce/common/notification/ApplicationIssuedNotification.java, src/test/java/uk/gov/hmcts/divorce/caseworker/service/task/SendApplicationIssueNotificationsTest.java, src/test/java/uk/gov/hmcts/divorce/common/notification/ApplicationIssuedNotificationTest.java
Fix perosnal service notifications for applicant and respondent
https://tools.hmcts.net/jira/browse/NFDIV-2099
=> Fix personal service reissue notifications

src/integrationTest/java/uk/gov/hmcts/divorce/caseworker/CaseworkerCreateGeneralOrderIT.java, src/integrationTest/java/uk/gov/hmcts/divorce/caseworker/CaseworkerIssueApplicationIT.java, src/integrationTest/java/uk/gov/hmcts/divorce/caseworker/CaseworkerReIssueApplicationIT.java, src/integrationTest/java/uk/gov/hmcts/divorce/document/content/NoticeOfProceedingContentIT.java, src/integrationTest/resources/application.yaml, src/main/java/uk/gov/hmcts/divorce/common/config/DocmosisTemplatesConfig.java, src/main/java/uk/gov/hmcts/divorce/document/content/NoticeOfProceedingContent.java, src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/NFDIV-2089
=> NFDIV-2089: Add content for v2 of R2 NOP

src/main/java/uk/gov/hmcts/divorce/divorcecase/model/JurisdictionConnections.java
Add missing bracket to jurisdiction text
=> Add missing bracket to jurisdiction text

src/main/java/uk/gov/hmcts/divorce/document/DocumentConstants.java
Rename pdf that is generated after app2 solicitor submits their answers on joint applications
https://tools.hmcts.net/jira/browse/NFDIV-1943
=> NFDIV-1943

src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerUploadDocument.java
Add delete permission to caseworker to allow them to delete as well as add documents on caseworker-upload-document event
https://tools.hmcts.net/jira/browse/NFDIV-2134
=> NFDIV-2134

src/integrationTest/java/uk/gov/hmcts/divorce/document/content/NoticeOfProceedingContentIT.java, src/main/java/uk/gov/hmcts/divorce/document/content/NoticeOfProceedingContent.java
https://tools.hmcts.net/jira/browse/NFDIV-2124
=> NFDIV-2124: Fix issues around respondent represented personal service content

src/main/java/uk/gov/hmcts/divorce/common/event/DraftAos.java
Allow Draft AOS to be triggered from AosOverdue state.
https://tools.hmcts.net/jira/browse/NFDIV-2182
=> Added aos overdue as prestate for draft aos

src/main/java/uk/gov/hmcts/divorce/divorcecase/model/Applicant.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/CaseData.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/Solicitor.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/access/CaseworkerWithCAAAccess.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/tab/CaseAccessAdministratorSearchTab.java, src/test/java/uk/gov/hmcts/divorce/divorcecase/model/access/CaseworkerAccessWithCAATest.java
https://tools.hmcts.net/jira/browse/NFDIV-2152
=> Added new fields to display on unassigned cases tab for CAA

src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerReissueApplication.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/State.java
https://tools.hmcts.net/jira/browse/NFDIV-1769
=> NFDIV-1769: Remove disputed state as not required

src/main/java/uk/gov/hmcts/divorce/caseworker/event/page/CorrectPaperCase.java
https://tools.hmcts.net/jira/browse/NFDIV-2154
=> Rearrange applicant 1 statement of truth questions

src/main/java/uk/gov/hmcts/divorce/document/model/DocumentType.java
https://tools.hmcts.net/jira/browse/NFDIV-1845
=> NFDIV-1845: Rename the marriage certificate in the UI

src/main/java/uk/gov/hmcts/divorce/divorcecase/model/access/CaseworkerWithCAAAccess.java, src/test/java/uk/gov/hmcts/divorce/divorcecase/model/access/CaseworkerAccessWithCAATest.java
=> Add creator CRU in CaseworkerWithCAAAccess

src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerIssueApplication.java, src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerReissueApplication.java
https://tools.hmcts.net/jira/browse/NFDIV-2091
=> NFDIV-2091: Add awaiting dwp response to pre states for issue and reissue

src/main/java/uk/gov/hmcts/divorce/divorcecase/model/access/CaseworkerWithCAAAccess.java, src/test/java/uk/gov/hmcts/divorce/divorcecase/model/access/CaseworkerAccessWithCAATest.java
=> Add more permissions to CaseworkerAccessWithCAA

build.gradle, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/Solicitor.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/access/CaseworkerWithCAAAccess.java, src/test/java/uk/gov/hmcts/divorce/divorcecase/model/access/CaseworkerAccessWithCAATest.java
Revert the explicit app2 permissions added to the CAA classes and upgrade the ccd-config-generator so that the permissions are inherited from the parent class
=> Access control changes

src/main/java/uk/gov/hmcts/divorce/divorcecase/model/State.java
The name is currently missing so it falls back to the long description
=> Add name for Draft state

src/main/java/uk/gov/hmcts/divorce/divorcecase/tab/ApplicationTab.java
https://tools.hmcts.net/jira/browse/NFDIV-2193
=> Show service method only for sole applications

src/integrationTest/java/uk/gov/hmcts/divorce/caseworker/CaseworkerOfflineDocumentVerifiedIT.java, src/integrationTest/resources/caseworker-offline-document-about-to-start-response.json, src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerOfflineDocumentVerified.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/CaseDocuments.java, src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerOfflineDocumentVerifiedTest.java
https://tools.hmcts.net/jira/browse/NFDIV-1718
=> Populate scanned document names for offline verified event

src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerReissueApplication.java
Retain value of service method as currently being set to null and causing incorrect NOP to be sent
https://tools.hmcts.net/jira/browse/NFDIV-2164
=> NFDIV-2164

build.gradle
Refer https://github.com/hmcts/nfdiv-case-api/pull/1813/files and https://github.com/hmcts/ccd-config-generator/pull/317
=> Bump config generator library to include scanned and delivery date format

src/main/java/uk/gov/hmcts/divorce/legaladvisor/event/LegalAdvisorMakeDecision.java
https://tools.hmcts.net/jira/browse/NFDIV-2230
=> NFDIV-2230: Add show condition for free text box on make decision event

build.gradle
Update Tomcat dependencies CVE-2022-29885
=> Update tomcat dependencies CVE-2022-29885

src/main/java/uk/gov/hmcts/divorce/common/event/page/ConditionalOrderReviewAoS.java
Remove heading when joint application for draft conditional order event
https://tools.hmcts.net/jira/browse/NFDIV-2268
=> Remove heading for joint draft conditional order event

src/main/java/uk/gov/hmcts/divorce/divorcecase/tab/CaseTypeTab.java
https://tools.hmcts.net/jira/browse/NFDIV-2306
=> NFDIV-2306: Use app1 and app2 solicitor roles for tabs

src/functionalTest/java/uk/gov/hmcts/divorce/testutil/FunctionalTestSuite.java, src/main/java/uk/gov/hmcts/divorce/document/content/PronouncementListTemplateContent.java, src/main/java/uk/gov/hmcts/divorce/systemupdate/schedule/SystemAlertApplicationNotReviewedTask.java, src/main/java/uk/gov/hmcts/divorce/systemupdate/schedule/SystemFinalOrderOverdueTask.java, src/main/java/uk/gov/hmcts/divorce/systemupdate/schedule/SystemNotifyApplicantDisputeFormOverdueTask.java, src/main/java/uk/gov/hmcts/divorce/systemupdate/schedule/SystemNotifyRespondentApplyFinalOrderTask.java, src/main/java/uk/gov/hmcts/divorce/systemupdate/schedule/SystemProgressCasesToAosOverdueTask.java, src/main/java/uk/gov/hmcts/divorce/systemupdate/schedule/SystemProgressCasesToAwaitingFinalOrderTask.java, src/main/java/uk/gov/hmcts/divorce/systemupdate/schedule/SystemProgressHeldCasesTask.java, src/main/java/uk/gov/hmcts/divorce/systemupdate/schedule/SystemRemindApplicant1ApplicationApprovedTask.java, src/main/java/uk/gov/hmcts/divorce/systemupdate/schedule/SystemRemindApplicant2Task.java, src/main/java/uk/gov/hmcts/divorce/systemupdate/schedule/SystemRemindApplicantsApplyForFinalOrderTask.java, src/main/java/uk/gov/hmcts/divorce/systemupdate/schedule/SystemRemindRespondentSolicitorToRespondTask.java, src/main/java/uk/gov/hmcts/divorce/systemupdate/schedule/conditionalorder/SystemRemindApplicantsApplyForCOrderTask.java, src/main/java/uk/gov/hmcts/divorce/systemupdate/service/CcdSearchService.java, src/test/java/uk/gov/hmcts/divorce/systemupdate/schedule/SystemAlertApplicationNotReviewedTaskTest.java, src/test/java/uk/gov/hmcts/divorce/systemupdate/schedule/SystemFinalOrderOverdueTaskTest.java, src/test/java/uk/gov/hmcts/divorce/systemupdate/schedule/SystemNotifyApplicantDisputeFormOverdueTaskTest.java, src/test/java/uk/gov/hmcts/divorce/systemupdate/schedule/SystemNotifyRespondentApplyFinalOrderTaskTest.java, src/test/java/uk/gov/hmcts/divorce/systemupdate/schedule/SystemProgressCasesToAosOverdueTaskTest.java, src/test/java/uk/gov/hmcts/divorce/systemupdate/schedule/SystemProgressCasesToAwaitingFinalOrderTaskTest.java, src/test/java/uk/gov/hmcts/divorce/systemupdate/schedule/SystemProgressHeldCasesTaskTest.java, src/test/java/uk/gov/hmcts/divorce/systemupdate/schedule/SystemRemindApplicant1ApplicationApprovedTaskTest.java, src/test/java/uk/gov/hmcts/divorce/systemupdate/schedule/SystemRemindApplicant2TaskTest.java, src/test/java/uk/gov/hmcts/divorce/systemupdate/schedule/SystemRemindApplicantsApplyForFinalOrderTaskTest.java, src/test/java/uk/gov/hmcts/divorce/systemupdate/schedule/SystemRemindRespondentSolicitorToRespondTaskTest.java, src/test/java/uk/gov/hmcts/divorce/systemupdate/schedule/conditionalorder/SystemRemindApplicantsApplyForCOrderTaskTest.java, src/test/java/uk/gov/hmcts/divorce/systemupdate/service/CcdSearchServiceTest.java
https://tools.hmcts.net/jira/browse/NFDIV-2248
=> NFDIV-2248: Update cron job for Aos overdue task and logging for multiple states

src/main/java/uk/gov/hmcts/divorce/divorcecase/tab/CaseTypeTab.java
Update show condition for CO tab as applicant 2 can potentially submit their conditional order before applicant 1 on joint cases
https://tools.hmcts.net/jira/browse/NFDIV-2306
=> NFDIV-2306

config/pmd/ruleset.xml, src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerUploadAmendedApplication.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/CaseDocuments.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/tab/CaseTypeTab.java, src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerUploadAmendedApplicationTest.java
https://tools.hmcts.net/jira/browse/NFDIV-1356
=> NFDIV-1356: Add new event to upload amended application

src/cftlib/java/uk/gov/hmcts/divorce/cftlib/CftLibConfig.java
=> Import bulk cases definition in cft lib

build.gradle
Reverts hmcts/nfdiv-case-api#1960
=> Revert "Bump hmcts.ccd.sdk from 3.0.2 to 3.0.3"

config/owasp/suppressions.xml
Add suppression for CVE-2022-22976 as it's a false positive
=> Add owasp suppression

src/integrationTest/java/uk/gov/hmcts/divorce/caseworker/CaseworkerIssueApplicationIT.java, src/integrationTest/java/uk/gov/hmcts/divorce/caseworker/CaseworkerReIssueApplicationIT.java, src/integrationTest/resources/application.yaml, src/main/resources/application.yaml
Reverts hmcts/nfdiv-case-api#1934
=> Revert "NFDIV-2274 - Update NoP document to get latest changes"

src/integrationTest/java/uk/gov/hmcts/divorce/caseworker/CaseworkerIssueApplicationIT.java, src/integrationTest/java/uk/gov/hmcts/divorce/caseworker/CaseworkerReIssueApplicationIT.java, src/integrationTest/resources/application.yaml, src/main/resources/application.yaml
Use V5 of document to get changes to fix a bug where marriage
content was present on a civil partnership NoP.
Update unit tests.
https://tools.hmcts.net/jira/browse/NFDIV-2274
=> NFDIV-2274 - use new v5 version of NoP sole respondent document.

src/main/java/uk/gov/hmcts/divorce/divorcecase/util/AddressUtil.java, src/test/java/uk/gov/hmcts/divorce/divorcecase/model/ApplicantTest.java
- Currently citizens are entering country as Great Britain which should not be treated as overseas.
https://tools.hmcts.net/jira/browse/NFDIV-2331
=> Treat Great Britain as non overseas address 

src/integrationTest/resources/application.yaml, src/main/resources/application.yaml
Add missing Welsh document template config 
=> Add missing config for welsh

src/main/java/uk/gov/hmcts/divorce/notification/CommonContent.java, src/test/java/uk/gov/hmcts/divorce/notification/CommonContentTest.java
Add common content methods to add Welsh partner content if applicant 1 or applicant 2 preferrs Welsh
=> Add common content methods for Welsh partner content

src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerAddNote.java, src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerGeneralEmail.java, src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerGeneralLetter.java, src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerRefund.java, src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerUploadAmendedApplication.java, src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerUploadConfidentialDocument.java, src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerUploadDocument.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/State.java, src/main/java/uk/gov/hmcts/divorce/systemupdate/event/SystemAttachScannedDocuments.java
Add events for withdrawn and rejected
https://tools.hmcts.net/jira/browse/NFDIV-2358
=> Nfdiv-2358 Add events for withdrawn and rejected

src/integrationTest/java/uk/gov/hmcts/divorce/bulkaction/service/PronouncementListDocServiceIT.java, src/integrationTest/resources/application.yaml, src/main/java/uk/gov/hmcts/divorce/document/content/DocmosisTemplateConstants.java, src/main/java/uk/gov/hmcts/divorce/document/content/PronouncementListTemplateContent.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/divorce/document/content/PronouncementListTemplateContentTest.java
Updates to Conditional Order pronouncement list document. 
Added Sole/Joint and application type columns to the case list.
https://tools.hmcts.net/jira/browse/NFDIV-1378
=> NFDIV-1378 : CO pronouncement list doc updated

src/main/java/uk/gov/hmcts/divorce/common/event/SubmitAos.java
https://tools.hmcts.net/jira/browse/NFDIV-2366
=> NFDIV-2366: Add AosOverdue as a valid pre-state for Submit AoS event

src/integrationTest/java/uk/gov/hmcts/divorce/caseworker/CaseworkerConfirmServicePaymentIT.java, src/integrationTest/java/uk/gov/hmcts/divorce/common/SubmitAosIT.java, src/main/java/uk/gov/hmcts/divorce/citizen/event/CitizenApplicant2UpdateApplication.java, src/main/java/uk/gov/hmcts/divorce/common/event/SubmitAos.java, src/main/java/uk/gov/hmcts/divorce/common/event/UpdateAos.java, src/main/java/uk/gov/hmcts/divorce/common/event/page/Applicant2SolStatementOfTruth.java, src/main/java/uk/gov/hmcts/divorce/common/service/task/SetSubmitAosState.java, src/test/java/uk/gov/hmcts/divorce/citizen/event/CitizenApplicant2UpdateApplicationTest.java, src/test/java/uk/gov/hmcts/divorce/common/service/task/SetSubmitAosStateTest.java
Set up pre state and post state for submit aos and update aos
https://tools.hmcts.net/jira/browse/NFDIV-2366
=> NFDIV-2366

.github/workflows/ccd-diff.yml, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/CaseData.java
=> Set up CCD diff tool

src/main/java/uk/gov/hmcts/divorce/common/event/SubmitAos.java
Add OfflineDocumentReceived to list valid pre-states for SubmitAos Event
https://tools.hmcts.net/jira/browse/NFDIV-2418
=> NFDIV-2418

src/integrationTest/java/uk/gov/hmcts/divorce/caseworker/CaseworkerIssueApplicationIT.java, src/integrationTest/java/uk/gov/hmcts/divorce/document/content/NoticeOfProceedingJointContentIT.java, src/integrationTest/resources/application.yaml, src/main/java/uk/gov/hmcts/divorce/document/content/NoticeOfProceedingJointContent.java, src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/NFDIV-2290
=> NFDIV-2290

src/integrationTest/java/uk/gov/hmcts/divorce/caseworker/CaseworkerIssueApplicationIT.java, src/integrationTest/java/uk/gov/hmcts/divorce/document/content/NoticeOfProceedingContentIT.java, src/integrationTest/java/uk/gov/hmcts/divorce/document/content/NoticeOfProceedingJointContentIT.java, src/integrationTest/resources/application.yaml, src/main/java/uk/gov/hmcts/divorce/caseworker/service/task/GenerateApplicant1NoticeOfProceeding.java, src/main/java/uk/gov/hmcts/divorce/caseworker/service/task/GenerateApplicant2NoticeOfProceedings.java, src/main/java/uk/gov/hmcts/divorce/document/content/DocmosisTemplateConstants.java, src/main/java/uk/gov/hmcts/divorce/document/content/NoticeOfProceedingContent.java, src/main/java/uk/gov/hmcts/divorce/document/content/NoticeOfProceedingsWithAddressContent.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/divorce/caseworker/service/task/GenerateApplicant1NoticeOfProceedingTest.java, src/test/java/uk/gov/hmcts/divorce/caseworker/service/task/GenerateApplicant2NoticeOfProceedingsTest.java
Add Welsh translation of NoP A1 document template
https://tools.hmcts.net/jira/browse/NFDIV-2281
=> Add NoP A1 document Welsh translation template

config/owasp/suppressions.xml
Suppress CVEs as there is no fixed version for tomcat-embed-core and tomcat-embed-websocket
=> Suppress tomcat CVEs

build.gradle, config/owasp/suppressions.xml, src/main/java/uk/gov/hmcts/divorce/common/service/task/SetApplicant2Email.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/CaseData.java, src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerNoticeOfChangeTest.java, src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerWithdrawnTest.java
Reduce CVE count
https://tools.hmcts.net/jira/browse/NFDIV-2359
=> Reduce CVEs

src/integrationTest/java/uk/gov/hmcts/divorce/caseworker/CaseworkerIssueBailiffPackIT.java, src/integrationTest/resources/application.yaml, src/main/resources/application.yaml
Add certificate of service Welsh translation
https://tools.hmcts.net/jira/browse/NFDIV-2263
=> Add certificate of service Welsh transaltion

src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerUpdateDueDate.java
https://tools.hmcts.net/jira/browse/NFDIV-2499
=> Configure update due date access for caseworkers

src/integrationTest/java/uk/gov/hmcts/divorce/document/content/GeneralOrderTemplateContentIT.java, src/main/java/uk/gov/hmcts/divorce/document/content/GeneralOrderTemplateContent.java
https://tools.hmcts.net/jira/browse/NFDIV-2497
Updated general order document text for Deputy District Judge. 
=> NFDIV-2497: updated document text

src/main/java/uk/gov/hmcts/divorce/divorcecase/tab/CaseTypeTab.java
https://github.com/hmcts/nfdiv-case-api/pull/2049
Opening a new pr to try to fix the build
=>  Nfdiv-2314 add cannot upload field to co outcome tab

src/main/java/uk/gov/hmcts/divorce/common/event/SubmitClarification.java, src/main/java/uk/gov/hmcts/divorce/legaladvisor/event/LegalAdvisorMakeDecision.java
- Should have been removed as part of https://github.com/hmcts/nfdiv-case-api/pull/2118
=> Remove aboutToStarts in LegalAdvisorMakeDecision and SubmitClarification

config/owasp/suppressions.xml
Suppress CVE-2022-31569, CVE-2020-11022, CVE-2020-11023
=> Suppress non updatable CVEs

src/integrationTest/java/uk/gov/hmcts/divorce/caseworker/CaseworkerRegenerateCourtOrdersIT.java, src/integrationTest/java/uk/gov/hmcts/divorce/systemupdate/event/SystemUpdateCaseWithCourtHearingIT.java, src/integrationTest/resources/application.yaml, src/integrationTest/resources/wiremock/responses/about-to-submit-system-regenerate-court-orders.json, src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerRegenerateCourtOrders.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/CaseDocuments.java, src/main/java/uk/gov/hmcts/divorce/document/content/ConditionalOrderPronouncedTemplateContent.java, src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerRegenerateCourtOrdersTest.java, src/test/java/uk/gov/hmcts/divorce/document/content/ConditionalOrderPronouncedTemplateContentTest.java
- Regenerate COE and CO granted docs if they exists on case for digital applications.
- Only available to super user to trigger from XUI.
https://tools.hmcts.net/jira/browse/NFDIV-1412
=> Regenerate court orders(Conditional Order granted and COE docs) for digital case

.github/workflows/ccd-diff.yml
=> Add explicit permissions to fix report on dependabot PRs

src/functionalTest/resources/request/casedata/ccd-callback-casedata-solicitor-submit-aos.json, src/functionalTest/resources/responses/response-solicitor-submit-aos.json, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/AcknowledgementOfService.java
Remove unused prayerHasBeenGiven field
=> Remove unused prayerHasBeenGiven field

src/integrationTest/java/uk/gov/hmcts/divorce/document/content/ServiceOrderTemplateContentIT.java, src/main/java/uk/gov/hmcts/divorce/document/content/ServiceOrderTemplateContent.java
Fix for due date NPE when LA making decision
=> Fix for due date NPE when LA making decision

src/functionalTest/java/uk/gov/hmcts/divorce/citizen/CitizenAddPaymentFT.java, src/integrationTest/java/uk/gov/hmcts/divorce/citizen/event/CitizenAddPaymentIT.java, src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerHwfApplicationAccepted.java, src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerPaymentMade.java, src/main/java/uk/gov/hmcts/divorce/citizen/event/CitizenAddPayment.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/Application.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/tab/ApplicationTab.java, src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerHwfApplicationAcceptedTest.java, src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerPaymentMadeTest.java, src/test/java/uk/gov/hmcts/divorce/citizen/event/CitizenAddPaymentTest.java
Changes to set state to Awaiting Applicants when applicant wants to serve papers to respondent
https://tools.hmcts.net/jira/browse/NFDIV-2185
=> NFDIV-2185 - V2 : Changes added

src/integrationTest/java/uk/gov/hmcts/divorce/common/SubmitConditionalOrderIT.java, src/integrationTest/resources/application.yaml, src/main/java/uk/gov/hmcts/divorce/document/content/ConditionalOrderAnswersTemplateContent.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/divorce/document/content/ConditionalOrderAnswersTemplateContentTest.java
reverted changes till the new template gets deployed to prod 
https://tools.hmcts.net/jira/browse/NFDIV-2549
=> NFDIV-2549: Reverted changes

src/functionalTest/resources/application.yaml, src/integrationTest/resources/application.yaml, src/main/java/uk/gov/hmcts/divorce/citizen/notification/conditionalorder/EntitlementGrantedConditionalOrderNotification.java, src/main/java/uk/gov/hmcts/divorce/common/notification/ConditionalOrderPronouncedNotification.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/divorce/citizen/notification/conditionalorder/EntitlementGrantedConditionalOrderNotificationTest.java, src/test/java/uk/gov/hmcts/divorce/common/notification/ConditionalOrderPronouncedNotificationTest.java
Fix respondent solicitor entitlement granted Conditional Order notification
Fix respondent solicitor Conditional Order pronounced notification
https://tools.hmcts.net/jira/browse/NFDIV-2613
=> Nfdiv 2613 fix solicitor notifications for conditional order

src/integrationTest/java/uk/gov/hmcts/divorce/common/GeneralApplicationReceivedNotificationIT.java, src/test/java/uk/gov/hmcts/divorce/citizen/notification/GeneralApplicationReceivedNotificationTest.java
Add general application received Welsh email translation
https://www.notifications.service.gov.uk/services/56f68e5c-b51f-4bdf-a0ac-d70af335e1d1/templates/1f4cd3f9-1092-4703-826c-0685131e6dff
https://tools.hmcts.net/jira/browse/NFDIV-1985
=> Add general application received Welsh email translation

src/main/java/uk/gov/hmcts/divorce/citizen/notification/conditionalorder/EntitlementGrantedConditionalOrderNotification.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/divorce/citizen/notification/conditionalorder/EntitlementGrantedConditionalOrderNotificationTest.java
- Fix for solicitor notification showing citizen URL (https://www.notifications.service.gov.uk/services/56f68e5c-b51f-4bdf-a0ac-d70af335e1d1/templates/351edcb3-5193-4883-9095-19ef6617fa8a)
https://tools.hmcts.net/jira/browse/NFDIV-2676
=> NFDIV-2676 - Solicitor notification showing citizen URL

src/main/java/uk/gov/hmcts/divorce/common/event/DraftAos.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/AcknowledgementOfService.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/tab/CaseTypeTab.java, src/test/java/uk/gov/hmcts/divorce/common/event/DraftAosTest.java
Add aosIsDrafted field and set when AoS Draft event is submitted
https://tools.hmcts.net/jira/browse/NFDIV-2492
=> Add aosIsDrafted field

src/main/java/uk/gov/hmcts/divorce/citizen/event/CitizenSwitchedToSole.java, src/test/java/uk/gov/hmcts/divorce/citizen/event/CitizenSwitchedToSoleTest.java
fix for a bug where if applicant2 wasnt linked and switch to sole event was called, it will throw an error trying to unlink a user which wasnt linked to case.
https://tools.hmcts.net/jira/browse/NFDIV-2677
=> Fix switch to sole

src/integrationTest/java/uk/gov/hmcts/divorce/systemupdate/event/SystemLinkApplicant2IT.java, src/integrationTest/resources/wiremock/responses/about-to-submit-link-applicant-2.json, src/main/java/uk/gov/hmcts/divorce/systemupdate/event/SystemLinkApplicant2.java, src/test/java/uk/gov/hmcts/divorce/systemupdate/event/SystemLinkApplicant2Test.java
set app2 offline to no on systemLinkApplicant2
https://tools.hmcts.net/jira/browse/NFDIV-2675
=> Nfdiv 2675 set app2 offline to no on system link applicant2

src/main/java/uk/gov/hmcts/divorce/divorcecase/tab/CaseTypeTab.java
Add additional field to language tab
https://tools.hmcts.net/jira/browse/NFDIV-2547
=> NFDIV-2547

src/functionalTest/java/uk/gov/hmcts/divorce/legaladvisor/LegalAdvisorMakeDecisionFT.java, src/functionalTest/resources/request/casedata/ccd-callback-casedata-legal-advisor-make-decision-offline-clarification.json, src/functionalTest/resources/responses/response-legal-advisor-make-decision-co-clarification-offline-joint.json, src/functionalTest/resources/responses/response-legal-advisor-make-decision-co-clarification-offline-sole.json, src/integrationTest/java/uk/gov/hmcts/divorce/document/content/ConditionalOrderOfflineClarificationContentIT.java, src/main/java/uk/gov/hmcts/divorce/document/DocumentConstants.java, src/main/java/uk/gov/hmcts/divorce/document/content/ConditionalOrderClarificationContent.java, src/main/java/uk/gov/hmcts/divorce/document/content/ConditionalOrderOfflineClarificationContent.java, src/main/java/uk/gov/hmcts/divorce/legaladvisor/event/LegalAdvisorMakeDecision.java, src/main/java/uk/gov/hmcts/divorce/legaladvisor/notification/LegalAdvisorMoreInfoDecisionNotification.java, src/main/java/uk/gov/hmcts/divorce/legaladvisor/service/printer/AwaitingClarificationApplicationPrinter.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/divorce/legaladvisor/event/LegalAdvisorMakeDecisionTest.java, src/test/java/uk/gov/hmcts/divorce/legaladvisor/notification/LegalAdvisorMoreInfoDecisionNotificationTest.java, src/test/java/uk/gov/hmcts/divorce/legaladvisor/service/printer/AwaitingClarificationApplicationPrinterTest.java
Add functionality to send clarification letter pack to offline applicants when a legal advisor make's a decision that more information (clarification) is required on their application.
https://tools.hmcts.net/jira/browse/NFDIV-1741
=> NFDIV-1741 - Send Awaiting Clarification letter pack to offline applicants when LA decision is MORE_INFO

Jenkinsfile_CNP, src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerRemoveDocument.java, src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerRemoveDocumentTest.java
https://tools.hmcts.net/jira/browse/NFDIV-2738
https://user-images.githubusercontent.com/13840402/186456243-95f17f3f-66fe-4066-84ae-3c8fe9bc4182.mp4
=> Added remove document for super users

src/main/resources/application.yaml
corrected template name in config
https://tools.hmcts.net/jira/browse/NFDIV-2483
=> NFDIV-2483 : corrected template name in config

src/main/java/uk/gov/hmcts/divorce/systemupdate/event/SystemCancelCaseInvite.java
https://tools.hmcts.net/jira/browse/NFDIV-2755
=> Update system cancel invite event prestate to include conditional order pending

charts/nfdiv-case-api/values.preview.template.yaml
=> revert to latest frontend image

src/main/java/uk/gov/hmcts/divorce/divorcecase/model/access/Applicant2Access.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/access/DefaultAccess.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/access/SystemUpdateAndSuperUserAccess.java, src/test/java/uk/gov/hmcts/divorce/divorcecase/model/access/Applicant2AccessTest.java, src/test/java/uk/gov/hmcts/divorce/divorcecase/model/access/DefaultAccessTest.java, src/test/java/uk/gov/hmcts/divorce/divorcecase/model/access/SystemUpdateAndSuperUserAccessTest.java
Add delete access rights to case documents fields for systemupdate role, to cover reordering of documents
https://tools.hmcts.net/jira/browse/NFDIV-2693
=> Add delete access rights to case document fields for systemupdate

src/functionalTest/resources/responses/response-caseworker-offline-document-verified-d84-about-to-submit.json, src/integrationTest/resources/caseworker-offline-document-verified-d84-response.json, src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerOfflineDocumentVerified.java
https://tools.hmcts.net/jira/browse/NFDIV-2701
=> NFDIV-2701: Reclassify D84 to the correct doc type

src/main/java/uk/gov/hmcts/divorce/common/event/DraftConditionalOrder.java, src/test/java/uk/gov/hmcts/divorce/common/event/DraftConditionalOrderTest.java
Update DraftConditionalOrder so that if applicant 2 is requesting the draft CO, then no applicant 1 information is altered -
This fixes the issue where applicant 2 submits a draft CO from the front end, making applicant 1 or applicant 1 solicitor unble to create a draft CO
https://tools.hmcts.net/jira/browse/NFDIV-2741
=> Fix app1 unable to draft CO after app2 has drafted

src/main/java/uk/gov/hmcts/divorce/common/event/DraftConditionalOrder.java, src/main/java/uk/gov/hmcts/divorce/common/event/SubmitConditionalOrder.java, src/test/java/uk/gov/hmcts/divorce/common/event/DraftConditionalOrderTest.java, src/test/java/uk/gov/hmcts/divorce/common/event/SubmitConditionalOrderTest.java
Clean up submit CO event and fix validation
https://tools.hmcts.net/jira/browse/NFDIV-2741
=> NFDIV-2741 Clean up submit CO event and fix validation

build.gradle, src/cftlib/java/uk/gov/hmcts/divorce/cftlib/CftLibConfig.java
Load the JSON definition directly (without generating the XLSX) when spinning up the development environment
=> Load JSON definition directly

src/main/java/uk/gov/hmcts/divorce/divorcecase/model/State.java
=> Allow AwaitingApplicant2Response as pre state for return to previous state

src/main/java/uk/gov/hmcts/divorce/divorcecase/model/State.java
Reverts hmcts/nfdiv-case-api#2366
=> Revert "Allow AwaitingApplicant2Response as pre state for return to previous state"

src/main/java/uk/gov/hmcts/divorce/document/content/DocmosisCommonContent.java, src/main/java/uk/gov/hmcts/divorce/document/content/DocmosisTemplateConstants.java, src/test/java/uk/gov/hmcts/divorce/document/content/DocmosisCommonContentTest.java
Add class to set common content for docmosis templates
=> Add class to set common content for docmosis templates

src/main/java/uk/gov/hmcts/divorce/document/content/DocmosisCommonContent.java, src/test/java/uk/gov/hmcts/divorce/document/content/DocmosisCommonContentTest.java
Header added to docmosis common content.
https://tools.hmcts.net/jira/browse/NFDIV-2574
=> Add header content to docmosis common content

src/main/java/uk/gov/hmcts/divorce/document/content/DocmosisTemplateConstants.java
Fix welsh phone number and opening times
=> Fix welsh phone number and opening times

src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerReissueApplication.java
This reverts commit 0b156f52339710789b24f1eb94da80dd62530510.
=> Revert "Change Reissue show condition (#2357)"

src/main/java/uk/gov/hmcts/divorce/systemupdate/event/SystemUpdateCaseWithCourtHearing.java
https://tools.hmcts.net/jira/browse/NFDIV-2868
=> Include offline document verified as prestate to allow updating court details

src/main/java/uk/gov/hmcts/divorce/bulkaction/ccd/event/CaseworkerEditBulkCase.java, src/main/java/uk/gov/hmcts/divorce/bulkaction/ccd/event/CaseworkerPrintPronouncement.java, src/main/java/uk/gov/hmcts/divorce/bulkaction/ccd/event/CaseworkerPronounceList.java, src/main/java/uk/gov/hmcts/divorce/bulkaction/ccd/event/CaseworkerRemoveCasesFromBulkList.java, src/main/java/uk/gov/hmcts/divorce/bulkaction/ccd/event/CaseworkerScheduleCase.java
Add logging to bulk action event callbacks
https://tools.hmcts.net/jira/browse/NFDIV-2926
=> Add logging to bulk action event callbacks

src/test/java/uk/gov/hmcts/divorce/testutil/TestDataHelper.java
Adding for testing.
https://tools.hmcts.net/jira/browse/NFDIV-2577
=> Add method to generate basic docmosis template content for testing

src/main/java/uk/gov/hmcts/divorce/systemupdate/event/SystemPronounceCase.java
https://tools.hmcts.net/jira/browse/NFDIV-3044
=> Added offline document verified as prestate for system pronounce case

src/main/java/uk/gov/hmcts/divorce/systemupdate/schedule/SystemAlertApplicationNotReviewedTask.java, src/main/java/uk/gov/hmcts/divorce/systemupdate/schedule/SystemProgressCasesToAosOverdueTask.java, src/main/java/uk/gov/hmcts/divorce/systemupdate/schedule/conditionalorder/SystemRemindApplicantsApplyForCOrderTask.java
Add logging of case state to system cron tasks
https://tools.hmcts.net/jira/browse/NFDIV-3066
=> Add logging of state to system cron tasks

src/main/java/uk/gov/hmcts/divorce/systemupdate/schedule/migration/SetAosIsDraftedToYesMigration.java, src/test/java/uk/gov/hmcts/divorce/systemupdate/schedule/migration/SetAosIsDraftedToYesMigrationTest.java
Add more logging to SetAosIsDraftedToYesMigration
Narrow the search criteria for SetAosIsDraftedToYesMigration - it looks like the migration is starting but not completing.
https://tools.hmcts.net/jira/browse/NFDIV-2829
=> Add logging and narrow search aosisdrafted migration

src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerAwaitingAmendedApplication.java, src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerAwaitingAmendedApplicationTest.java
Create new Caseworker Awaiting Amended Application event
https://tools.hmcts.net/jira/browse/NFDIV-1362
=> NFDIV-1362

src/main/resources/data/joint.json
=> Update solicitors email

build.gradle
https://github.com/hmcts/nfdiv-case-api/pull/2530
https://github.com/hmcts/nfdiv-case-api/pull/2529
https://github.com/hmcts/nfdiv-case-api/pull/2528
https://github.com/hmcts/nfdiv-case-api/pull/2526
https://github.com/hmcts/nfdiv-case-api/pull/2525
https://github.com/hmcts/nfdiv-case-api/pull/2524
https://github.com/hmcts/nfdiv-case-api/pull/2513
https://github.com/hmcts/nfdiv-case-api/pull/2500
=> Combine dependency upgrade prs into single pr to reduce effort of merging and rebasing

src/main/java/uk/gov/hmcts/divorce/systemupdate/schedule/migration/SetAosIsDraftedToYesMigration.java, src/test/java/uk/gov/hmcts/divorce/systemupdate/schedule/migration/SetAosIsDraftedToYesMigrationTest.java
Change query to search for references given by environment variable so that aos is drafted migration targets specific cases.
Example:
AOS_IS_DRAFTED_REFERENCES=1663667452138441,1663669164915603,1666090230608688
https://tools.hmcts.net/jira/browse/NFDIV-2829
=> Migrate aos is drafted using list of references query

build.gradle
Fix issue where the launch darkly dependency was failing to be downloaded from jcenter
=> Fix build issue with launch darkly downloading from jcenter

build.gradle, config/owasp/suppressions.xml
Fix CVE and suppress CVEs with no current fixes
N/A
=> Fix CVE and suppress CVEs with no current fixes

src/main/java/uk/gov/hmcts/divorce/systemupdate/event/SystemMigrateCaseWithCoEGeneration.java
Fix issue where CoE was not generated when migrating court hearing in case linked to bulk action case
https://tools.hmcts.net/jira/browse/NFDIV-3125
=> Fix CoE generation when migrating court hearing

build.gradle, src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerGrantFinalOrder.java, src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerUpdateOfflineStatus.java, src/main/java/uk/gov/hmcts/divorce/caseworker/service/print/AosPackPrinter.java, src/main/java/uk/gov/hmcts/divorce/caseworker/service/task/GenerateApplicant2NoticeOfProceedings.java, src/main/java/uk/gov/hmcts/divorce/caseworker/service/task/GenerateD10Form.java, src/main/java/uk/gov/hmcts/divorce/caseworker/service/task/SendAosResponseLetterPackToApplicant.java, src/main/java/uk/gov/hmcts/divorce/common/service/task/GenerateAosResponseLetterDocument.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/Applicant.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/validation/ValidationUtil.java, src/main/java/uk/gov/hmcts/divorce/document/content/ConditionalOrderRefusedForAmendmentContent.java, src/main/java/uk/gov/hmcts/divorce/document/content/NoticeOfProceedingContent.java, src/main/java/uk/gov/hmcts/divorce/document/content/NoticeOfProceedingJointContent.java, src/main/java/uk/gov/hmcts/divorce/notification/NotificationDispatcher.java, src/main/java/uk/gov/hmcts/divorce/systemupdate/event/SystemProgressCaseToAosOverdue.java, src/main/java/uk/gov/hmcts/divorce/systemupdate/event/SystemProgressCaseToAwaitingFinalOrder.java, src/main/java/uk/gov/hmcts/divorce/systemupdate/service/task/GenerateConditionalOrderPronouncedCoversheet.java, src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerNoticeOfChangeTest.java, src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerOfflineDocumentVerifiedTest.java, src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerUpdateOfflineStatusTest.java, src/test/java/uk/gov/hmcts/divorce/common/event/SubmitConditionalOrderTest.java, src/test/java/uk/gov/hmcts/divorce/divorcecase/model/ApplicantTest.java, src/test/java/uk/gov/hmcts/divorce/notification/NotificationDispatcherTest.java
Update offline check for app2 and add event to update offline flag
https://tools.hmcts.net/jira/browse/NFDIV-3140
=> NFDIV-3140

src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerUpdateFinalOrderFields.java
https://tools.hmcts.net/jira/browse/NFDIV-3174
=> Remove date final order eligible from update fo event

src/main/java/uk/gov/hmcts/divorce/bulkaction/service/CasePronouncementService.java, src/test/java/uk/gov/hmcts/divorce/bulkaction/service/CasePronouncementServiceTest.java
Fix bulkcase failing to update after pronouncing cases
https://tools.hmcts.net/jira/browse/NFDIV-3164
=> Fix failing to update bulkcase after pronouncing cases

src/main/java/uk/gov/hmcts/divorce/common/event/DraftAos.java, src/main/java/uk/gov/hmcts/divorce/common/event/SubmitAos.java
Add show condition for aosIsDrafted to Draft AoS and Submit AoS events
https://tools.hmcts.net/jira/browse/NFDIV-2492
=> Add aosIsDrafted show condition to DraftAos and SubmitAos

src/main/java/uk/gov/hmcts/divorce/divorcecase/model/State.java
https://tools.hmcts.net/jira/browse/NFDIV-3188
=> NFDIV-3188 : Make AwaitingService state accessible for CAA to assign cases to solicitors

src/main/java/uk/gov/hmcts/divorce/systemupdate/event/SystemAttachScannedDocuments.java, src/test/java/uk/gov/hmcts/divorce/systemupdate/event/SystemAttachScannedDocumentsTest.java
https://tools.hmcts.net/jira/browse/NFDIV-3199
=> Skip subtype reclassification

src/cftlibTest/java/uk/gov/hmcts/divorce/cftlib/SoleApplicationCreateAndIssueTest.java
Fix failing cftLib Test SoleApplicationCreateAndIssueTest by updating locator
=> Fix SoleApplicationCreateAndIssueTest

src/integrationTest/java/uk/gov/hmcts/divorce/solicitor/Applicant2SolicitorSwitchToSoleFoIT.java, src/integrationTest/resources/solicitor-applicant2-switch-to-sole-fo-response.json, src/main/java/uk/gov/hmcts/divorce/common/event/SwitchedToSoleFinalOrder.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/FinalOrder.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/Applicant1SolicitorSwitchToSoleFo.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/Applicant2SolicitorSwitchToSoleFo.java
Add pages for solicitors to switch to sole at Final Order stage
https://tools.hmcts.net/jira/browse/NFDIV-2765
=> NFDIV-2765

src/main/java/uk/gov/hmcts/divorce/systemupdate/service/CcdSearchService.java, src/test/java/uk/gov/hmcts/divorce/systemupdate/service/CcdSearchServiceTest.java
Remove possibility of case being linked to two bulk cases
https://tools.hmcts.net/jira/browse/NFDIV-3191
=> Nfdiv 3191 fix cases linked to two bulk cases v2

src/integrationTest/java/uk/gov/hmcts/divorce/testutil/DocumentUploadDFormsMocker.java
https://tools.hmcts.net/jira/browse/NFDIV-3217
=> NFDIV-3217: added IT Dforms utility

src/main/java/uk/gov/hmcts/divorce/common/event/Applicant2ApplyForFinalOrder.java, src/main/java/uk/gov/hmcts/divorce/common/event/ApplyForFinalOrder.java
Stop solicitors submitting twice.
https://tools.hmcts.net/jira/browse/NFDIV-3207
=> NFDIV-3207 - Add show conditions for Apply for final order events

src/main/java/uk/gov/hmcts/divorce/bulkaction/service/CasePronouncementService.java, src/main/java/uk/gov/hmcts/divorce/bulkaction/service/filter/CaseProcessingStateFilter.java
Add extra logging to pronounce bulk case to trace production issue
https://tools.hmcts.net/jira/browse/NFDIV-3230
=> Add extra logging to trace pronounce cases

src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerHWFPartPaymentMade.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/State.java, src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerHWFPartPaymentMadeTest.java
New event to allow caseworkers to record a part payment with HWF.
https://tools.hmcts.net/jira/browse/NFDIV-1116
=> NFDIV-1116 - Caseworker HWF Part Payment Made event

Jenkinsfile_CNP
Move away from depreciated after() call to afterAlways() call
N/A
=> Move away from depreciated after() call to afterAlways() call

src/main/java/uk/gov/hmcts/divorce/systemupdate/schedule/migration/CreateDoubleLinkedCasesListMigration.java, src/main/java/uk/gov/hmcts/divorce/systemupdate/service/CcdSearchService.java, src/test/java/uk/gov/hmcts/divorce/systemupdate/schedule/migration/CreateDoubleLinkedCasesListMigrationTest.java
Log list of all cases double linked to bulk cases
https://tools.hmcts.net/jira/browse/NFDIV-3214
=> Log list of all double linked case to bulk case

src/main/java/uk/gov/hmcts/divorce/systemupdate/schedule/migration/CreateDoubleLinkedCasesListMigration.java, src/test/java/uk/gov/hmcts/divorce/systemupdate/schedule/migration/CreateDoubleLinkedCasesListMigrationTest.java
Fix create double linked cases list exception
https://tools.hmcts.net/jira/browse/NFDIV-3214
=> Fix create double linked cases list exception

src/main/java/uk/gov/hmcts/divorce/bulkaction/ccd/event/CaseworkerRetryPronounceList.java, src/main/java/uk/gov/hmcts/divorce/bulkaction/service/CasePronouncementService.java, src/main/java/uk/gov/hmcts/divorce/bulkaction/service/filter/CaseProcessingStateFilter.java, src/main/java/uk/gov/hmcts/divorce/bulkaction/task/PronounceCaseProvider.java, src/main/java/uk/gov/hmcts/divorce/systemupdate/event/SystemPronounceCase.java, src/test/java/uk/gov/hmcts/divorce/bulkaction/ccd/event/CaseworkerRetryPronounceListTest.java, src/test/java/uk/gov/hmcts/divorce/bulkaction/service/CasePronouncementServiceTest.java, src/test/java/uk/gov/hmcts/divorce/bulkaction/service/filter/CaseProcessingStateFilterTest.java, src/test/java/uk/gov/hmcts/divorce/bulkaction/task/PronounceCaseProviderTest.java
https://tools.hmcts.net/jira/browse/NFDIV-3205
=> Make pronouncement judge editable in retry pronouncement list for super users

src/integrationTest/java/uk/gov/hmcts/divorce/caseworker/CaseworkerIssueApplicationIT.java, src/integrationTest/java/uk/gov/hmcts/divorce/caseworker/CaseworkerReIssueApplicationIT.java, src/main/java/uk/gov/hmcts/divorce/caseworker/service/task/SendAosPackToRespondent.java, src/main/java/uk/gov/hmcts/divorce/caseworker/service/task/SetServiceType.java, src/test/java/uk/gov/hmcts/divorce/caseworker/service/task/SendAosPackToRespondentTest.java
Service type was set to Personal Service if applicant1 did not know the address of applicant2. This needs to be changed as there is no way for applicant1 to serve applicatn2 if they don't know the address.
https://tools.hmcts.net/jira/browse/NFDIV-3223
=> NFDIV-3223: Fix issue with service type setting

src/integrationTest/java/uk/gov/hmcts/divorce/caseworker/CaseworkerCreateGeneralOrderIT.java, src/integrationTest/java/uk/gov/hmcts/divorce/caseworker/CaseworkerIssueApplicationIT.java, src/integrationTest/java/uk/gov/hmcts/divorce/caseworker/CaseworkerReIssueApplicationIT.java, src/integrationTest/java/uk/gov/hmcts/divorce/document/content/ConditionalOrderRefusedForClarificationContentIT.java, src/integrationTest/java/uk/gov/hmcts/divorce/document/content/GeneralOrderTemplateContentIT.java, src/integrationTest/java/uk/gov/hmcts/divorce/document/content/NoticeOfProceedingContentIT.java, src/integrationTest/java/uk/gov/hmcts/divorce/document/content/NoticeOfProceedingJointContentIT.java, src/integrationTest/java/uk/gov/hmcts/divorce/document/content/ServiceOrderTemplateContentIT.java, src/integrationTest/resources/application.yaml, src/main/java/uk/gov/hmcts/divorce/caseworker/service/task/GenerateGeneralLetter.java, src/main/java/uk/gov/hmcts/divorce/document/content/ConditionalOrderRefusedForClarificationContent.java, src/main/java/uk/gov/hmcts/divorce/document/content/DocmosisCommonContent.java, src/main/java/uk/gov/hmcts/divorce/document/content/DocmosisTemplateConstants.java, src/main/java/uk/gov/hmcts/divorce/document/content/GeneralLetterTemplateContent.java, src/main/java/uk/gov/hmcts/divorce/document/content/GeneralOrderTemplateContent.java, src/main/java/uk/gov/hmcts/divorce/document/content/NoticeOfProceedingContent.java, src/main/java/uk/gov/hmcts/divorce/document/content/NoticeOfProceedingJointContent.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/divorce/caseworker/service/task/GenerateGeneralLetterTest.java, src/test/java/uk/gov/hmcts/divorce/document/content/ConditionalOrderRefusedForClarificationContentTest.java, src/test/java/uk/gov/hmcts/divorce/document/content/GeneralLetterTemplateContentTest.java, src/test/java/uk/gov/hmcts/divorce/document/content/GeneralOrderTemplateContentTest.java, src/test/java/uk/gov/hmcts/divorce/document/content/NoticeOfProceedingContentTest.java, src/test/java/uk/gov/hmcts/divorce/testutil/TestDataHelper.java
Change description
Add common header and footer and update template versions
Added new method in TestDataHelper class to assert ctscContactDetails and have updated email address
JIRA link (if applicable)
https://tools.hmcts.net/jira/browse/NFDIV-3118
Before merging a pull request make sure that:
README and other documentation has been updated / added (if needed)
If this ticket will have any visible impact on users and is not behind a feature toggle, make sure that:
this ticket been reviewed by QA
the user story been signed off by the PO
=> NFDIV-3118: Add common header and footer and update template versions

src/main/java/uk/gov/hmcts/divorce/solicitor/service/CcdAccessService.java, src/test/java/uk/gov/hmcts/divorce/solicitor/service/CcdAccessServiceTest.java
https://tools.hmcts.net/jira/browse/NFDIV-2824
=> NFDIV-2824: debugging existing

config/owasp/suppressions.xml
Suppress CVE-2021-4277 - No fix available yet
N/A
=> Suppress CVE-2021-4277 - No fix available yet

build.gradle
Bump tomcat-embed-core version to fix cve
N/A
=> Bump tomcat-embed-core version to fix cve

src/functionalTest/java/uk/gov/hmcts/divorce/systemupdate/event/SystemProgressCaseToAosOverdueFT.java, src/integrationTest/java/uk/gov/hmcts/divorce/systemupdate/event/SystemProgressCaseToAosOverdueIT.java, src/integrationTest/resources/application.yaml, src/integrationTest/resources/wiremock/responses/about-to-submit-system-progress-case-to-aos-overdue-offline-js.json, src/main/java/uk/gov/hmcts/divorce/common/service/task/GenerateAosOverdueLetterDocument.java, src/main/java/uk/gov/hmcts/divorce/document/DocumentConstants.java, src/main/java/uk/gov/hmcts/divorce/document/content/AosOverdueLetterTemplateContent.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/divorce/common/service/task/GenerateAosOverdueLetterDocumentTest.java, src/test/java/uk/gov/hmcts/divorce/document/content/AosOverdueLetterTemplateContentTest.java
AOS overdue doc changes for Judicial Separation
https://tools.hmcts.net/jira/browse/NFDIV-2902
=> NFDIV-2902: AOS overdue doc changes for Judicial Separation

src/functionalTest/java/uk/gov/hmcts/divorce/systemupdate/event/SystemPronounceCaseFT.java, src/main/java/uk/gov/hmcts/divorce/document/DocumentConstants.java, src/main/java/uk/gov/hmcts/divorce/systemupdate/service/task/ConditionalOrderPronouncedCoverLetterHelper.java, src/main/java/uk/gov/hmcts/divorce/systemupdate/service/task/GenerateConditionalOrderPronouncedDocument.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/divorce/systemupdate/service/task/ConditionalOrderPronouncedCoverLetterHelperTest.java, src/test/java/uk/gov/hmcts/divorce/systemupdate/service/task/GenerateConditionalOrderPronouncedDocumentTest.java
changes for JS CO pronounced doc and cover letter 
https://tools.hmcts.net/jira/browse/NFDIV-2918
=> NFDIV-2918: changes for JS CO pronounced doc and cover letter 

src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerOfflineDocumentVerified.java
https://tools.hmcts.net/jira/browse/NFDIV-3198
=> Update condition to display who is submitting only for switch to sole option

src/main/java/uk/gov/hmcts/divorce/divorcecase/model/State.java, src/main/java/uk/gov/hmcts/divorce/legaladvisor/event/LegalAdvisorMakeDecision.java, src/main/java/uk/gov/hmcts/divorce/legaladvisor/event/LegalAdvisorReview.java, src/test/java/uk/gov/hmcts/divorce/legaladvisor/event/LegalAdvisorReviewTest.java
https://tools.hmcts.net/jira/browse/NFDIV-3166
=> NFDIV-3166 Legal Advisor Review

charts/nfdiv-case-api/Chart.yaml
=> Bump java chart to latest

src/integrationTest/java/uk/gov/hmcts/divorce/document/content/ConditionalOrderRefusedForClarificationContentIT.java, src/main/java/uk/gov/hmcts/divorce/common/service/task/SetSubmitAosState.java, src/main/java/uk/gov/hmcts/divorce/document/content/ConditionalOrderRefusedForClarificationContent.java
Fix NPE issue where isJudicialSeparation is null
https://tools.hmcts.net/jira/browse/NFDIV-3281
=> Fix NPE issue with JS

.github/renovate.json
Add terraform to manager to auto get update PRs
N/A
=> Add terraform to manager to auto get update PRs

src/main/java/uk/gov/hmcts/divorce/systemupdate/schedule/bulkaction/SystemCreateBulkCaseListTask.java
To help us debug the create bulk cases cron, we're adding a better log message.
=> Nfdiv add logging bulk cases cron

src/main/java/uk/gov/hmcts/divorce/divorcecase/tab/CaseTypeTab.java
https://tools.hmcts.net/jira/browse/NFDIV-3307
Add AwaitingGeneralConsideration to FinalOrderTab show conditions
=> NFDiv-3307 FO tab not visible after general referral

src/main/java/uk/gov/hmcts/divorce/divorcecase/tab/CaseTypeTab.java
NFDIV-3041: Add new state for final order tab
https://tools.hmcts.net/jira/browse/NFDIV-3041
=> NFDIV-3041: Add new state for final order tab

src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerOfflineDocumentVerified.java, src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerOfflineDocumentVerifiedTest.java
Add parentheses in the correct place for conditionals
https://tools.hmcts.net/jira/browse/NFDIV-3308
=> NFDIV-3308: Add parentheses in the correct place for conditionals

src/main/java/uk/gov/hmcts/divorce/caseworker/event/page/CorrectRelationshipDetails.java
https://tools.hmcts.net/jira/browse/NFDIV-3297
Change 'Divorce or dissolution?' label text on Correct Relationship Details form (displayed during Correct Paper Case event).
=> NFDiv-3297 Update label text

config/owasp/suppressions.xml
https://cve.report/CVE-2022-45688
=> Add suppression for CVE-2022-45688

Jenkinsfile_CNP
Fix outdated .internal preview URL for jenkins
=> Fix outdated .internal preview URL for jenkins

.github/PULL_REQUEST_TEMPLATE.md, build.gradle
Update PR template after dev discussions
=> Update PR template after dev discussions

.github/renovate.json, Dockerfile, config/owasp/suppressions.xml
Update app insights to 3.4.10 per https://tools.hmcts.net/jira/browse/DTSPO-13217
=> Update app insights to 3.4.10

src/main/java/uk/gov/hmcts/divorce/citizen/event/CitizenSubmitApplication.java, src/main/java/uk/gov/hmcts/divorce/common/event/SubmitAos.java
=> Testing code deployment in production

config/owasp/suppressions.xml
CVE-2023-20860 will be resolved by upgrading Spring, which will be handled as tech debt asap.
=> Temporary suppression for CVE-2023-20860

src/main/java/uk/gov/hmcts/divorce/divorcecase/model/CaseData.java
In production we are seeing cases fail to submit due to missing field which was deleted by mistake. Adding it back.
N/A
=> Add field which was removed as it exists in case data in production

src/main/java/uk/gov/hmcts/divorce/bulkaction/ccd/event/SuperuserRemoveCaseFromBulkList.java
Event needs to be hidden as it's use case is resolved.
https://tools.hmcts.net/jira/browse/NFDIV-3412
=> Hide event in production

build.gradle
https://github.com/hmcts/nfdiv-case-api/pull/2936
=> Revert incorrect dep upgrade

src/main/java/uk/gov/hmcts/divorce/divorcecase/model/State.java
Need to move case back to general referral
=> Remove AwaitingPronouncement from banned states as needed

src/integrationTest/java/uk/gov/hmcts/divorce/caseworker/CaseworkerRegenerateCourtOrdersIT.java, src/integrationTest/java/uk/gov/hmcts/divorce/systemupdate/event/SystemUpdateCaseWithCourtHearingIT.java, src/integrationTest/resources/application.yaml, src/main/java/uk/gov/hmcts/divorce/document/content/CertificateOfEntitlementContent.java, src/main/java/uk/gov/hmcts/divorce/document/content/DocmosisTemplateConstants.java, src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/NFDIV-3471
=> NFDiv-3471 Certificate of Entitlement Order - Add dynamic content for [judicial]

src/main/java/uk/gov/hmcts/divorce/systemupdate/service/task/GenerateCertificateOfEntitlement.java
https://tools.hmcts.net/jira/browse/NFDIV-3449
=> NFDiv-3449 Add missing Pertner var to joint JS content generation

Jenkinsfile_CNP, build.gradle, config/owasp/suppressions.xml
We removed the syncing of demo due to JS being taken for testing.
Now that JS is done we can re-sync with master.
P.S cnp-flux-config PR to come to re-enable prod image.
=> Sync demo with master now that JS is complete in demo env

src/integrationTest/resources/application.yaml, src/main/resources/application.yaml
Shouldn't have been updated. Only ENG needed V3 change.
https://tools.hmcts.net/jira/browse/NFDIV-3285
=> NFDIV-3285 - undo accidental update of welsh doc

src/main/java/uk/gov/hmcts/divorce/systemupdate/event/SystemRemoveBulkCase.java
Case in rejected can't be removed from bulk case due to 422 error on allowed states.
=> Allow cases rejected and withdrawn to be removed from bulk cases

src/main/java/uk/gov/hmcts/divorce/common/notification/ServiceApplicationNotification.java, src/test/java/uk/gov/hmcts/divorce/common/notification/ServiceApplicationNotificationTest.java
Prevent NPE
https://tools.hmcts.net/jira/browse/NFDIV-3607
=> NFDIV-3607: Prevent NPE

src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerGeneralReferral.java, src/main/java/uk/gov/hmcts/divorce/common/event/Applicant2ApplyForFinalOrder.java, src/main/java/uk/gov/hmcts/divorce/common/event/ApplyForFinalOrder.java, src/main/java/uk/gov/hmcts/divorce/common/service/GeneralReferralService.java, src/main/java/uk/gov/hmcts/divorce/common/service/task/SetGeneralReferralDetails.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/FinalOrder.java, src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerGeneralReferralTest.java, src/test/java/uk/gov/hmcts/divorce/common/event/Applicant2ApplyForFinalOrderTest.java, src/test/java/uk/gov/hmcts/divorce/common/event/ApplyForFinalOrderTest.java, src/test/java/uk/gov/hmcts/divorce/common/service/GeneralReferralServiceTest.java, src/test/java/uk/gov/hmcts/divorce/common/service/task/SetGeneralReferralDetailsTest.java, src/test/java/uk/gov/hmcts/divorce/divorcecase/model/FinalOrderTest.java
final order overdue state progression
https://tools.hmcts.net/jira/browse/NFDIV-3580
=> Nfdiv 3580 final order overdue state progression

src/integrationTest/java/uk/gov/hmcts/divorce/endpoint/ValidationControllerIT.java, src/main/java/uk/gov/hmcts/divorce/bulkscan/validation/OcrValidator.java, src/main/java/uk/gov/hmcts/divorce/endpoint/ValidationController.java, src/main/java/uk/gov/hmcts/divorce/endpoint/data/OcrDataValidationRequest.java
Prevent 400 errors in appinsights from validate-ocr endpoint
https://tools.hmcts.net/jira/browse/NFDIV-3593
=> NFDIV-3593: Prevent 400 errors in appinsights from validate-ocr endpoint

src/main/java/uk/gov/hmcts/divorce/divorcecase/model/FinalOrder.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/tab/CaseTypeTab.java
https://tools.hmcts.net/jira/browse/NFDIV-1621
=> add app2 sot field and show answers in fo tab.

src/main/java/uk/gov/hmcts/divorce/idam/IdamService.java
Ensure that getCachedIdamOauth2Token is used for preview and local envs where CLUSTER_NAME is not set
(https://tools.hmcts.net/jira/browse/NFDIV-3620)
=> Fix 429 errors in preview and local envs

README.md, src/main/java/uk/gov/hmcts/divorce/common/event/page/Applicant2FinalOrderExplainTheDelay.java, src/main/java/uk/gov/hmcts/divorce/common/event/page/FinalOrderExplainTheDelay.java
=> Fix Sot labels

src/functionalTest/resources/application.yaml, src/integrationTest/resources/application.yaml, src/main/java/uk/gov/hmcts/divorce/systemupdate/event/SystemAttachScannedDocuments.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/divorce/systemupdate/event/SystemAttachScannedDocumentsTest.java
=> Remove old feature flag

src/functionalTest/java/uk/gov/hmcts/divorce/caseworker/CaseworkerCreateGeneralLetterFT.java, src/functionalTest/java/uk/gov/hmcts/divorce/caseworker/CaseworkerIssueApplicationFT.java, src/functionalTest/java/uk/gov/hmcts/divorce/caseworker/CaseworkerOfflineDocumentVerifiedFT.java, src/functionalTest/java/uk/gov/hmcts/divorce/legaladvisor/LegalAdvisorMakeDecisionFT.java, src/functionalTest/java/uk/gov/hmcts/divorce/systemupdate/event/SystemProgressCaseToAosOverdueFT.java, src/functionalTest/java/uk/gov/hmcts/divorce/systemupdate/event/SystemProgressHeldCasesFT.java, src/functionalTest/java/uk/gov/hmcts/divorce/systemupdate/event/SystemResendCOPronouncedCoverLetterFT.java, src/functionalTest/java/uk/gov/hmcts/divorce/systemupdate/event/SystemUpdateCaseWithCourtHearingFT.java, src/main/java/uk/gov/hmcts/divorce/common/event/page/Applicant2FinalOrderExplainTheDelay.java, src/main/java/uk/gov/hmcts/divorce/common/event/page/FinalOrderExplainTheDelay.java
=> Alter show condition

src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerNoticeOfChange.java, src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerNoticeOfChangeTest.java
=> Fix Noc Npe

src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerNoticeOfChange.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/NoticeOfChange.java, src/main/java/uk/gov/hmcts/divorce/solicitor/service/SolicitorValidationService.java, src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerNoticeOfChangeTest.java, src/test/java/uk/gov/hmcts/divorce/solicitor/service/SolicitorValidationServiceTest.java
=> Add Validation errors for Noc when user not exists and mismatched organisation

src/main/java/uk/gov/hmcts/divorce/caseworker/service/task/SendAosPackToApplicant.java, src/test/java/uk/gov/hmcts/divorce/caseworker/service/task/SendAosPackToApplicantTest.java
Add Check for Joint Application when sending Application Issue Letters
=> Add Check for Joint Application when sending Application Issue Letters

src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerOfflineDocumentVerified.java, src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerOfflineDocumentVerifiedTest.java
Use typeOfDocumentAttached instead of scannedSubtypeReceived to fix submitted actions
https://tools.hmcts.net/jira/browse/NFDIV-3621
=> NFDIV-3621: Fix CaseworkerOfflineDocumentVerified submitted actions

build.gradle
=> Bump tomcat version to fix CVE-2020-23064

src/integrationTest/java/uk/gov/hmcts/divorce/caseworker/CaseworkerIssueApplicationIT.java, src/integrationTest/java/uk/gov/hmcts/divorce/caseworker/CaseworkerReIssueApplicationIT.java, src/integrationTest/resources/caseworker-offline-document-verified-other-response.json, src/integrationTest/resources/wiremock/responses/about-to-submit-cancel-case-invite.json, src/main/java/uk/gov/hmcts/divorce/caseworker/service/task/SendAosPackToApplicant.java, src/main/java/uk/gov/hmcts/divorce/caseworker/service/task/SetServiceType.java, src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerCreatePaperCaseTest.java, src/test/java/uk/gov/hmcts/divorce/caseworker/service/task/SendAosPackToApplicantTest.java, src/test/java/uk/gov/hmcts/divorce/caseworker/service/task/SetServiceTypeTest.java, src/test/java/uk/gov/hmcts/divorce/testutil/TestDataHelper.java
Joint applications should always be court service
https://tools.hmcts.net/jira/browse/NFDIV-3640
=> Joint applications should always be court service

src/functionalTest/java/uk/gov/hmcts/divorce/bulkscan/endpoint/ValidationControllerFT.java, src/integrationTest/java/uk/gov/hmcts/divorce/bulkscan/endpoint/ValidationControllerIT.java, src/main/java/uk/gov/hmcts/divorce/bulkscan/endpoint/data/OcrDataValidationRequest.java, src/main/java/uk/gov/hmcts/divorce/bulkscan/validation/data/OcrDataFields.java, src/test/java/uk/gov/hmcts/divorce/bulkscan/validation/OcrValidatorTest.java, src/test/java/uk/gov/hmcts/divorce/testutil/TestDataHelper.java
Expect List<OcrDataField> rather than List<KeyValue> in OcrDataValidationRequest
https://tools.hmcts.net/jira/browse/NFDIV-3593
=> NFDIV-3593: Expect List<OcrDataField> rather than List<KeyValue> in OcrDataValidationRequest

src/main/java/uk/gov/hmcts/divorce/bulkscan/endpoint/ValidationController.java
Add debug logging for ocr validation
https://tools.hmcts.net/jira/browse/NFDIV-3593
=> Add debug logging for ocr validation

src/main/java/uk/gov/hmcts/divorce/caseworker/event/page/CorrectRelationshipDetails.java, src/main/java/uk/gov/hmcts/divorce/notification/CommonContent.java, src/test/java/uk/gov/hmcts/divorce/notification/CommonContentTest.java
Protect against NPE
https://tools.hmcts.net/jira/browse/NFDIV-3646
=> Protect against NPE

src/main/java/uk/gov/hmcts/divorce/caseworker/event/page/CorrectRelationshipDetails.java
=> revert gender change

src/main/java/uk/gov/hmcts/divorce/common/event/SwitchedToSoleFinalOrder.java
Add FinalOrderExplainTheDelay
https://tools.hmcts.net/jira/browse/NFDIV-3668
=> NFDIV-3668: Add FinalOrderExplainTheDelay

src/main/java/uk/gov/hmcts/divorce/common/event/SwitchedToSoleFinalOrder.java, src/test/java/uk/gov/hmcts/divorce/common/event/SwitchedToSoleFinalOrderTest.java
https://tools.hmcts.net/jira/browse/NFDIV-3651
=> add general referral service to switch to sole fo event

src/main/java/uk/gov/hmcts/divorce/solicitor/event/SolicitorChangeServiceRequest.java, src/test/java/uk/gov/hmcts/divorce/solicitor/event/SolicitorChangeServiceRequestTest.java
…e Request (Sol -> Court)
Update due date in case when solicitor uses Change Service Request (Sol -> Court)
https://tools.hmcts.net/jira/browse/NFDIV-3601
=> NFDIV-3601: Update due date 

src/main/java/uk/gov/hmcts/divorce/citizen/notification/Applicant1IntendToSwitchToSoleFoNotification.java, src/main/java/uk/gov/hmcts/divorce/notification/SwitchToSoleSolicitorTemplateContent.java, src/main/java/uk/gov/hmcts/divorce/solicitor/notification/SolicitorIntendsToSwitchToSoleFoNotification.java, src/test/java/uk/gov/hmcts/divorce/citizen/notification/Applicant1IntendToSwitchToSoleFoNotificationTest.java, src/test/java/uk/gov/hmcts/divorce/notification/SwitchToSoleSolicitorTemplateContentTest.java, src/test/java/uk/gov/hmcts/divorce/solicitor/notification/SolicitorIntendsToSwitchToSoleFoNotificationTest.java
Missing notification: email to notify applicant 2 that applicant 1 has submitted an intent to switch to sole is not being sent to applicant 2's solicitor
https://tools.hmcts.net/jira/browse/NFDIV-3745
=> Nfdiv 3745 missing notification

src/main/java/uk/gov/hmcts/divorce/payment/PaymentService.java
=> add logging

src/main/java/uk/gov/hmcts/divorce/payment/PaymentService.java, src/main/java/uk/gov/hmcts/divorce/payment/model/CreditAccountPaymentRequest.java
=> fix case_type

build.gradle, src/functionalTest/java/uk/gov/hmcts/divorce/caseworker/CaseworkerRejectedFT.java
Fix bootRun
https://tools.hmcts.net/jira/browse/NFDIV-3738
=> Nfdiv 3738 fix boot run

build.gradle, config/owasp/suppressions.xml
CVE-2023-5072
https://tools.hmcts.net/jira/browse/NFDIV-3770
=> CVE-2023-5072

Dockerfile
Reverts hmcts/nfdiv-case-api#3311
=> Revert "Update hmctspublic.azurecr.io/base/java Docker tag to v21"

Dockerfile, charts/nfdiv-case-api/Chart.yaml, charts/nfdiv-case-api/values.yaml
=> update to java21 again

src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerReturnToPreviousState.java, src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerReturnToPreviousStateTest.java
=> Check cases are issued before sending to post issued state

src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerOfflineDocumentVerified.java
https://tools.hmcts.net/jira/browse/NFDIV-3779
=> NFDIV-3779 - Add logging to help track what caseworkers are doing for event

src/main/java/uk/gov/hmcts/divorce/CaseApiApplication.java, src/main/java/uk/gov/hmcts/divorce/payment/PaymentClient.java, src/main/java/uk/gov/hmcts/divorce/payment/PaymentStatusService.java, src/main/java/uk/gov/hmcts/divorce/payment/model/Payment.java, src/main/java/uk/gov/hmcts/divorce/systemupdate/schedule/SystemFindCasesWithSuccessfulPaymentsTask.java, src/test/java/uk/gov/hmcts/divorce/payment/PaymentStatusServiceTest.java, src/test/java/uk/gov/hmcts/divorce/systemupdate/schedule/SystemFindCasesWithSuccessfulPaymentsTaskTest.java
Cron task to log case id's where case is in AwaitingPayment state but has successful payment,
=> Cron task to log case id's where case is in AwaitingPayment state but has successful payment

src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerOfflineDocumentVerified.java
=> More logging for offline doc verified

src/main/java/uk/gov/hmcts/divorce/systemupdate/schedule/SystemFindCasesWithSuccessfulPaymentsTask.java
=> NFDIV-3751: update log message

build.gradle
=> update rse lib

src/main/java/uk/gov/hmcts/divorce/payment/PaymentStatusService.java, src/main/java/uk/gov/hmcts/divorce/systemupdate/schedule/SystemFindCasesWithSuccessfulPaymentsTask.java, src/test/java/uk/gov/hmcts/divorce/payment/PaymentStatusServiceTest.java, src/test/java/uk/gov/hmcts/divorce/systemupdate/schedule/SystemFindCasesWithSuccessfulPaymentsTaskTest.java
refactor to use parallel stream
=> NFDIV-3751: refactor to use parallel stream

src/main/java/uk/gov/hmcts/divorce/payment/PaymentStatusService.java
=> NFDIV-3751: use case insensitive match

src/main/java/uk/gov/hmcts/divorce/payment/PaymentStatusService.java
=> NFDIV-3751: Add logging

src/main/java/uk/gov/hmcts/divorce/payment/PaymentStatusService.java, src/main/java/uk/gov/hmcts/divorce/systemupdate/schedule/SystemFindCasesWithSuccessfulPaymentsTask.java, src/test/java/uk/gov/hmcts/divorce/systemupdate/schedule/SystemFindCasesWithSuccessfulPaymentsTaskTest.java
=> NFDIV-3751: filter out current day to reduce number in-progress cases

build.gradle
=> update cft lib

src/main/java/uk/gov/hmcts/divorce/payment/PaymentStatusService.java
=> Remove log message

src/main/java/uk/gov/hmcts/divorce/payment/PaymentStatusService.java, src/main/java/uk/gov/hmcts/divorce/systemupdate/schedule/SystemFindCasesWithSuccessfulPaymentsTask.java, src/test/java/uk/gov/hmcts/divorce/payment/PaymentStatusServiceTest.java, src/test/java/uk/gov/hmcts/divorce/systemupdate/schedule/SystemFindCasesWithSuccessfulPaymentsTaskTest.java
NFDIV-3751: Amend search criteria
=> NFDIV-3751: Amend search criteria

build.gradle
Bump cft lib to latest for new env var secrets
=> Bump cft lib to latest for new env var secrets

src/main/java/uk/gov/hmcts/divorce/payment/PaymentStatusService.java
=> NFDIV-3751: Log case ids

src/main/java/uk/gov/hmcts/divorce/divorcecase/model/CaseDocuments.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/tab/CaseTypeTab.java, src/main/java/uk/gov/hmcts/divorce/document/model/LetterPack.java, src/main/java/uk/gov/hmcts/divorce/document/print/LetterPrinter.java
Add tab for super users showing the letter packs being sent to aid in testing
https://tools.hmcts.net/jira/browse/NFDIV-3826
=> NFDIV-3826: Doc Pack QA Tab

src/integrationTest/resources/caseworker-expedite-final-order-offline-response.json, src/integrationTest/resources/caseworker-grant-final-order-offline-response.json, src/integrationTest/resources/caseworker-grant-final-order-overdue-response.json, src/main/java/uk/gov/hmcts/divorce/document/print/LetterPrinter.java
=> fix QA letter pack tab

build.gradle
https://nvd.nist.gov/vuln/detail/CVE-2023-34055
https://nvd.nist.gov/vuln/detail/CVE-2023-34053
=> Bump springboot version to fix CVEs

build.gradle, src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerOfflineDocumentVerified.java, src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerOfflineDocumentVerifiedTest.java
After a document rework, we removed the submitted callback for OfflineDocumentVerified event. This needed to be added to allow for the switch to sole events to be chained correctly.
Added back submitted callback
Fixed unit tests
https://tools.hmcts.net/jira/browse/NFDIV-N/A
=> NFDIV - Fix broken switch to sole for offline cases

src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerGeneralEmail.java, src/main/java/uk/gov/hmcts/divorce/caseworker/service/task/GenerateGeneralLetter.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/CaseData.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/tab/CaseTypeTab.java, src/main/java/uk/gov/hmcts/divorce/document/DocumentUtil.java, src/main/java/uk/gov/hmcts/divorce/document/model/DocumentType.java, src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerGeneralEmailTest.java, src/test/java/uk/gov/hmcts/divorce/document/DocumentUtilTest.java
Stop Confidential general letters and general emails appearing in the correspondence tab
https://tools.hmcts.net/jira/browse/NFDIV-3773
=> Stop Confidential general letters and general emails appearing in the correspondence tab

src/main/java/uk/gov/hmcts/divorce/document/DocumentUtil.java, src/main/java/uk/gov/hmcts/divorce/document/model/DocumentType.java, src/test/java/uk/gov/hmcts/divorce/document/DocumentUtilTest.java
Fix confidential approach to general letters
=> Fix confidential approach to general letters

src/integrationTest/java/uk/gov/hmcts/divorce/caseworker/CaseworkerRegenerateCourtOrdersIT.java, src/integrationTest/resources/application.yaml, src/main/resources/application.yaml
Update docmosis template reference
https://tools.hmcts.net/jira/browse/NFDIV-3836
=> NFDIV-3836: Update docmosis template reference

src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerGeneralLetter.java, src/main/java/uk/gov/hmcts/divorce/document/print/LetterPrinter.java
Remove use of null General Letter object for recipient name
=> Remove use of null General Letter object for recipient name

build.gradle
Update to latest to fix issue with booting cft lib
=> Update to latest to fix issue with booting cft lib

src/main/java/uk/gov/hmcts/divorce/divorcecase/model/State.java
=> add back as it's breaking stuff

src/main/java/uk/gov/hmcts/divorce/systemupdate/event/SystemCancelCaseInvite.java
Allow invites to be cancelled from AwaitingService state
=> A case is failing to cancel invite as it's in state of AwaitingService

src/main/java/uk/gov/hmcts/divorce/document/content/ConditionalOrderPronouncedTemplateContent.java, src/main/java/uk/gov/hmcts/divorce/systemupdate/service/task/GenerateConditionalOrderPronouncedDocument.java, src/test/java/uk/gov/hmcts/divorce/document/content/ConditionalOrderPronouncedTemplateContentTest.java, src/test/java/uk/gov/hmcts/divorce/systemupdate/service/task/GenerateConditionalOrderPronouncedDocumentTest.java
fix template content classto fetch missing vars
NFDIV-3935
=> NFDIV-3935 template vars missing on the content class

src/integrationTest/java/uk/gov/hmcts/divorce/caseworker/CaseworkerIssueApplicationIT.java, src/integrationTest/java/uk/gov/hmcts/divorce/caseworker/CaseworkerReIssueApplicationIT.java, src/integrationTest/resources/application.yaml, src/main/resources/application.yaml
Reverting because QA is needed
=> Revert "NFDIV-3835: Update NoP PS template"

src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/NFDIV-4016
=> NFDIV-4016 old price 245

src/functionalTest/resources/responses/response-caseworker-confirm-payment-deemed.json
https://tools.hmcts.net/jira/browse/NFDIV-4028
=> NFDIV-4028 Update Case-Api FTs to expect new fee values

charts/nfdiv-case-api/Chart.yaml, charts/nfdiv-case-api/values.yaml
https://tools.hmcts.net/jira/browse/NFDIV-4036
=> reduce min replicas to 2

src/main/java/uk/gov/hmcts/divorce/divorcecase/validation/ValidationUtil.java, src/test/java/uk/gov/hmcts/divorce/divorcecase/validation/CaseValidationTest.java
https://tools.hmcts.net/jira/browse/NFDIV-4059
=> NFDIV-4059 Add validation warning for null submittedDate

src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerHwfApplicationAccepted.java, src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerPaymentMade.java, src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerHwfApplicationAcceptedTest.java, src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerPaymentMadeTest.java
https://tools.hmcts.net/jira/browse/NFDIV-4060
=> NFDIV-4060 Set dateSubmitted in CaseworkerPaymentMade and CaseworkerHwfApplicationAccepted events

src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerAmendCase.java, src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerIssueApplication.java, src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerReissueApplication.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/validation/ValidationUtil.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/SolicitorCreateApplication.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/MarriageCertificateDetails.java, src/test/java/uk/gov/hmcts/divorce/divorcecase/validation/CaseValidationTest.java
Validate marriage date against current date when dateSubmitted is null
=> Validate on currentdate when no date submitted

src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerAmendCase.java, src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerAmendCaseTest.java
https://tools.hmcts.net/jira/browse/NFDIV-4117
=> [NFDIV-4117] Revert D8 regeneration on update case

src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerNoticeOfChange.java
https://tools.hmcts.net/jira/browse/NFDIV-4181
=> NFDIV-4181 Improve NOC logging to include Case Id and appropriate Applicant

src/main/java/uk/gov/hmcts/divorce/common/notification/ServiceApplicationNotification.java, src/main/java/uk/gov/hmcts/divorce/notification/CommonContent.java, src/test/java/uk/gov/hmcts/divorce/common/notification/ServiceApplicationNotificationTest.java, src/test/java/uk/gov/hmcts/divorce/testutil/TestDataHelper.java
https://tools.hmcts.net/jira/browse/NFDIV-4182
=> NFDIV-4182 ServiceApplicationNotification.sentToApplicant1Solicitor pulls null date

src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerAddAdminClarification.java, src/main/java/uk/gov/hmcts/divorce/caseworker/event/ConditionalOrderReviewCaseworker.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/State.java, src/main/java/uk/gov/hmcts/divorce/legaladvisor/event/LegalAdvisorMakeDecision.java, src/main/java/uk/gov/hmcts/divorce/legaladvisor/event/LegalAdvisorReview.java, src/test/java/uk/gov/hmcts/divorce/caseworker/event/ConditionalOrderReviewCaseworkerTest.java
Add a new event for caseworker
https://tools.hmcts.net/jira/browse/NFDIV-3998
=> NFDIV-3998: Add a new event for caseworker

src/functionalTest/resources/responses/response-joint-application-help-with-fees-awaiting-documents.json, src/main/java/uk/gov/hmcts/divorce/common/service/task/SetStateAfterSubmission.java, src/test/java/uk/gov/hmcts/divorce/common/service/task/SetStateAfterSubmissionTest.java
Refactor code to set correct state for help with fees
https://tools.hmcts.net/jira/browse/NFDIV-4148
=> NFDIV-4148: Refactor code to set correct state for help with fees

src/main/java/uk/gov/hmcts/divorce/divorcecase/model/access/BulkCaseListAccess.java, src/test/java/uk/gov/hmcts/divorce/divorcecase/model/access/BulkCaseListAccessTest.java
Grant create permission to caseworker and superuser on schedule cases for listing add cases field
https://tools.hmcts.net/jira/browse/NFDIV-4190
=> NFDIV-4190: Grant create permission to caseworker and superuser

src/main/resources/data/joint.json, src/main/resources/data/sole.json
We need these fields to be set for common component NoC to work on the cases.
https://tools.hmcts.net/jira/browse/NFDIV-4192
=> [NFDIV-4192] Set OrgPolicyCaseAssignedRole for test cases

src/main/java/uk/gov/hmcts/divorce/common/service/task/GenerateAndLinkRespondentAnswers.java, src/test/java/uk/gov/hmcts/divorce/common/service/task/GenerateAndLinkRespondentAnswersTest.java
Check if aos is drafted and equal to yes
https://tools.hmcts.net/jira/browse/NFDIV-4193
=> NFDIV-4193: Check if aos is drafted and equal to yes

src/main/java/uk/gov/hmcts/divorce/solicitor/event/SolicitorChangeServiceRequest.java, src/test/java/uk/gov/hmcts/divorce/solicitor/event/SolicitorChangeServiceRequestTest.java
https://tools.hmcts.net/jira/browse/NFDIV-4165
=> [NFDIV-4165] Block solicitor change service request unless issueDate is set

src/main/java/uk/gov/hmcts/divorce/divorcecase/model/CaseData.java
Add caseworker access on field
https://tools.hmcts.net/jira/browse/NFDIV-4257
=> NFDIV-4257: Add caseworker access on field

src/main/java/uk/gov/hmcts/divorce/document/content/ConditionalOrderPronouncedTemplateContent.java, src/test/java/uk/gov/hmcts/divorce/document/content/ConditionalOrderPronouncedTemplateContentTest.java
Ensure that for conditional order pronounced template content, correct partner label is filled in and is a derivative of the applicant information passed in method arguments.
https://tools.hmcts.net/jira/browse/NFDIV-4258
=> NFDIV-4258 Add partner information for correct parter

src/main/java/uk/gov/hmcts/divorce/divorcecase/tab/CaseTypeTab.java
https://tools.hmcts.net/jira/browse/NFDIV-4259
=> [NFDIV-4259] Hide change of representatives tab unless NoC fields are set

Dockerfile
Fortify flagging our dockerfile for not having a specified user
https://tools.hmcts.net/jira/browse/NFDIV-4262
=> Specify user in dockerfile

src/integrationTest/java/uk/gov/hmcts/divorce/testutil/IdamWireMock.java, src/integrationTest/resources/application.yaml
Adjusted integration test config to stop Fortify warning
https://tools.hmcts.net/jira/browse/NFDIV-4280
=> [NFDIV-4280] Get integration test login details from env variable

src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerGeneralApplicationReceivedDummyOldEventName.java, src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerGeneralApplicationReceivedDummyOldEventNameTest.java
https://tools.hmcts.net/jira/browse/NFDIV-4281
=> [NFDIV-4281] Add read permissions for old general application received event name

src/main/java/uk/gov/hmcts/divorce/common/service/task/SetStateAfterSubmission.java, src/test/java/uk/gov/hmcts/divorce/common/service/task/SetStateAfterSubmissionTest.java
https://tools.hmcts.net/jira/browse/NFDIV-4282
=> [NFDIV-4282] Only move joint case to HWF state during submission if both applicants need HWF

build.gradle
https://tools.hmcts.net/jira/browse/NFDIV-4291
=> [NFDIV-4291] Add Fortify Version Classifier

src/main/java/uk/gov/hmcts/divorce/common/event/page/GeneralApplicationUploadDocument.java
https://tools.hmcts.net/jira/browse/NFDIV-4286
=> [NFDIV-4286] Make general application fields optional for caseworkers

src/main/java/uk/gov/hmcts/divorce/common/service/task/SetFinalOrderFieldsAsApplicant2.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/FinalOrder.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/search/CaseFieldsConstants.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/search/SearchInputFields.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/tab/CaseTypeTab.java
https://tools.hmcts.net/jira/browse/NFDIV-4104
=> [NFDIV-4104] Allow respondents to pay online for Final Order EXUI updates

src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerUpdateFinRemAndJurisdiction.java, src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerUpdateFinRemAndJurisdictionJoint.java, src/main/java/uk/gov/hmcts/divorce/common/event/RegenerateApplication.java
https://tools.hmcts.net/jira/browse/NFDIV-4312
=> [NFDIV-4312] Give caseworkers access to event history for regen D8 and update finrem

src/main/java/uk/gov/hmcts/divorce/systemupdate/event/SystemPronounceCase.java, src/test/java/uk/gov/hmcts/divorce/systemupdate/event/SystemPronounceCaseTest.java
Fix issue with missing court 
https://tools.hmcts.net/jira/browse/NFDIV-4308
=> NFDIV-4308: Fix issue with missing court

src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerPrepareGeneralEmailAttachments.java, src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerPrepareGeneralEmailAttachmentsTest.java
https://tools.hmcts.net/jira/browse/NFDIV-4311
=> [NFDIV-4311] Handle docs without files attached in prepare email attachments

src/main/java/uk/gov/hmcts/divorce/systemupdate/event/SystemPronounceCase.java, src/test/java/uk/gov/hmcts/divorce/systemupdate/event/SystemPronounceCaseTest.java
Remove system update case with court hearing event call
https://tools.hmcts.net/jira/browse/NFDIV-4308
=> NFDIV-4308: Remove system update case with court hearing event call

src/main/java/uk/gov/hmcts/divorce/common/event/SwitchedToSoleFinalOrder.java
Fix issue with switching user roles
https://tools.hmcts.net/jira/browse/NFDIV-4313
=> NFDIV-4313: Fix issue with switching user roles

src/main/java/uk/gov/hmcts/divorce/document/content/templatecontent/FinalOrderCanApplyTemplateContent.java
Check which applicant the template content is being created for and pass arguments accordingly to commoncontent.getpartner
https://tools.hmcts.net/jira/browse/NFDIV-4334
=> NFDIV-4334 Fix value for partner field in apply for final order letter

charts/nfdiv-case-api/Chart.yaml
Update ccd def cleanup chart
https://tools.hmcts.net/jira/browse/NFDIV-4138
=> NFDIV-4138: Update ccd def cleanup chart

src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerUploadDocument.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/CaseDocuments.java, src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerUploadDocumentTest.java
Restrict deletion of documents in 'Upload document' event.
https://tools.hmcts.net/jira/browse/NFDIV-4402
=> NFDIV-4402 - Restrict deletion of documents in 'Upload document' event.

src/main/java/uk/gov/hmcts/divorce/divorcecase/search/CaseFieldsConstants.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/search/SearchInputFields.java
https://tools.hmcts.net/jira/browse/NFDIV-4440
=> [NFDIV-4422] Add general referral type to search filters

.github/workflows/stale.yml
Update workflow to a scheduled job for 3PM each day
https://tools.hmcts.net/jira/browse/NFDIV-4430
=> NFDIV-4430 Update workflow to a scheduled job for 3PM each day

.github/workflows/stale.yml
Nfdiv-4430 Running stale workflow scheduled at 3AM everyday
https://tools.hmcts.net/jira/browse/NFDIV-4430
=> Nfdiv-4430 Running stale workflow scheduled at 3AM everyday

src/main/java/uk/gov/hmcts/divorce/citizen/event/CitizenPaymentMade.java, src/main/java/uk/gov/hmcts/divorce/citizen/event/RespondentFinalOrderPaymentMade.java
Add user permissions for cron testing in AAT
https://tools.hmcts.net/jira/browse/NFDIV-4330
=> NFDIV-4330: Add user permissions for cron testing in AAT

src/main/java/uk/gov/hmcts/divorce/common/ccd/HighLevelDataSetupApp.java
https://tools.hmcts.net/jira/browse/NFDIV-4410
=> [NFDIV-4410] Use CCD Environment in high level data setup logic

src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerRemoveDocument.java, src/main/java/uk/gov/hmcts/divorce/common/ccd/HighLevelDataSetupApp.java, src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerRemoveDocumentTest.java
Check for presence of document type
https://tools.hmcts.net/jira/browse/NFDIV-4521
=> NFDIV-4521 - Check for presence of document type

build.gradle
https://tools.hmcts.net/jira/browse/NFDIV-4461
=> [NFDIV-4461] Update config generator to 5.5.14

src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerRequestForInformationResponse.java
https://tools.hmcts.net/jira/browse/NFDIV-4537
=> NFDIV-4537 Amend CW Event Name - Change- Add Text Only RFI Response -TO- Add RFI Response

src/main/java/uk/gov/hmcts/divorce/divorcecase/model/CaseData.java
https://tools.hmcts.net/jira/browse/NFDIV-4587
=> [NFDIV-4587] Blank out stale document data when new general application added

src/main/java/uk/gov/hmcts/divorce/systemupdate/event/SystemSetTimeToLive.java, src/test/java/uk/gov/hmcts/divorce/systemupdate/event/SystemSetTimeToLiveTest.java
https://tools.hmcts.net/jira/browse/NFDIV-4455
=> [NFDIV-4455] Add event for Retain and Dispose TTL migration

src/main/java/uk/gov/hmcts/divorce/caseworker/service/notification/FinalOrderGrantedNotification.java, src/main/java/uk/gov/hmcts/divorce/payment/PaymentService.java, src/test/java/uk/gov/hmcts/divorce/caseworker/service/notification/FinalOrderGrantedNotificationTest.java
https://tools.hmcts.net/jira/browse/NFDIV-4646
=> [NFDIV-4646] Remove deprecated F&P keyword

src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerRequestForInformation.java
https://tools.hmcts.net/jira/browse/NFDIV-4620
=> NFDIV-4620 Block RFI from being available in "Draft", "AwaitingPayment"

src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerRemoveGeneralLetter.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/GeneralLetterDetails.java, src/main/java/uk/gov/hmcts/divorce/document/DocumentRemovalService.java, src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerRemoveGeneralLetterTest.java
https://tools.hmcts.net/jira/browse/NFDIV-4596
=> [NFDIV-4596] Add event to remove general letters

src/main/java/uk/gov/hmcts/divorce/noticeofchange/event/SystemApplyNoticeOfChange.java
https://tools.hmcts.net/jira/browse/NFDIV-4649
=> [NFDIV-4649] Use AAC response data for NOC notifications

Jenkinsfile_CNP, build.gradle, src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerCreatePaperCase.java
https://tools.hmcts.net/jira/browse/NFDIV-4677
=> NFDIV-4677 Investigate how paper case can be created for testing without bulk scan process

build.gradle
Reverts hmcts/nfdiv-case-api#4326
=> Revert "Update plugin com.github.hmcts.rse-cft-lib to v0.19.1582"

src/main/java/uk/gov/hmcts/divorce/divorcecase/model/Solicitor.java
=> Avoid null pointer exception when sol address is blank

charts/nfdiv-case-api/Chart.yaml
https://tools.hmcts.net/jira/browse/NFDIV-4709
=> [NFDIV-4709] Update remaining charts to OCI

build.gradle
=> Upgrade config gen to 5.5.19

src/main/java/uk/gov/hmcts/divorce/divorcecase/validation/ValidationUtil.java, src/test/java/uk/gov/hmcts/divorce/divorcecase/validation/CaseValidationTest.java
https://tools.hmcts.net/jira/browse/NFDIV-4795
=> [NFDIV-4795] Allow more characters in names

src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerCreatePaperCase.java, src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerCreatePaperCaseTest.java
Stop sending paper app received letter for JS cases
https://tools.hmcts.net/jira/browse/NFDIV-4835
=> NFDIV-4835 - Stop sending paper app received letter for JS cases

src/main/java/uk/gov/hmcts/divorce/systemupdate/event/SystemLinkApplicant1.java, src/main/java/uk/gov/hmcts/divorce/systemupdate/event/SystemLinkApplicant2.java
https://tools.hmcts.net/jira/browse/NFDIV-4804
=> NFDIV-4804 - Update event names for linking events

src/test/java/uk/gov/hmcts/divorce/caseworker/event/page/CorrectRelationshipDetailsTest.java, src/test/java/uk/gov/hmcts/divorce/caseworker/service/NoticeOfChangeServiceTest.java, src/test/java/uk/gov/hmcts/divorce/common/event/page/Applicant2SolConfirmContactDetailsTest.java, src/test/java/uk/gov/hmcts/divorce/common/event/page/ConditionalOrderReviewAoSApplicant2IfNoTest.java, src/test/java/uk/gov/hmcts/divorce/common/event/page/ConditionalOrderReviewAoSApplicant2Test.java, src/test/java/uk/gov/hmcts/divorce/common/event/page/ConditionalOrderReviewAoSIfNoTest.java, src/test/java/uk/gov/hmcts/divorce/common/event/page/ConditionalOrderReviewAoSTest.java, src/test/java/uk/gov/hmcts/divorce/common/notification/ApplyForConditionalOrderDocumentPackTest.java, src/test/java/uk/gov/hmcts/divorce/common/notification/AwaitingConditionalOrderReminderNotificationDocumentPackTest.java, src/test/java/uk/gov/hmcts/divorce/common/service/task/SetApplicantOfflineStatusTest.java, src/test/java/uk/gov/hmcts/divorce/document/print/model/PrintTest.java, src/test/java/uk/gov/hmcts/divorce/solicitor/event/page/Applicant2ServiceDetailsTest.java, src/test/java/uk/gov/hmcts/divorce/solicitor/event/page/MarriageIrretrievablyBrokenTest.java, src/test/java/uk/gov/hmcts/divorce/solicitor/event/page/SolAboutApplicant1Test.java, src/test/java/uk/gov/hmcts/divorce/solicitor/event/page/SolHowDoYouWantToApplyForDivorceTest.java, src/test/java/uk/gov/hmcts/divorce/solicitor/service/task/ProgressApplicant1FinalOrderStateTest.java, src/test/java/uk/gov/hmcts/divorce/solicitor/service/task/ProgressApplicant2FinalOrderStateTest.java, src/test/java/uk/gov/hmcts/divorce/solicitor/service/task/SetApplicantGenderTest.java
https://tools.hmcts.net/jira/browse/NFDIV-4830
=> NFDIV-4830 Ensure assertion arguments are passed in correct order

src/functionalTest/resources/request/casedata/ccd-callback-solicitor-general-application-about-to-submit-telephone-payment.json, src/functionalTest/resources/request/casedata/ccd-callback-solicitor-general-application-about-to-submit.json, src/functionalTest/resources/responses/response-solicitor-general-application-about-to-submit-telephone-payment.json, src/functionalTest/resources/responses/response-solicitor-general-application-about-to-submit.json, src/main/java/uk/gov/hmcts/divorce/common/event/page/GeneralApplicationUploadDocument.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/SolicitorGeneralApplication.java, src/test/java/uk/gov/hmcts/divorce/solicitor/event/SolicitorGeneralApplicationTest.java
https://tools.hmcts.net/jira/browse/NFDIV-4811
=> NFDIV-4811 - Validate that general application is not submitted without documents

src/main/java/uk/gov/hmcts/divorce/divorcecase/model/RequestForInformationList.java
https://tools.hmcts.net/jira/browse/NFDIV-4883
=> [NFDIV-4883] Catch NPE in request for information list

src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerAddNoteTest.java, src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerAddTranslationTest.java, src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerAwaitingJudgeClarificationTest.java, src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerCreateCaseFlagTest.java, src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerCreateGeneralOrderTest.java, src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerGeneralEmailTest.java, src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerListForHearingTest.java, src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerManageCaseFlagTest.java, src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerPendingHearingDateTest.java, src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerPendingHearingOutcomeTest.java, src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerPrepareForCaseFlagsTest.java, src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerRescindConditionalOrderTest.java, src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerResetConditionalOrderFlagsTest.java, src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerResponseToJudgeTest.java, src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerReturnToPreviousStateTest.java, src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerUpdateApplicant1EmailTest.java, src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerUpdateApplicant2EmailTest.java, src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerUpdateDueDateTest.java, src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerUpdateGeneralApplicationTest.java, src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerUpdateLanguagePreferenceTest.java, src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerUpdateOfflineStatusTest.java, src/test/java/uk/gov/hmcts/divorce/common/config/interceptors/RequestInterceptorTest.java, src/test/java/uk/gov/hmcts/divorce/solicitor/event/SolicitorArchiveCaseTest.java, src/test/java/uk/gov/hmcts/divorce/solicitor/service/CcdAccessServiceTest.java
https://tools.hmcts.net/jira/browse/NFDIV-4833
=> [NFDIV-4833] Remove redundant exception declarations

src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerRemoveScannedDocument.java, src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerRemoveScannedDocumentTest.java
https://tools.hmcts.net/jira/browse/NFDIV-4893
=> [NFDIV-4893] Temporarily turn off hard deletion of scanned docs

src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerCreatePaperCase.java, src/main/java/uk/gov/hmcts/divorce/document/content/DocmosisTemplateConstants.java, src/main/java/uk/gov/hmcts/divorce/document/content/PaperApplicationReceivedTemplateContent.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerCreatePaperCaseTest.java, src/test/java/uk/gov/hmcts/divorce/document/content/PaperApplicationReceivedTemplateContentTest.java
https://tools.hmcts.net/jira/browse/NFDIV-4842
=> [NFDIV-4842] Support JS cases in paper case received letter

src/main/java/uk/gov/hmcts/divorce/document/content/NoticeOfProceedingSolicitorContent.java, src/test/java/uk/gov/hmcts/divorce/document/content/NoticeOfProceedingSolicitorContentTest.java
https://tools.hmcts.net/jira/browse/NFDIV-4897
=> NFDIV-4897 NoP Sol Content Generator not utilising addressOverseas field

src/main/java/uk/gov/hmcts/divorce/bulkaction/service/BulkCaseProcessingService.java
=> Add null checks for dropped bulk lists

src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerCreatePaperCase.java
https://tools.hmcts.net/jira/browse/NFDIV-4902
=> [NFDIV-4902] Hide create papercase from caseworkers

src/main/java/uk/gov/hmcts/divorce/document/DocumentRemovalService.java, src/test/java/uk/gov/hmcts/divorce/document/DocumentRemovalServiceTest.java
https://tools.hmcts.net/jira/browse/NFDIV-4893
=> [NFDIV-4893] Avoid deletion of scanned docs when subtype changes

src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerCreatePaperCase.java
=> Re-enable caseworker paper case

src/main/java/uk/gov/hmcts/divorce/divorcecase/model/BailiffServiceJourneyOptions.java
=> [NFDIV-4785] Bailiff part 5

src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/NFDIV-4939
=> NFDIV-4939 - Update docmosis reference for AoS Overdue template

src/main/java/uk/gov/hmcts/divorce/systemupdate/schedule/SystemJsDisputedAnswerOverdueTask.java, src/test/java/uk/gov/hmcts/divorce/systemupdate/schedule/SystemJsDisputedAnswerOverdueTaskTest.java
Update cron query to use correct field values
https://tools.hmcts.net/jira/browse/NFDIV-4931
=> NFDIV-4931: Update cron query to use correct field values

src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/NFDIV-4920
=> NFDIV-4920 - Update docmosis reference for CO refusal templates

src/main/java/uk/gov/hmcts/divorce/common/event/RegenerateApplicationDocument.java
https://tools.hmcts.net/jira/browse/NFDIV-4975
Revert changes post document regen
=> NFDIV-4975 INC29919 - Add TTL_PROFILE to Regenerate D8 event

src/main/java/uk/gov/hmcts/divorce/divorcecase/model/DispenseWithServiceJourneyOptions.java
https://tools.hmcts.net/jira/browse/NFDIV-4767
=> NFDIV-4767 Dispense with service 5

src/main/java/uk/gov/hmcts/divorce/divorcecase/model/AlternativeService.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/AlternativeServiceJourneyOptions.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/BailiffServiceJourneyOptions.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/DeemedServiceJourneyOptions.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/DispenseWithServiceJourneyOptions.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/InterimApplicationOptions.java
=> Configure searchable for no response fields

src/main/java/uk/gov/hmcts/divorce/document/content/DispenseWithServiceApplicationTemplateContent.java, src/test/java/uk/gov/hmcts/divorce/document/content/DispenseWithServiceApplicationTemplateContentTest.java
https://tools.hmcts.net/jira/browse/NFDIV-5062
=> Nfdiv 5062 fix dispense service answers template content

src/main/java/uk/gov/hmcts/divorce/citizen/event/Applicant1UpdatePartnerDetailsOrReissue.java
Reset reissue options for contact details update
=> NFDIV-4713: Reset reissue options for contact details update

src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerGeneralReferral.java, src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerReissueApplication.java, src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerRejectGeneralApplication.java, src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerRejectServiceApplication.java, src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerUploadServiceApplicationDocuments.java, src/main/java/uk/gov/hmcts/divorce/citizen/notification/SaveAndSignOutNotificationHandler.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/GeneralApplication.java, src/main/java/uk/gov/hmcts/divorce/document/content/DispenseWithServiceApplicationTemplateContent.java, src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerGeneralReferralTest.java, src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerRejectGeneralApplicationTest.java, src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerRejectServiceApplicationTest.java, src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerUploadServiceApplicationDocumentsTest.java, src/test/java/uk/gov/hmcts/divorce/citizen/notification/SaveAndSignOutNotificationHandlerTest.java, src/test/java/uk/gov/hmcts/divorce/divorcecase/model/GeneralApplicationTest.java, src/test/java/uk/gov/hmcts/divorce/document/content/DispenseWithServiceApplicationTemplateContentTest.java
https://tools.hmcts.net/jira/browse/NFDIV-5052
=> [NFDIV-5052] No Response Caseworker Events

src/main/java/uk/gov/hmcts/divorce/divorcecase/model/State.java
=> [NFDIV-5064] Aos submission in awaiting documents
