hmcts/nfdiv-case-api

api/src/functionalTest/resources/responses/ccd-callback-submit-petition.json, api/src/integrationTest/resources/wiremock/responses/issue-fees-response.json, api/src/main/java/uk/gov/hmcts/reform/divorce/caseapi/controllers/SolicitorSubmitPetitionController.java, api/src/main/resources/application.yaml, api/src/test/java/uk/gov/hmcts/reform/divorce/caseapi/controllers/SolicitorSubmitPetitionControllerTest.java, ccd-definitions/src/main/java/uk/gov/hmcts/reform/divorce/ccd/model/CaseData.java
https://tools.hmcts.net/jira/browse/NFDIV-542
- Removed duplicate order summary from Case data.
- Added config to accept case sensitive enum as this is required when binding CCD callback request. 
- Tested on local docker and works fine.
```
[ ] Yes
[x ] No
```
=> Fix order summary for solicitor submit event

ccd-definitions/src/main/java/uk/gov/hmcts/reform/divorce/ccd/ccdcase/NoFaultDivorce.java, ccd-definitions/src/main/java/uk/gov/hmcts/reform/divorce/ccd/model/CaseData.java
https://tools.hmcts.net/jira/browse/NFDIV-425
The old frontend had this property has an Set as it allowed users to have more than one option but the new implementation allows users to only select one option.
```
[ ] Yes
[X] No
```
=> change from set to single as frontend now only returns 1 value

Jenkinsfile_CNP, api/build.gradle, api/src/functionalTest/java/uk/gov/hmcts/reform/divorce/caseapi/FunctionalTestSuite.java, api/src/functionalTest/java/uk/gov/hmcts/reform/divorce/caseapi/SolicitorSubmitPetitionTest.java, api/src/functionalTest/resources/application.yaml, api/src/integrationTest/java/uk/gov/hmcts/reform/divorce/caseapi/controllers/SolicitorSubmitPetitionControllerTest.java, api/src/integrationTest/resources/application.yaml, api/src/main/java/uk/gov/hmcts/reform/divorce/caseapi/CaseApiApplication.java, api/src/main/java/uk/gov/hmcts/reform/divorce/caseapi/config/AuthConfiguration.java, api/src/main/java/uk/gov/hmcts/reform/divorce/caseapi/controllers/SolicitorSubmitPetitionController.java, api/src/main/java/uk/gov/hmcts/reform/divorce/caseapi/enums/NotificationConstants.java, api/src/main/java/uk/gov/hmcts/reform/divorce/caseapi/service/CcdAccessService.java, api/src/main/java/uk/gov/hmcts/reform/divorce/caseapi/service/IdamService.java, api/src/main/resources/application.yaml, api/src/test/java/uk/gov/hmcts/reform/divorce/caseapi/TestConstants.java, api/src/test/java/uk/gov/hmcts/reform/divorce/caseapi/caseapi/util/TestDataHelper.java, api/src/test/java/uk/gov/hmcts/reform/divorce/caseapi/controllers/SolicitorSubmitPetitionControllerTest.java, api/src/test/java/uk/gov/hmcts/reform/divorce/caseapi/service/CcdAccessServiceTest.java, api/src/test/java/uk/gov/hmcts/reform/divorce/caseapi/service/IdamServiceTest.java, charts/nfdiv-case-api/Chart.yaml, charts/nfdiv-case-api/values.yaml
- https://tools.hmcts.net/jira/browse/NFDIV-558
- This PR adds functionality to add petitioner solicitor case roles as part of existing about to start callback for petitioner solicitor submit.
- For functional tests I am using an existing case id in AAT. Please let me know if that is fine or should I create new case in functional test everytime and use that case id ?
- Temporarily using `nfdiv_cms` s2s secret for token generation as cms is whitelisted in CCD and nfdiv case api is not. Will update once ccd has case api whitelisted.
=> Add petitioner solicitor roles

ccd-definitions/src/main/java/uk/gov/hmcts/reform/divorce/ccd/model/CaseData.java
https://tools.hmcts.net/jira/browse/NFDIV-249
New field created so that https://tools.hmcts.net/jira/browse/NFDIV-249 can use petitionerKnowsRespondentsAddress field
```
[ ] Yes
[ X ] No
```
=> NFDIV-249: new field petitionerKnowsRespondentsEmailAddress

api/build.gradle
- Notify Java API client will be required to be downloaded from Maven central as bintray will be deactivated from 1 May 2021.
- Configured jitpack repo to install ccd generator.
=> Removed bintray repo for gov notifiy and added jitpack repo for generator

src/main/java/uk/gov/hmcts/divorce/common/model/CaseData.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/SolicitorStatementOfTruthPaySubmit.java, src/main/java/uk/gov/hmcts/divorce/solicitor/service/SolicitorSubmitPetitionService.java, src/test/java/uk/gov/hmcts/divorce/solicitor/event/SolicitorStatementOfTruthPaySubmitTest.java, src/test/java/uk/gov/hmcts/divorce/solicitor/service/SolicitorSubmitPetitionServiceTest.java, src/test/java/uk/gov/hmcts/divorce/testutil/TestConstants.java
https://tools.hmcts.net/jira/browse/NFDIV-642
-  This PR adds functionality to update digital details fields based on respondent organisation and if the respondent solicitor is digitally available.
- Haven't replaced respondent with applicant2 as we still not have got the confirmation.
- Includes minor refactoring as well.
```
[ ] Yes
[ x] No
```
=> Added functionality to update respondent digital details fields

src/main/java/uk/gov/hmcts/divorce/common/model/CaseData.java
[NFDIV-656](https://tools.hmcts.net/jira/browse/NFDIV-656) Remove "IsInternational" fields from CaseDefination and Citizen Journey. 
Removes the `isInternational` fields. Requires https://github.com/hmcts/nfdiv-frontend/pull/557 to be merged first. The frontend will now use the address country to determine if the address should be displayed in international format.
```
[ ] Yes
[x] No
```
=> chore(NFDIV-656): Remove isInternational fields & use formatted AddressGlobalUK only

src/main/java/uk/gov/hmcts/divorce/citizen/event/CitizenAddPayment.java, src/main/java/uk/gov/hmcts/divorce/common/model/CaseData.java, src/test/java/uk/gov/hmcts/divorce/citizen/event/CitizenAddPaymentTest.java
[NFDIV-680](https://tools.hmcts.net/jira/browse/NFDIV-680) Payment - State Changes
Allow adding of payments while the case is in an `AwaitingPayment` state.
```
[ ] Yes
[x] No
```
=> feat(NFDIV-680): Allowing adding of payments while AwaitingPayment

build.gradle, charts/nfdiv-case-api/Chart.yaml, charts/nfdiv-case-api/values.yaml, settings.gradle, src/functionalTest/resources/application.yaml, src/integrationTest/java/uk/gov/hmcts/divorce/caseworker/schedule/CaseworkerAwaitingConditionalOrderTaskTest.java, src/integrationTest/resources/application.yaml, src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerAwaitingConditionalOrder.java, src/main/java/uk/gov/hmcts/divorce/caseworker/schedule/CaseworkerAwaitingConditionalOrderTask.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerAwaitingConditionalOrderTest.java, src/test/java/uk/gov/hmcts/divorce/caseworker/schedule/CaseworkerAwaitingConditionalOrderTaskTest.java
https://tools.hmcts.net/jira/browse/NFDIV-983
- Added event to move case state from `Holding` to `AwaitingConditionalOrder`.
- Added scheduled task to trigger the event if case is in holding state for more than 20 weeks.
- Integration test verifies if the scheduled job is executed only once.
- We will have to rely on manual testing till we e2e test in place as integration and functional tests for scheduled tasks is bit difficult.
```
[ ] Yes
[x ] No
```
=> Add schedule task for awaiting conditional order

src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerUpdateLanguage.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/SolicitorUpdateApplicant1Language.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/SolicitorUpdateApplicant2Language.java, src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerUpdateLanguageTest.java, src/test/java/uk/gov/hmcts/divorce/solicitor/event/SolicitorUpdateApplicant1LanguageTest.java, src/test/java/uk/gov/hmcts/divorce/solicitor/event/SolicitorUpdateApplicant2LanguageTest.java
This PR adds separate events for Solicitor 1 and 2 to update their clients language preference and an event for caseworkers to update either applicants language preference
=> NFDIV-890 Add update language events

src/main/java/uk/gov/hmcts/divorce/systemupdate/schedule/SystemProgressCasesToAosOverdueTask.java, src/test/java/uk/gov/hmcts/divorce/systemupdate/schedule/SystemProgressCasesToAosOverdueTaskTest.java
AoS overdue task should move case when overdue date on or before current date
=> Fix aos overdue scheduled task

src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/Applicant2ServiceDetails.java
https://tools.hmcts.net/jira/browse/NFDIV-1082
Fix service details page field that was displaying incorrect label
=> Fix service details page incorrect label displayed

src/main/java/uk/gov/hmcts/divorce/citizen/notification/Applicant2ApprovedNotification.java
https://tools.hmcts.net/jira/browse/NFDIV-974
Applicant 2's email address isn't currently being set on the FE, so need to use the applicant2InviteEmailAddress field to send emails to applicant 2 at the moment
```
[ ] Yes
[x] No
```
=> Update app 2 email address

src/main/java/uk/gov/hmcts/divorce/divorcecase/model/Applicant.java
https://tools.hmcts.net/jira/projects/NFDIV/issues/NFDIV-1096
Need to remove the content relating to property & children
AC 1 - question on sol journey 
When I am on the 'Other legal proceedings' screen. 
AC 2 - When the mini application is generated
see same name branch in repo https://github.com/hmcts/rdo-docmosis 
AC 3 - Application tab
When the caseworker clicks the application tab
[ ] Yes
[x] No
```
=> Remove '',property or children' from the

build.gradle
- In general it's better to use jitpack only when necessary and mavenCentral as a general purpose repository due to jitpack being a potential attack vector https://github.com/ben-manes/gradle-versions-plugin/issues/541#issuecomment-878461574
=> Fetch ben manes plugin from maven central instead of jitpack

src/main/java/uk/gov/hmcts/divorce/CaseApiApplication.java
- By default UTC timezone is used due to which documents generated during issue/reissue has time stamp which is one hour behind.
- Set Europe/London as default timezone for the app.
- Tested on local docker and is working fine.
=> Set Europe/London timezone for the app

src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerIssueApplication.java, src/main/java/uk/gov/hmcts/divorce/systemupdate/schedule/SystemAlertApplicationNotReviewedTask.java, src/main/java/uk/gov/hmcts/divorce/systemupdate/schedule/SystemMigrateCasesTask.java, src/main/java/uk/gov/hmcts/divorce/systemupdate/schedule/SystemProgressCasesToAosOverdueTask.java, src/main/java/uk/gov/hmcts/divorce/systemupdate/schedule/SystemProgressHeldCasesTask.java, src/main/java/uk/gov/hmcts/divorce/systemupdate/schedule/SystemRemindApplicant1ApplicationApprovedTask.java, src/main/java/uk/gov/hmcts/divorce/systemupdate/schedule/SystemRemindApplicant2Task.java, src/main/java/uk/gov/hmcts/divorce/systemupdate/schedule/conditionalorder/SystemNotifyApplicant1ApplyForConditionalOrder.java, src/main/java/uk/gov/hmcts/divorce/systemupdate/service/CcdSearchService.java, src/main/java/uk/gov/hmcts/divorce/systemupdate/service/CcdUpdateService.java, src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerIssueApplicationTest.java, src/test/java/uk/gov/hmcts/divorce/systemupdate/schedule/SystemAlertApplicationNotReviewedTaskTest.java, src/test/java/uk/gov/hmcts/divorce/systemupdate/schedule/SystemMigrateCasesTaskTest.java, src/test/java/uk/gov/hmcts/divorce/systemupdate/schedule/SystemProgressCasesToAosOverdueTaskTest.java, src/test/java/uk/gov/hmcts/divorce/systemupdate/schedule/SystemProgressHeldCasesTaskTest.java, src/test/java/uk/gov/hmcts/divorce/systemupdate/schedule/SystemRemindApplicant1ApplicationApprovedTaskTest.java, src/test/java/uk/gov/hmcts/divorce/systemupdate/schedule/SystemRemindApplicant2TaskTest.java, src/test/java/uk/gov/hmcts/divorce/systemupdate/schedule/conditionalorder/SystemNotifyApplicant1ApplyForConditionalOrderTest.java, src/test/java/uk/gov/hmcts/divorce/systemupdate/service/CcdSearchServiceTest.java, src/test/java/uk/gov/hmcts/divorce/systemupdate/service/CcdUpdateServiceTest.java
Reduce the number of calls made to idam and service auth provider by getting the tokens at the start of executing a cron, rather than on every CCD API call
=> Make less idam calls

src/integrationTest/resources/wiremock/responses/about-to-submit-link-applicant-2.json, src/main/java/uk/gov/hmcts/divorce/systemupdate/event/SystemLinkApplicant2.java
Remove state change for SystemLinkApplicant2 
Currently case in AwaitingAos state is being set to AwaitingApplicant2Response when a respondent links to the case
```
[ ] Yes
[x] No
```
=> remove state change for SystemLinkApplicant2

src/integrationTest/java/uk/gov/hmcts/divorce/testutil/FeesWireMock.java, src/main/java/uk/gov/hmcts/divorce/payment/PaymentService.java, src/test/java/uk/gov/hmcts/divorce/payment/PaymentServiceTest.java
no ticket
Fee and Payment team have reverted a change to the keyword for fee lookups on Bailiff Enforcement and Divorce petition fees
```
[ ] Yes
[x] No
```
=> Revert changes to the Bailiff and Divorce service keywords

src/main/java/uk/gov/hmcts/divorce/citizen/notification/Applicant1ResubmitNotification.java, src/test/java/uk/gov/hmcts/divorce/citizen/notification/Applicant1ResubmitNotificationTest.java
- https://tools.hmcts.net/jira/browse/NFDIV-1183
- move content back to template for resubmit notification
- affected template: https://www.notifications.service.gov.uk/services/56f68e5c-b51f-4bdf-a0ac-d70af335e1d1/templates/e0398a62-8900-48d0-baf8-5d73040089ae
```
[ ] Yes
[X] No
```
=> nfdiv-1183: move content back to template

build.gradle, charts/nfdiv-case-api/Chart.yaml, charts/nfdiv-case-api/values.preview.template.yaml, src/integrationTest/java/uk/gov/hmcts/divorce/solicitor/SolicitorCreateApplicationIT.java, src/integrationTest/java/uk/gov/hmcts/divorce/solicitor/SolicitorSubmitApplicationIT.java, src/integrationTest/java/uk/gov/hmcts/divorce/testutil/CaseDataWireMock.java, src/main/java/uk/gov/hmcts/divorce/CaseApiApplication.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/SolicitorCreateApplication.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/SolicitorSubmitApplication.java, src/main/java/uk/gov/hmcts/divorce/solicitor/service/CcdAccessService.java, src/test/java/uk/gov/hmcts/divorce/solicitor/event/SolicitorCreateApplicationTest.java, src/test/java/uk/gov/hmcts/divorce/solicitor/event/SolicitorSubmitApplicationTest.java, src/test/java/uk/gov/hmcts/divorce/solicitor/service/CcdAccessServiceTest.java
- Remove [CREATOR] role when adding [APPONESOLICITOR] role
- Switch roles on submitted hook in solicitor-create-application event instead of aboutToStart of solicitor-submit-case
- Upgrade ccd-client library
- Use Case Assignment API to change user roles to ensure supplementary data for Share a case is set correctly by CCD
As noted on: https://tools.hmcts.net/confluence/display/RCCD/A+Guide+to+Assign+Access+to+cases+for+professional+users%3A+configuration?focusedCommentId=1475839441#comment-1475839441 you must remove the [CREATOR] role before adding the new role or the supplementary data does not get set.
=> Share a case

src/main/java/uk/gov/hmcts/divorce/common/event/SubmitAos.java, src/main/java/uk/gov/hmcts/divorce/common/event/page/Applicant2SolStatementOfTruth.java, src/main/java/uk/gov/hmcts/divorce/common/event/page/SolicitorDetailsWithStatementOfTruth.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/AcknowledgementOfService.java, src/main/java/uk/gov/hmcts/divorce/systemupdate/event/SystemIssueSolicitorAosDisputed.java, src/main/java/uk/gov/hmcts/divorce/systemupdate/event/SystemIssueSolicitorAosUnDisputed.java, src/test/java/uk/gov/hmcts/divorce/common/event/SubmitAosTest.java
https://tools.hmcts.net/jira/browse/NFDIV-1345
- Removed Prayer and statement of truth from `Applicant2SolStatementOfTruth` page as SOT is moved to new page and prayer is removed.
- Added new page `SolicitorDetailsWithStatementOfTruth` as below.
- As part of submitted event created disputed/undisputed event based on how solicitor has chosen to respond.
=> Add solicitor statement of truth page with disputed/undisputed events

src/main/java/uk/gov/hmcts/divorce/divorcecase/tab/ApplicationTab.java
https://tools.hmcts.net/jira/browse/NFDIV-1410
Display respondent contact details in application tab when applicant2KeepContactDetailsConfidential is not set
=> Display respondent contact details when keep confidential is not set

src/main/java/uk/gov/hmcts/divorce/document/content/NoticeOfProceedingContent.java, src/test/java/uk/gov/hmcts/divorce/document/content/NoticeOfProceedingContentTest.java
should be: 'You must tell the court if you’ve [been married to / entered into a civil partnership with] more than one person during this [marriage / civil partnership].'
=> Fix dynamic content for notice of proceedings

src/main/java/uk/gov/hmcts/divorce/systemupdate/event/SystemProgressCaseToAosOverdue.java, src/test/java/uk/gov/hmcts/divorce/systemupdate/event/SystemProgressCaseToAosOverdueTest.java
Fix an issue where AoS reminder email fails if applicant2 email is an empty string. 
Correct logic on when to send applicant1 a reminder that the respondent has not completed the AoS
=> Fix Aos reminder issues

Jenkinsfile_CNP, charts/nfdiv-case-api/values.preview.template.yaml, src/main/java/uk/gov/hmcts/divorce/citizen/event/CitizenUpdateCaseStateAat.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/Applicant.java, src/test/java/uk/gov/hmcts/divorce/citizen/event/CitizenUpdateCaseStateAatTest.java
Remove setting of default access class for solicitor
the access class should already be inherited from the access to the Applicant fields
```
[ ] Yes
[x] No
```
=> Remove setting of default access class for solicitor

src/main/java/uk/gov/hmcts/divorce/divorcecase/model/RetiredFields.java, src/test/java/uk/gov/hmcts/divorce/divorcecase/model/RetiredFieldsTest.java
- https://tools.hmcts.net/jira/browse/NFDIV-1128
- https://tools.hmcts.net/jira/browse/NFDIV-1129
- https://tools.hmcts.net/jira/browse/NFDIV-1130
- reinstate fields deleted in previous commits into the RetiredFields class
```
[ ] Yes
[X] No
```
=> nfdiv-1130: retire fields instead of deleting them

src/functionalTest/resources/request/casedata/ccd-callback-general-order-about-to-submit.json, src/functionalTest/resources/request/casedata/ccd-callback-general-order.json, src/functionalTest/resources/responses/response-caseworker-general-order-mid-event.json, src/integrationTest/java/uk/gov/hmcts/divorce/document/content/GeneralOrderTemplateContentIT.java, src/integrationTest/resources/caseworker-general-order-response.json, src/main/java/uk/gov/hmcts/divorce/caseworker/event/page/CreateGeneralOrder.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/GeneralOrder.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/GeneralOrderJudgeOrLegalAdvisorType.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/RetiredFields.java, src/main/java/uk/gov/hmcts/divorce/document/content/GeneralOrderTemplateContent.java, src/test/java/uk/gov/hmcts/divorce/divorcecase/model/RetiredFieldsTest.java, src/test/java/uk/gov/hmcts/divorce/document/content/GeneralOrderTemplateContentTest.java, src/test/java/uk/gov/hmcts/divorce/testutil/TestDataHelper.java
https://tools.hmcts.net/jira/browse/NFDIV-1235
- Judge type enum includes addition of LA related values. Also Recorder is no more applicable.
- Judge and LA name values have been merged into single field.
- Retired old fields and migration.
=> General order changes including merging of name field and addition/removal to judge type

build.gradle
Bumps org.owasp.dependencycheck from 6.5.0.1 to 6.5.1.
---
updated-dependencies:
- dependency-name: org.owasp.dependencycheck
dependency-type: direct:production
update-type: version-update:semver-patch
...
Signed-off-by: dependabot[bot] <support@github.com>
```
[ ] Yes
[ ] No
```
=> build(deps): bump org.owasp.dependencycheck from 6.5.0.1 to 6.5.1

src/main/java/uk/gov/hmcts/divorce/divorcecase/model/Applicant.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/MarriageDetails.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/MarriageFormation.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/RetiredFields.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/SolAboutApplicant1.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/SolAboutApplicant2.java, src/test/java/uk/gov/hmcts/divorce/solicitor/event/page/SolAboutApplicant1Test.java
- Remove whoDivorcing fields from Applicant
- Make whoDivorcing and gender questions consistent with how they are set by the citizen side
- Fix an issue where Application.whoDivorcing is not set in the CoE for solicitor cases
=> WhoDivorcing and gender fixes for solicitor cases

src/main/java/uk/gov/hmcts/divorce/common/config/jackson/JacksonConfiguration.java, src/main/java/uk/gov/hmcts/divorce/systemupdate/service/CaseDetailsUpdater.java, src/test/java/uk/gov/hmcts/divorce/systemupdate/service/CaseDetailsUpdaterTest.java
https://tools.hmcts.net/jira/browse/NFDIV-1616
Revert add findAndRegisterModules method to autowired Jackson ObjectMapper
Update CaseDetailsUpdater to use new ObjectMapper rather than autowired Jackson ObjectMapper
=> Use new object mapper for class conversion

src/main/java/uk/gov/hmcts/divorce/solicitor/event/SolicitorSubmitJointApplication.java, src/main/java/uk/gov/hmcts/divorce/solicitor/service/SolicitorSubmitJointApplicationService.java, src/test/java/uk/gov/hmcts/divorce/solicitor/event/SolicitorSubmitJointApplicationTest.java, src/test/java/uk/gov/hmcts/divorce/solicitor/service/SolicitorSubmitJointApplicationServiceTest.java
- We cannot autowire a HttpServletRequest in service class where we are using Async aspect as this will tie our aspect to be only runnable for classes that are called from within an executing HttpServletRequest.
=> Move HttpServletRequest to SolicitorSubmitJointApplication as we cannot autowire it in service

src/main/java/uk/gov/hmcts/divorce/common/event/Applicant2Approve.java, src/main/java/uk/gov/hmcts/divorce/common/event/Applicant2RequestChanges.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/Application.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/SolicitorSubmitJointApplication.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/SolStatementOfTruthApplicant2.java, src/main/java/uk/gov/hmcts/divorce/solicitor/service/SolicitorSubmitJointApplicationService.java, src/test/java/uk/gov/hmcts/divorce/solicitor/event/SolicitorSubmitJointApplicationTest.java, src/test/java/uk/gov/hmcts/divorce/solicitor/service/SolicitorSubmitJointApplicationServiceTest.java
- If we configure applicant 2 solicitor  access for `APPLICANT_2_APPROVE` or  `APPLICANT_2_REQUEST_CHANGES` then app2 solicitor will see those in drop down and trigger. Hence configure system user and trigger those asynchronously using system user.
- Remove hidden field financial order as it needs to be shown on Financial order page.
=> Use system user to trigger async event and remove financial order hidden field

src/main/java/uk/gov/hmcts/divorce/common/event/SubmitAos.java, src/main/java/uk/gov/hmcts/divorce/systemupdate/event/SystemIssueAosDisputed.java, src/main/java/uk/gov/hmcts/divorce/systemupdate/event/SystemIssueAosUnDisputed.java, src/test/java/uk/gov/hmcts/divorce/common/event/SubmitAosTest.java, src/test/java/uk/gov/hmcts/divorce/systemupdate/event/SystemIssueAosDisputedTest.java, src/test/java/uk/gov/hmcts/divorce/systemupdate/event/SystemIssueAosUnDisputedTest.java
These events are triggered for citizen and solicitor cases so I've removed solicitor from the event ID
=> Remove solicitor from disputed and undisputed event names

src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerNoticeOfChange.java, src/main/java/uk/gov/hmcts/divorce/common/event/CreateTestCase.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/CaseData.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/NoticeOfChange.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/UserRole.java, src/main/java/uk/gov/hmcts/divorce/solicitor/service/CcdAccessService.java, src/main/resources/data/joint.json, src/main/resources/data/sole.json, src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerNoticeOfChangeTest.java, src/test/java/uk/gov/hmcts/divorce/solicitor/service/CcdAccessServiceTest.java
https://tools.hmcts.net/jira/browse/NFDIV-1654
This PR adds an event that allows a caseworker or admin to trigger Notice of Change when a case is in any state. The notice of change will remove all access to the case for one of the applicants and optionally replace the organisation policy of another solicitor organisation has taken the case over. Unless another digital solicitor will take over the case the applicant will be marked as offline.
=> NFDIV-1654 Notice of change

build.gradle, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/CaseData.java, src/main/java/uk/gov/hmcts/divorce/systemupdate/event/SystemAttachScannedDocuments.java, src/main/java/uk/gov/hmcts/divorce/systemupdate/event/SystemHandleSupplementaryEvidence.java
Labels are now optional. Where possible we should use labels defined in the event. The `@CCD` is also optional if no other options are required.
=> remove label

build.gradle
By declaring task inputs and outputs, so that Gradle will not run the task if the generateCCDConfig task is up to date.
More work remains todo in the config generator to generate deterministic (ie. sorted) json, so that we only rebuild the xls if there is an actual config change.
=> Fix Gradle up-to-date checks on buildCCDXlsx

charts/nfdiv-case-api/Chart.yaml, src/integrationTest/java/uk/gov/hmcts/divorce/endpoint/BulkScanCaseTransformationControllerIT.java, src/integrationTest/resources/transformation-success-response.json, src/main/java/uk/gov/hmcts/divorce/bulkscan/transformation/PaperFormDetailsTransformer.java, src/main/java/uk/gov/hmcts/divorce/bulkscan/validation/data/OcrDataFields.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/PaperFormDetails.java, src/test/java/uk/gov/hmcts/divorce/bulkscan/transformation/ApplicationTransformerTest.java, src/test/java/uk/gov/hmcts/divorce/bulkscan/validation/OcrValidatorTest.java, src/test/resources/transformation/input/valid-application-ocr-with-null-values.json, src/test/resources/transformation/input/valid-paper-form-ocr.json, src/test/resources/transformation/output/paper-form-transformed.json
- OCR fields are converted to null when invoked from an exception record. Handle this as `Collector.toMap` doesn't allow null values and we need to retain the keys in the map.
- Added transformation for missing fields.
=> Fix nullpointer during transformation and added missing fields

src/functionalTest/java/uk/gov/hmcts/divorce/systemupdate/event/SystemProgressHeldCasesFT.java
Reverts hmcts/nfdiv-case-api#1423
=> Revert "Disabled Elastic search functional test due to ccd limitation of 10K cases"

src/main/java/uk/gov/hmcts/divorce/divorcecase/model/FinalOrder.java, src/main/java/uk/gov/hmcts/divorce/systemupdate/schedule/SystemNotifyRespondentApplyFinalOrderTask.java
https://tools.hmcts.net/jira/browse/NFDIV-1622
- NFDIV-1622 is broken because the reminderSent field isn't being set and so the cron job is always picking up the same 100 cases.
```
[ ] Yes
[X] No
```
=> Correct logging name and add default access to finalOrderReminderSent fields

src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerAlternativeServiceApplication.java, src/main/java/uk/gov/hmcts/divorce/citizen/notification/GeneralApplicationReceivedNotification.java, src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerAlternativeServiceApplicationTest.java, src/test/java/uk/gov/hmcts/divorce/citizen/notification/GeneralApplicationReceivedNotificationTest.java
https://tools.hmcts.net/jira/browse/NFDIV-1736
As per NFDIV-1736, the notification should only be sent to
applicant 1 and will always be sent regardless of if they
are logged in or not. Reworked logic to always send notification.
```
[ ] Yes
[X] No
```
=> Remove sending notification to applicant 2 / respondent

src/main/java/uk/gov/hmcts/divorce/bulkscan/exception/InvalidOcrDataException.java, src/main/java/uk/gov/hmcts/divorce/bulkscan/transformation/D8FormToCaseTransformer.java, src/main/java/uk/gov/hmcts/divorce/bulkscan/transformation/D8sFormToCaseTransformer.java, src/main/java/uk/gov/hmcts/divorce/common/config/advice/GlobalExceptionHandler.java, src/test/java/uk/gov/hmcts/divorce/bulkscan/transformation/D8FormToCaseTransformerTest.java, src/test/java/uk/gov/hmcts/divorce/bulkscan/transformation/D8sFormToCaseTransformerTest.java
- During transformation if there are OCR validation errors then we need to return 200 rather than 422 so that warnings are displayed in warning tab. 
- Returning 422 makes bulk scan service display generic message on warnings tab.
=> Fix ocr validation response during transformation if there are validation errors- D8 & D8S

build.gradle, src/main/java/uk/gov/hmcts/divorce/notification/GetAllTemplatesFromNotify.java
https://tools.hmcts.net/jira/browse/NFDIV-1677
This class will allow us to search the Notify email templates for a specific template value or for a specific string within the body of the email template.
```
[ ] Yes
[X] No
```
=> NFDIV-1677 Add new util class to allow us to retrieve all email templates that match a search criteria

src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerNoticeOfChange.java
When doing a NoC the address for the applicant not selected disappears because we aren't using the RetainHiddenValue field (yet) so CCD will wipe the value.
=> fix missing address when doing NoC

src/integrationTest/resources/d8-transformation-success-response.json, src/integrationTest/resources/d8s-transformation-success-response.json, src/integrationTest/resources/transformation-success-warning-response.json, src/main/java/uk/gov/hmcts/divorce/bulkscan/transformation/Applicant2Transformer.java, src/main/java/uk/gov/hmcts/divorce/bulkscan/transformation/MarriageDetailsTransformer.java, src/test/resources/transformation/output/applicant2-transformed-warnings.json, src/test/resources/transformation/output/applicant2-transformed.json
- When creating local date for marriage date pass the month and day parameter in correct order.
- When checking solicitor name to derive if applicant 2 is represented include empty as well otherwise if values is empty it is being treated as solicitor is represented.
=> Fix marriage date parsing and include empty check for solicitor name

src/integrationTest/java/uk/gov/hmcts/divorce/citizen/event/CitizenSubmitApplicationIT.java, src/main/java/uk/gov/hmcts/divorce/common/service/task/SendCitizenSubmissionNotifications.java, src/test/java/uk/gov/hmcts/divorce/common/service/task/SendCitizenSubmissionNotificationsTest.java
- https://tools.hmcts.net/jira/browse/NFDIV-1833
- prevent application-submitted notifications if AwaitingHWFDecision
```
[ ] Yes
[X] No
```
=> nfdiv-1833: prevent awaitingHWFDecision state notification

src/main/java/uk/gov/hmcts/divorce/bulkscan/transformation/ApplicationTransformer.java, src/test/java/uk/gov/hmcts/divorce/bulkscan/transformation/ApplicationTransformerTest.java
https://tools.hmcts.net/jira/browse/NFDIV-2007
When jurisdictionReasonsJointHabitualWho has a value other thank blank,
then add that jurisdiction connection even if jurictionReasonsJointHabitual is
marked as false.
```
[ ] Yes
[X] No
```
=> Bug fix - field jurisdictionReasonsJointHabitualWho not being set correctly

src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerAlternativeServiceApplication.java, src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerAlternativeServiceApplicationTest.java
N/A
An error is showing in our test environment where it is missing
the applicants email address when sending a notification to applicant1.
After looking through the code we shouldn't call to send to applicant1
directly but rather wrap the call in the notificationDispatcher.
```
[ ] Yes
[X] No
```
=> Wrap send to applicant1 notification with notificationDispatcher

src/main/java/uk/gov/hmcts/divorce/caseworker/event/page/CorrectPaperCase.java
=> Fix missing condition to display applicant 2 financial orders on correct paper case

src/main/java/uk/gov/hmcts/divorce/solicitor/event/SolicitorCreateApplication.java, src/test/java/uk/gov/hmcts/divorce/solicitor/event/SolicitorCreateApplicationTest.java
- return an error if applicationType is null (xui refresh issue), to avoid NPE  
=>  return an error if applicationType is null (xui refresh issue), to avoid NPE

src/integrationTest/java/uk/gov/hmcts/divorce/caseworker/CaseworkerOfflineDocumentVerifiedIT.java, src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerOfflineDocumentVerified.java
- Currently when Offline document verified event is triggered by the caseworker and document is AOS D10 then state is not transitioned as the task checks the status of case is AosDrafted.
- We are now setting it to AosDrafted once the scanned document is reclassified as D10.
- Integration test was passing as it was passing incorrect state in the request which is now fixed.
https://tools.hmcts.net/jira/browse/NFDIV-2319
=> Fix state transition when AOS documents is received and classified by  caseworker

charts/nfdiv-case-api/values.preview.template.yaml
[Frontend is creating ](https://github.com/hmcts/nfdiv-frontend/blob/master/charts/nfdiv-frontend/values.yaml) an addiional DNS , this shouldn't be needed in preview. If needed, it has to be .internal . Currently its created as .aat.platform.hmcts.net.
=> Remove additional DNS for frontend

charts/nfdiv-case-api/Chart.yaml, charts/nfdiv-case-api/values.preview.template.yaml
CFT have patched ingress on our elasticsearch chart. This is in relation to the ongoing cluster upgrades across all environments. We need teams using the chart-ccd chart to bump the chart version to 8.0.17CFT have patched ingress on our elasticsearch chart. This is in relation to the ongoing cluster upgrades across all environments. We need teams using the chart-ccd chart to bump the chart version to 8.0.17
=> Update ccd chart as ingress has been patched on Elasticsearch charts

src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerConfirmAlternativeService.java, src/main/java/uk/gov/hmcts/divorce/common/event/DraftConditionalOrder.java, src/main/java/uk/gov/hmcts/divorce/common/event/UpdateConditionalOrder.java, src/main/java/uk/gov/hmcts/divorce/common/event/page/ConditionalOrderReviewAoS.java, src/main/java/uk/gov/hmcts/divorce/common/service/task/SetServiceConfirmed.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/CaseDocuments.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/ConditionalOrder.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/tab/CaseTypeTab.java, src/main/java/uk/gov/hmcts/divorce/solicitor/service/SolicitorSubmitConfirmService.java, src/main/java/uk/gov/hmcts/divorce/solicitor/service/task/AddOfflineRespondentAnswersLink.java, src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerConfirmAlternativeServiceTest.java, src/test/java/uk/gov/hmcts/divorce/common/event/DraftConditionalOrderTest.java, src/test/java/uk/gov/hmcts/divorce/common/event/UpdateConditionalOrderTest.java, src/test/java/uk/gov/hmcts/divorce/common/service/task/SetServiceConfirmedTest.java, src/test/java/uk/gov/hmcts/divorce/divorcecase/model/CaseDocumentsTest.java, src/test/java/uk/gov/hmcts/divorce/solicitor/service/SolicitorSubmitConfirmServiceTest.java, src/test/java/uk/gov/hmcts/divorce/solicitor/service/task/AddOfflineRespondentAnswersLinkTest.java
Set serviceConfirmed field to Yes on caseworker-confirm-alternative-service event
Set serviceConfirmed field to Yes on caseworker-confirm-service event
Show uploading of proof of service document on draft-conditional-order event when serviceConfirmed field is set
Change draft-conditional-order event page name to 'Draft Conditional Order'
https://tools.hmcts.net/jira/browse/NFDIV-2332
=> Handle confirm service and confirm alternative service in draft CO

src/integrationTest/resources/caseworker-reissue-application-about-to-submit-app2-not-sol-rep-response.json, src/main/java/uk/gov/hmcts/divorce/caseworker/service/ReIssueApplicationService.java, src/test/java/uk/gov/hmcts/divorce/caseworker/service/ReIssueApplicationServiceTest.java
Currently when reissueOption was selected as offline and when it is changed to digital then the case can't progress due to the offline flag set to Yes. With the change, for digital AoS, the offline flag needs to be set to No so the case can progress. Also updated unit and integration tests.
https://tools.hmcts.net/jira/browse/NFDIV-2520
=> NFDIV-2520: Set offline to No for digital AoS

src/integrationTest/java/uk/gov/hmcts/divorce/citizen/event/CitizenSwitchedToSoleCoIT.java, src/main/java/uk/gov/hmcts/divorce/citizen/notification/Applicant2SwitchToSoleCoNotification.java, src/test/java/uk/gov/hmcts/divorce/citizen/notification/Applicant2SwitchToSoleCoNotificationTest.java
> Currently when applicant 2 is citizen and applicant 1 is represented and if applicant 2 switches to sole then no notification is sent to applicant 2 solicitor(previously applicant 1 solicitor). This PR add notification to applicant 2 solicitor.
https://tools.hmcts.net/jira/browse/NFDIV-2811
=> Added solicitor notification when app2 switches to sole and app1 is represented

src/main/java/uk/gov/hmcts/divorce/systemupdate/event/SystemAttachScannedDocuments.java
https://tools.hmcts.net/jira/browse/NFDIV-2921
=> Removed history access for solicitors for attach scanned docs to restrict viewing confidential docs

src/integrationTest/java/uk/gov/hmcts/divorce/bulkaction/service/CasePronouncementServiceIT.java, src/main/java/uk/gov/hmcts/divorce/bulkaction/ccd/event/CaseworkerPronounceList.java, src/main/java/uk/gov/hmcts/divorce/bulkaction/ccd/event/CaseworkerRetryPronounceList.java, src/main/java/uk/gov/hmcts/divorce/bulkaction/service/CasePronouncementService.java, src/test/java/uk/gov/hmcts/divorce/bulkaction/ccd/event/CaseworkerPronounceListTest.java, src/test/java/uk/gov/hmcts/divorce/bulkaction/ccd/event/CaseworkerRetryPronounceListTest.java, src/test/java/uk/gov/hmcts/divorce/bulkaction/service/CasePronouncementServiceTest.java
-  I had a look at the issue and it is due to incorrect credentials used in the code(instead of system user it is using caseworker credentials) and hence it is failing to trigger system pronounce case on individual cases.
- For cases on which Pronounce list is already triggered bulk case state has moved to pronounced so we need a backward fix. For this I created retry event where it allows superusers to retry "Pronounce List" event on bulk case in Pronounced state. 
- This will only retry system pronounce case event on NFD cases within the bulk list and no dates9hearing and final order eligible from) will be updated.
https://tools.hmcts.net/jira/browse/NFDIV-3037
=> Use system user creds for pronounce case and add retry event for pronounce list

src/main/java/uk/gov/hmcts/divorce/idam/IdamService.java
- Currently Idam token are cached when running functional tests but when functional tests are executed they are executed against main app which also generates system user token.
- This PR conditionally only does caching for Idam token in AAT and preview as for production we don't intent to do caching as of now.
=> Enable idam token caching for preview and AAT

build.gradle, src/functionalTest/java/uk/gov/hmcts/divorce/testutil/IdamTokenGenerator.java, src/main/java/uk/gov/hmcts/divorce/idam/IdamService.java
- Currently if AAT or preview pods are not refreshed due to new commits not being added and if pods are up for more than 8 hours then existing implementation will return expired tokens which is causing front end pipeline to fail.
- This implementation removes expires token after 2 hours or adding token.
=> Use expiring caffeine cache to remove expired tokens

src/main/java/uk/gov/hmcts/divorce/systemupdate/event/SystemRemoveBulkCase.java
- Currently caseworker triggering remove cases from bulk list is failing to unlink as the event system-remove-bulk-case is configured for system update user.
- There will be a separate PR to fix authorisation token passed from remove cases from bulk list to system-remove-bulk-case so that instead of logged in user token it uses system update user token.
- This PR allows super user to trigger system-remove-bulk-case event for prod cases in prod.
=> Add super user to remove bulk case link from NFD case

src/main/java/uk/gov/hmcts/divorce/systemupdate/event/SystemMigrateCaseWithCoEGeneration.java, src/main/java/uk/gov/hmcts/divorce/systemupdate/schedule/migration/CaseCourtHearingMigration.java, src/main/java/uk/gov/hmcts/divorce/systemupdate/schedule/migration/SetAosIsDraftedToYesMigration.java, src/main/java/uk/gov/hmcts/divorce/systemupdate/schedule/migration/SetCaseCourtHearingBulkAction.java, src/main/java/uk/gov/hmcts/divorce/systemupdate/schedule/migration/predicate/CaseCourtHearingPredicate.java, src/main/java/uk/gov/hmcts/divorce/systemupdate/schedule/migration/predicate/HasAosDraftedEventPredicate.java, src/main/java/uk/gov/hmcts/divorce/systemupdate/schedule/migration/task/CaseCourtHearingTaskProvider.java, src/test/java/uk/gov/hmcts/divorce/systemupdate/event/SystemMigrateCaseWithCoEGenerationTest.java, src/test/java/uk/gov/hmcts/divorce/systemupdate/schedule/migration/CaseCourtHearingMigrationTest.java, src/test/java/uk/gov/hmcts/divorce/systemupdate/schedule/migration/SetAosIsDraftedToYesMigrationTest.java, src/test/java/uk/gov/hmcts/divorce/systemupdate/schedule/migration/SetCaseCourtHearingBulkActionTest.java, src/test/java/uk/gov/hmcts/divorce/systemupdate/schedule/migration/predicate/CaseCourtHearingPredicateTest.java, src/test/java/uk/gov/hmcts/divorce/systemupdate/schedule/migration/predicate/HasAosDraftedEventPredicateTest.java, src/test/java/uk/gov/hmcts/divorce/systemupdate/schedule/migration/task/CaseCourtHearingTaskProviderTest.java
Add cron migration for setting court hearing info on bulk action cases.
Uses: 
MIGRATE_AOS_IS_DRAFTED=true
AOS_IS_DRAFTED_REFERENCES={comma delimited list of case references}
https://tools.hmcts.net/jira/browse/NFDIV-3125
=> Add migration for setting court hearing on bulk action cases

src/main/java/uk/gov/hmcts/divorce/systemupdate/event/SystemPronounceCase.java
- Currently if the system trigger for pronounce case fails and if it also fails to update bulk case with failed list there is no way to retry the pronounce case on NFD case.
- This PR allows super user to trigger pronounce case so that appropriate documents can be generated and case can be updated.
https://tools.hmcts.net/jira/browse/NFDIV-3139
=> Allow superusers to trigger system pronounce case in case pronounce case events fails when triggered by system

src/functionalTest/resources/application.yaml, src/integrationTest/java/uk/gov/hmcts/divorce/caseworker/CaseworkerReIssueApplicationIT.java, src/integrationTest/java/uk/gov/hmcts/divorce/citizen/notification/conditionalorder/AppliedForConditionalOrderNotificationIT.java, src/integrationTest/java/uk/gov/hmcts/divorce/common/Applicant2RequestChangesNotificationIT.java, src/integrationTest/java/uk/gov/hmcts/divorce/common/GeneralApplicationReceivedNotificationIT.java, src/integrationTest/java/uk/gov/hmcts/divorce/common/SoleApplicationDisputedNotificationIT.java, src/integrationTest/java/uk/gov/hmcts/divorce/common/SoleApplicationNotDisputedNotificationIT.java, src/integrationTest/java/uk/gov/hmcts/divorce/document/content/CertificateOfEntitlementContentIT.java, src/integrationTest/java/uk/gov/hmcts/divorce/document/content/GeneralOrderTemplateContentIT.java, src/integrationTest/java/uk/gov/hmcts/divorce/document/content/NoticeOfProceedingContentIT.java, src/integrationTest/java/uk/gov/hmcts/divorce/document/content/NoticeOfProceedingJointContentIT.java, src/integrationTest/java/uk/gov/hmcts/divorce/document/content/ServiceOrderTemplateContentIT.java, src/integrationTest/resources/application.yaml, src/main/java/uk/gov/hmcts/divorce/document/content/AosResponseLetterTemplateContent.java, src/main/java/uk/gov/hmcts/divorce/document/content/DocmosisCommonContent.java, src/main/java/uk/gov/hmcts/divorce/document/content/DocmosisTemplateConstants.java, src/main/java/uk/gov/hmcts/divorce/document/content/NoticeOfProceedingContent.java, src/main/java/uk/gov/hmcts/divorce/document/content/NoticeOfProceedingJointContent.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/divorce/document/content/AosResponseLetterTemplateContentTest.java, src/test/java/uk/gov/hmcts/divorce/document/content/CertificateOfEntitlementContentTest.java, src/test/java/uk/gov/hmcts/divorce/document/content/ConditionalOrderPronouncedTemplateContentTest.java, src/test/java/uk/gov/hmcts/divorce/document/content/DocmosisCommonContentTest.java, src/test/java/uk/gov/hmcts/divorce/document/content/NoticeOfProceedingContentTest.java, src/test/java/uk/gov/hmcts/divorce/document/content/NoticeOfProceedingJointContentTest.java, src/test/java/uk/gov/hmcts/divorce/legaladvisor/service/task/GenerateCoRefusedCoverLetterTest.java, src/test/java/uk/gov/hmcts/divorce/systemupdate/service/print/CertificateOfEntitlementPrinterTest.java, src/test/java/uk/gov/hmcts/divorce/systemupdate/service/task/ConditionalOrderPronouncedCoverLetterHelperTest.java, src/test/java/uk/gov/hmcts/divorce/systemupdate/service/task/GenerateCertificateOfEntitlementTest.java, src/test/java/uk/gov/hmcts/divorce/testutil/TestDataHelper.java
At the moment, multiple placeholders are defined in multiple classes to have references to the same email address. This PR removes all the others and only refers to the Docmosis commone content class for the email address. 
https://tools.hmcts.net/jira/browse/NFDIV-3200
=> NFDIV-3200: Update code to have one reference to the email address

charts/nfdiv-case-api/Chart.yaml
NFD pipeline builds are failing on deployment tasks as java chart is deprecated. Upgrading to suggested version of 4.0.8 as per the logs on the jenkins pipeline.
N/A
=> Bump java chart to 4.0.9 as 4.0.6 is now depreciated

src/main/java/uk/gov/hmcts/divorce/document/content/ConditionalOrderRefusedForAmendmentContent.java, src/main/java/uk/gov/hmcts/divorce/legaladvisor/service/printer/AwaitingAmendedApplicationPrinter.java
Saw in prod logs we had some NPE around using judicial separation toBoolean method, but JS can be null so changed it to be null safe.
N/A - Azure prod logs.
=> Change use of toBoolean to equals method to handle null values

config/owasp/suppressions.xml
Suppress CVE-2023-24998 for the time being, due to lack of updates for deps which import Apache Commons FileUpload.
=> Add suppression for CVE-2023-24998

src/main/java/uk/gov/hmcts/divorce/systemupdate/schedule/migration/BaseMigration.java, src/main/java/uk/gov/hmcts/divorce/systemupdate/schedule/migration/ConfirmReadPetitionMigration.java, src/main/java/uk/gov/hmcts/divorce/systemupdate/schedule/migration/JointApplicationMigration.java, src/main/java/uk/gov/hmcts/divorce/systemupdate/schedule/migration/PaperApplicationMigration.java, src/main/java/uk/gov/hmcts/divorce/systemupdate/schedule/migration/SetAosIsDraftedToYesMigration.java, src/main/java/uk/gov/hmcts/divorce/systemupdate/schedule/migration/task/MigrateRetiredFields.java, src/main/java/uk/gov/hmcts/divorce/systemupdate/schedule/migration/task/RemoveAccessCode.java, src/main/java/uk/gov/hmcts/divorce/systemupdate/schedule/migration/task/SetFailedMigrationVersionToZero.java, src/main/java/uk/gov/hmcts/divorce/systemupdate/schedule/migration/task/UpdateAosIsDrafted.java, src/main/java/uk/gov/hmcts/divorce/systemupdate/schedule/migration/task/UpdateApplicant2Offline.java, src/main/java/uk/gov/hmcts/divorce/systemupdate/schedule/migration/task/UpdateConfirmReadPetitionFields.java, src/test/java/uk/gov/hmcts/divorce/systemupdate/schedule/migration/BaseMigrationTest.java, src/test/java/uk/gov/hmcts/divorce/systemupdate/schedule/migration/ConfirmReadPetitionMigrationTest.java, src/test/java/uk/gov/hmcts/divorce/systemupdate/schedule/migration/JointApplicationMigrationTest.java, src/test/java/uk/gov/hmcts/divorce/systemupdate/schedule/migration/PaperApplicationMigrationTest.java, src/test/java/uk/gov/hmcts/divorce/systemupdate/schedule/migration/SetAosIsDraftedToYesMigrationTest.java, src/test/java/uk/gov/hmcts/divorce/systemupdate/schedule/migration/task/MigrateRetiredFieldsTest.java, src/test/java/uk/gov/hmcts/divorce/systemupdate/schedule/migration/task/RemoveAccessCodeTest.java, src/test/java/uk/gov/hmcts/divorce/systemupdate/schedule/migration/task/SetFailedMigrationVersionToZeroTest.java, src/test/java/uk/gov/hmcts/divorce/systemupdate/schedule/migration/task/UpdateAosIsDraftedTest.java, src/test/java/uk/gov/hmcts/divorce/systemupdate/schedule/migration/task/UpdateApplicant2OfflineTest.java, src/test/java/uk/gov/hmcts/divorce/systemupdate/schedule/migration/task/UpdateConfirmReadPetitionFieldsTest.java
NFD team has been made aware that the way we call the CCD API may not be concurrent safe. Updating all migrations to be concurrent safe by using the startEventResponse caseDetails instead of passing our own caseDetails in from the Ccd Search Service.
https://tools.hmcts.net/jira/browse/NFDIV-3318
https://tools.hmcts.net/jira/browse/NFDIV-3309
=> NFDIV-3318 - Fix migrations ccd issue

src/main/java/uk/gov/hmcts/divorce/caseworker/event/page/CorrectPaperCase.java
As per story, applicant2's prayer was not showing on the Correct Paper Case event. Adding it in as it is required in a joint application for JS & Separation.
https://tools.hmcts.net/jira/browse/NFDIV-3465
=> NFDIV-3465 - Add applicant2 JS and Separation prayers

bin/generate-ccd-definition.sh
Remove user param from docker run call in generate-ccd-definition.sh.
This prevents the inaccessible ./cache folder issue when running the definition processor.
=> Fix generate-ccd-definition.sh

src/functionalTest/resources/responses/response-solicitor-payment-mid-event.json, src/integrationTest/resources/caseworker-offline-document-about-to-start-response.json, src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerOfflineDocumentVerified.java, src/main/java/uk/gov/hmcts/divorce/solicitor/client/pba/PbaService.java
Fix Dynamic List serialisation issue - occurring for both pbaNumbers and scanned Document Names
Caused by setting a default value for the selected element which allowed users to progress to event submission without selecting an item from the dropdown. When clicking submit in these conditions, the exception is thrown.
Fixed by removing the default selected value for the dynamic list
https://tools.hmcts.net/jira/browse/NFDIV-3568
=> Fix Dynamic List serialisation issue

charts/nfdiv-case-api/Chart.yaml, charts/nfdiv-case-api/values.yaml, src/main/resources/application.yaml
Set graceful shutdown with a 2m timeout to avoid deployments shutting down the service while it is processing bulk cases.
https://tools.hmcts.net/jira/browse/NFDIV-3608
=> Set graceful shutdown with a 2m timeout

charts/nfdiv-case-api/Chart.yaml, charts/nfdiv-case-api/values.yaml, src/functionalTest/resources/application.yaml, src/integrationTest/resources/application.yaml, src/main/java/uk/gov/hmcts/divorce/systemupdate/service/CcdSearchService.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/divorce/systemupdate/service/CcdSearchServiceTest.java
This change will
- Limit the total number of cases returned from a CCD search query
- Reduce the page size from 100 to 50
In order to prevent the create bulk action task cron jobs from tripping over each other and assigning cases to multiple bulk action cases.
=> Limit the total number of cases returned from a CCD search query

src/main/java/uk/gov/hmcts/divorce/systemupdate/event/SystemPronounceCase.java
Clean up as it doesnt make sense to use the forStateTransition call with the end state being a set.
https://tools.hmcts.net/jira/browse/NFDIV-3767
=> Clean up state condition for event

src/main/java/uk/gov/hmcts/divorce/bulkaction/ccd/event/SuperuserRemoveErroredCases.java, src/test/java/uk/gov/hmcts/divorce/bulkaction/ccd/event/SuperuserRemoveErroredCasesTest.java
There are numerous bulk cases that have cases in the errored list that have been completed. This means the bulk case crons have been continually retrying to progress the cases for months.
This event will allow super users to manually remove cases from the errored list when cases have been progressed manually.
https://tools.hmcts.net/jira/browse/NFDIV-3767
=> Add event to remove errored cases from list

src/main/java/uk/gov/hmcts/divorce/caseworker/service/print/AosOverduePrinter.java, src/main/java/uk/gov/hmcts/divorce/caseworker/service/print/AosPackPrinter.java, src/main/java/uk/gov/hmcts/divorce/caseworker/service/print/AppliedForCoPrinter.java, src/main/java/uk/gov/hmcts/divorce/caseworker/service/print/FinalOrderGrantedPrinter.java, src/main/java/uk/gov/hmcts/divorce/caseworker/service/print/RegenerateCourtOrdersPrinter.java, src/main/java/uk/gov/hmcts/divorce/caseworker/service/print/SwitchToSoleCoPrinter.java, src/main/java/uk/gov/hmcts/divorce/document/DocumentUtil.java, src/main/java/uk/gov/hmcts/divorce/document/print/BulkPrintService.java, src/main/java/uk/gov/hmcts/divorce/systemupdate/service/print/ApplyForConditionalOrderPrinter.java, src/main/java/uk/gov/hmcts/divorce/systemupdate/service/print/ApplyForFinalOrderPrinter.java, src/main/java/uk/gov/hmcts/divorce/systemupdate/service/print/ConditionalOrderPronouncedPrinter.java, src/main/java/uk/gov/hmcts/divorce/systemupdate/service/print/ConditionalOrderReminderPrinter.java, src/test/java/uk/gov/hmcts/divorce/caseworker/service/print/AosPackPrinterTest.java, src/test/java/uk/gov/hmcts/divorce/document/DocumentUtilTest.java
Move all uses of `lettersWithDocumentType` over to `getLettersBasedOnContactPrivacy` to ensure the correct coversheets are selected.
=> Quick fix for confidentiality

src/main/java/uk/gov/hmcts/divorce/document/model/ConfidentialDocumentsReceived.java, src/main/java/uk/gov/hmcts/divorce/document/model/DocumentType.java
We found that 2 enums shared the same JsonProperties. I've looked at the 2 cases which have used this cover letter, both have:
"Judicial Separation order refusal cover letter".
I believe we can safely edit the clarification jsonProperty as it appears to be unused.
https://tools.hmcts.net/jira/browse/NFDIV-TBC
=> Fix enum jsonProperty which was duplicated

src/main/java/uk/gov/hmcts/divorce/document/CaseDocumentAccessManagement.java, src/test/java/uk/gov/hmcts/divorce/document/CaseDocumentAccessManagementTest.java
CDAM returning 404 but this can be ignored as document has already been deleted.
=> Ignore 404 returned from CDAM as document already deleted

src/integrationTest/java/uk/gov/hmcts/divorce/caseworker/CaseworkerConfirmServiceIT.java, src/integrationTest/java/uk/gov/hmcts/divorce/solicitor/SolicitorConfirmServiceIT.java, src/main/java/uk/gov/hmcts/divorce/solicitor/service/task/SetConfirmServiceDueDate.java, src/test/java/uk/gov/hmcts/divorce/solicitor/service/task/SetConfirmServiceDueDateTest.java
NFDIV-3839: Do not set dueDate if AOS already submitted
https://tools.hmcts.net/jira/browse/NFDIV-3839
=> NFDIV-3839: Do not set dueDate if AOS already submitted

src/main/java/uk/gov/hmcts/divorce/divorcecase/tab/CaseTypeTab.java
Service team have raised concerns about the tab in production. We can't show it to super users. Commenting so we can spend time to maybe get a "developer" role for our team to use the tab.
=> NFDIV - Hide letter pack tab

src/main/java/uk/gov/hmcts/divorce/systemupdate/event/SystemLinkWithBulkCase.java
Had a meeting with the service team. The new State InBulkActionCase needs further considerations before it can be used correctly.
Keeping state in code but reverting the transition to the new state to go back to old behaviour while we work on it further.
https://tools.hmcts.net/jira/browse/NFDIV-3824
=> NFDIV-3824 - Revert to use AwaitingPronouncement

src/main/java/uk/gov/hmcts/divorce/common/event/SwitchedToSoleCo.java, src/main/java/uk/gov/hmcts/divorce/common/event/SwitchedToSoleFinalOrder.java
When a retry is triggered by CCD on a switch to sole event which was originally triggered by applicant2, the isApplicant2 check fails and no roles / data are swapped. We want to disable the retry to avoid this.
https://tools.hmcts.net/jira/browse/NFDIV-3899
=> NFDIV-3899 - No retry on switch to sole events

src/main/java/uk/gov/hmcts/divorce/document/content/ConditionalOrderPronouncedTemplateContent.java
INC5627697 - it looks like we started doing a confidential check here by mistake in NFDIV-3878, which causes the address to be set as null in letters when a litigant is confidential.
https://tools.hmcts.net/jira/browse/NFDIV-4139
=> [NFDIV-4139] Stop confidential address check when getting address for CO pronounced template variables

src/integrationTest/java/uk/gov/hmcts/divorce/noticeofchange/event/SystemApplyNoticeOfChangeIT.java, src/integrationTest/java/uk/gov/hmcts/divorce/testutil/ManageCaseAssignmentWireMock.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/Applicant.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/Solicitor.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/util/SolicitorAddressPopulator.java, src/main/java/uk/gov/hmcts/divorce/noticeofchange/service/ChangeOfRepresentativeService.java, src/main/java/uk/gov/hmcts/divorce/solicitor/event/SolicitorSubmitJointApplication.java, src/main/java/uk/gov/hmcts/divorce/solicitor/service/task/SetApplicant1SolicitorAddress.java, src/test/java/uk/gov/hmcts/divorce/noticeofchange/ChangeOfRepresentativeServiceTest.java
Common component NoC update to start automatically populating the sol address and blanking out old sol details when the new sol is assigned to a case.
https://tools.hmcts.net/jira/browse/NFDIV-4221
=> [NFDIV-4221] Set solicitor firm address during common component NoC

src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerResetConditionalOrderFlags.java, src/main/java/uk/gov/hmcts/divorce/common/service/task/ResetConditionalOrderFlags.java, src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerResetConditionalOrderFlagsTest.java, src/test/java/uk/gov/hmcts/divorce/common/service/task/ResetConditionalOrderFlagsTest.java
We've been asked to introduce a new event for caseworkers/superusers to reset conditional order flags. This will allow them to prepare the case data for submission of a second conditional order.
https://tools.hmcts.net/jira/browse/NFDIV-4255
=> [NFDIV-4255] New event to reset conditional order drafted and submitted flags

.github/renovate.json, Jenkinsfile_nightly, build.gradle
Corrections to nightly CI config to get Fortify scans to work. Fortify client has also been downgraded to a version that is compatible with Java 17
https://tools.hmcts.net/jira/browse/NFDIV-4291
=> [NFDIV-4291] Use correct product and component names in nightly CI

src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerGeneralEmail.java, src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerPrepareGeneralEmailAttachments.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/GeneralEmail.java, src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerGeneralEmailTest.java, src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerPrepareGeneralEmailAttachmentsTest.java
CTSC wants ability to select general order documents in the prepare email attachments event for general email.
Also the fix for NFDIV-4297 is extended so as to remove stale data if a confidential general email was previously successfully sent.
https://tools.hmcts.net/jira/browse/NFDIV-4301
=> NFDIV-4301 Add General Order documents for selection in general email.

build.gradle
Reverts hmcts/nfdiv-case-api#3998
https://tools.hmcts.net/jira/browse/NFDIV-4326
We've been seeing errors in the logs due to failing crons since this was merged by dependabot:
```
java.lang.NoSuchMethodError: 'java.util.stream.Stream org.apache.logging.log4j.util.ServiceLoaderUtil.loadServices(java.lang.Class, java.lang.invoke.MethodHandles$Lookup, boolean)'
at org.apache.logging.log4j.core.impl.ThreadContextDataInjector.getServiceProviders(ThreadContextDataInjector.java:81)
at org.apache.logging.log4j.core.impl.ThreadContextDataInjector.<clinit>(ThreadContextDataInjector.java:68)
at org.apache.logging.log4j.core.impl.ThreadContextDataInjector$ForDefaultThreadContextMap.<init>(ThreadContextDataInjector.java:97)
at org.apache.logging.log4j.core.impl.ContextDataInjectorFactory.createDefaultI …
```
=> [NFDIV-4326] Revert "Update log4j2 monorepo to v2.24.0"

build.gradle
Dependabot tried to update log4j-api and log4j-to-slf4j to v2.24.0 this morning, which resulted in errors in the logs every time a cron started. I've reproduced the issue locally and it seems to be caused by dependencies which use old versions of log4j-core and specifying a version for log4j-core that's compatible with the other log4j dependencies avoids the errors
https://tools.hmcts.net/jira/browse/NFDIV-4326
=> [NFDIV-4326] Update log4j to 2.24.0

src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerResponseToServiceApplication.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/model/AlternativeService.java, src/main/java/uk/gov/hmcts/divorce/divorcecase/tab/CaseTypeTab.java, src/test/java/uk/gov/hmcts/divorce/caseworker/CaseworkerResponseToServiceApplicationTest.java
The entire collection of uploaded documents (linked to the case) was displayed in the event, allowing caseworker to add or delete. CTSC has requested to remove this and allow upload of max 5 documents as part of this event.
https://tools.hmcts.net/jira/browse/NFDIV-4289
=> NFDIV-4289 Update to Caseworker Response to service application

.github/workflows/stale.yml
This introduces a new workflow to the repository to mark PRs and issues as stale after 12 days of inactivity and closed after further 2 days (in case of continued inactivity). Currently configured to run in debug mode only.
Certain labels (such as 'dependencies') will exempt PR from inclusion in the workflow.
https://tools.hmcts.net/jira/browse/NFDIV-4430
=> NFDIV-4430 - Introduce workflow to mark PRs and issues as stale or closed

.github/renovate.json, build.gradle
Newer versions of cft lib are only compatible with Java 21. We need to stop renovate auto-upgrading until case-api has been upgraded from Java 17 to 21.
https://tools.hmcts.net/jira/browse/NFDIV-4683
=> [NFDIV-4683] Make renovate ignore cft lib and downgrade to version compatible with Java 17

src/main/java/uk/gov/hmcts/divorce/systemupdate/event/SystemAlertApplicationNotReviewed.java, src/main/java/uk/gov/hmcts/divorce/systemupdate/event/SystemNotifyApplicantCanSwitchToSoleAfterIntentionFO.java, src/main/java/uk/gov/hmcts/divorce/systemupdate/event/SystemNotifyApplicantDisputeFormOverdue.java, src/main/java/uk/gov/hmcts/divorce/systemupdate/event/SystemNotifyApplicantPartnerNotAppliedForFinalOrder.java, src/main/java/uk/gov/hmcts/divorce/systemupdate/event/SystemNotifyJointApplicantCanSwitchToSole.java, src/main/java/uk/gov/hmcts/divorce/systemupdate/event/SystemNotifyRespondentApplyFinalOrder.java, src/main/java/uk/gov/hmcts/divorce/systemupdate/event/SystemRemindApplicant1ApplicationReviewed.java, src/main/java/uk/gov/hmcts/divorce/systemupdate/event/SystemRemindApplicant2.java, src/main/java/uk/gov/hmcts/divorce/systemupdate/event/SystemRemindApplicantsApplyForCOrder.java, src/main/java/uk/gov/hmcts/divorce/systemupdate/event/SystemRemindApplicantsApplyForFinalOrder.java, src/main/java/uk/gov/hmcts/divorce/systemupdate/event/SystemRemindAwaitingJointFinalOrder.java, src/main/java/uk/gov/hmcts/divorce/systemupdate/event/SystemRemindRespondentSolicitor.java, src/main/java/uk/gov/hmcts/divorce/systemupdate/service/CcdUpdateService.java, src/test/java/uk/gov/hmcts/divorce/systemupdate/event/SystemAlertApplicationNotReviewedTest.java, src/test/java/uk/gov/hmcts/divorce/systemupdate/event/SystemNotifyApplicantCanSwitchToSoleAfterIntentionFOTest.java, src/test/java/uk/gov/hmcts/divorce/systemupdate/event/SystemNotifyApplicantDisputeFormOverdueTest.java, src/test/java/uk/gov/hmcts/divorce/systemupdate/event/SystemNotifyApplicantPartnerNotAppliedForFinalOrderTest.java, src/test/java/uk/gov/hmcts/divorce/systemupdate/event/SystemNotifyJointApplicantCanSwitchToSoleTest.java, src/test/java/uk/gov/hmcts/divorce/systemupdate/event/SystemNotifyRespondentApplyFinalOrderTest.java, src/test/java/uk/gov/hmcts/divorce/systemupdate/event/SystemRemindApplicant1ApplicationReviewedTest.java, src/test/java/uk/gov/hmcts/divorce/systemupdate/event/SystemRemindApplicant2Test.java, src/test/java/uk/gov/hmcts/divorce/systemupdate/event/SystemRemindApplicantsApplyForCOrderTest.java, src/test/java/uk/gov/hmcts/divorce/systemupdate/event/SystemRemindApplicantsApplyForFinalOrderTest.java, src/test/java/uk/gov/hmcts/divorce/systemupdate/event/SystemRemindAwaitingJointFinalOrderTest.java, src/test/java/uk/gov/hmcts/divorce/systemupdate/event/SystemRemindRespondentSolicitorTest.java
We need to check whether notification flags are already set using CCD data rather than relying on queries against Elastic Search data.
https://tools.hmcts.net/jira/browse/NFDIV-5069
=> [NFDIV-5069] Make crons resilient to ElasticSearch outages
